### ISSUE TITLE
Unreliable "View on map" behaviour

### ISSUE THREAD

**Issue by richlv** [organicmaps/organicmaps#1003]
When search results are viewed on the map, many entities are hidden in a non-deterministic manner, making this view unreliable.
For example, one might want to see all suoermarkets Rimi on this side of the river here:
![IMG_9811](https://user-images.githubusercontent.com/112888/128237890-902c097b-d675-42da-9240-450523a98f7d.PNG)

This gives an impression that there are only 3-4 of them. But if we zoom in a bit:
![IMG_9812](https://user-images.githubusercontent.com/112888/128238096-9da3c08f-580c-4790-a719-2a4c7ed2537b.PNG)

That's several more - and notice how one of the previously displayed entities is now missing.
Let's zoom in some more
![IMG_9813](https://user-images.githubusercontent.com/112888/128238205-df8ca579-897a-49b7-985e-abdd7c4a23c4.PNG)

Oh, so there are plenty of supermarkets closer to the current location.
A bit more zoom?
![IMG_9814](https://user-images.githubusercontent.com/112888/128238321-474071e4-3729-44ba-8390-52c7ee316b94.PNG)

So that shows a whole bunch of supermarkets more - but we cannot be sure that some are not missing somewhere.

If space/overlapping is an issue, showing those smaller blue dots might be a good solution (seems to be already done for some entities?).
If performance is an issue with many entities found, only hiding the overlapping ones might be a solution, although grouping would be really great - perhaps a new feature request :)

The main problem is that the map view of search results is unreliable, and we can never be sure that all relevant entities are actually displayed - or we have to zoom in so much, the map view becomes useless.

**Comment by kikuok** [comment]
I also wanted to write about this problem, but I was afraid, but they will not understand me, since I have a google translator. I join and acknowledge this issue! This is very uncomfortable for me too! I am a tourist and I am looking for points of interest on the map and on the screen does not show them all! Because of this, I am very sad, because in order to see all the sights, you have to zoom in on the map as much as possible, and this is VERY inconvenient when searching for a route.

Here's what I suggest: make ALL search results appear on the map at a time, regardless of the zoom. This makes life and search very easy. Thank you for your attention.

**Comment by rtsisyk** [comment]
Probably similar to #1011

**Comment by Jean-BaptisteC** [comment]
Fixed by #3709

**Comment by richlv** [comment]
Yay, thank you - what should users expect now, will all found entities be always shown in the map view?

**Comment by biodranik** [comment]
@richlv please let us know if it doesn't work for you.
