### ISSUE TITLE
Bottom Toolbar Not Showing on Android after search

### ISSUE THREAD

**Issue by gthbusrr** [organicmaps/organicmaps#1065]
# Issue Description
Bottom Toolbar not showing

# Step to reproduce
1. Open the app
2. Click the magnifying glass icon to search
3. **TYPE IN** search query string, then press `return` key on keyboard
4. As usually there will be no results shown on map in current viewport (would be great if it will automatically zoom out to show at least some result), click `Lists` in the bottom toolbar to bring up result list
5. Select specific result (doesn't matter which one)
6. Tara! Bottom toolbar empty.

# Environment
**App Version**: 2021.08.05-15-g31e5587abd-FDroid  
**Data version**: 210729er
**Device Manufacturer**: Samsung
**Device Model Name** Galaxy Note20 Ultra 5G
**Device Model Number**:SM-N9860
**Android Version**: 11

**Comment by biodranik** [comment]
Awesome, thanks!
@Endem10n can you please take a look?

**Comment by rtsisyk** [comment]
One more test case: 

https://user-images.githubusercontent.com/1799054/129166318-5554c83c-5e79-4206-beea-5f58bf0e4270.mp4

**Comment by biodranik** [comment]
Steps to reproduce:

From the home screen, tap in the search.

Enter in GPS coordinates, example 41.645808,-79.171094

Perform the search.

User is navigated to the location on the map

This is where the tools on the bottom will frequently not show up.   It occasionally happens when selecting a location on the map as well, but SEEMS to be more prevalent after a search.  Typically, this will happen a few times, and I'll force close and restart the app a few times and it will eventually work.  I doubt it's related to specific coordinates, but the ones in the example were particularly problematic yesterday.  It took roughly 20 restarts of the app, performing the same process each time to get it to work.
