### ISSUE TITLE
[android] Google TTS is too fast

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#1080]
https://user-images.githubusercontent.com/1799054/129158159-ea13633d-0d07-48e6-ba70-bd6d2eed4896.mp4

A fresh stock Android 12 on Google Pixel with preinstalled Google TTS libraries.

**Comment by biodranik** [comment]
Why do you think it's bad? For high speeds it's good to hear direction earlier.

How fast is it on other devices?

**Comment by Endem10n** [comment]
What exactly is the bug?

**Comment by rtsisyk** [comment]
>Why do you think it's bad? For high speeds it's good to hear direction earlier.

Sounds unnatural. It would be better to slow down the voice a bit.

**Comment by bugnano** [comment]
The same problem happens when using RHVoice as the TTS engine.

This is a problem, as not everyone is able to understand what the TTS voice is saying at that speed, especially if English is not your first language.

The obvious solution would be to respect the speed settings configured in the Android Settings app, alternatively you could make the TTS speed configurable from Organic Maps.

> Why do you think it's bad? For high speeds it's good to hear direction earlier.

Hearing directions earlier is not the same as hearing directions faster.

**Comment by biodranik** [comment]
If the system speed setting is not respected now, then it's an obvious bug which should be fixed.

**Comment by biodranik** [comment]
Google TTS speed settings are ignored ATM, confirmed with another user. That is a bug.

**Comment by M1Aston** [comment]
I agree. The voice is unnaturally fast.
It gets on my nerves. :-)

**Comment by biodranik** [comment]
@M1Aston what is your Android version?

**Comment by M1Aston** [comment]
A have a somewhat old phone, :-)
Android 8.0.0
