### ISSUE TITLE
Brands integration (logos-thumbnails)

### ISSUE THREAD

**Issue by ghost** [organicmaps/organicmaps#1211]
It would be nice for Organic Maps to show brand logos on the map instead of the shop=supermarket icon **for example**.
OpenStreetMap's ID Editor shows LOGOS for nodes that have brand tag and that brand is in its database.
![brand](https://user-images.githubusercontent.com/82209775/131323405-a4769065-8e05-4445-b70a-be388f67fbf7.png)
It would make appearance of the map better and easier to find something. I think ID editor uses wikidata to pull info and LOGO for a brand, would it be possible for Organic Maps to do the same?

**Comment by biodranik** [comment]
There is a discussion in #1052 about brands. Some people think that it will provide an unfair advantage for those shops with unique icons.

**Comment by starwatcher11** [comment]
Sorry, I didn't look there for my feature request, I only searched on Issues before posting.
I read the discussion and I agree with some points that it provides unfair advantage to those brands. I hope you implement some kind of solution that keeps a balance between smaller and bigger stores.
Perhaps one solution would be only when searching for the specific brand, then the icons would appear on the map.

**Comment by starwatcher11** [comment]
This feature would be very useful for Organic Maps. I understand the reasoning that you don't want to advertise big brands, giving them unfair advantages over smaller, traditional shops. However, there are some shop categories that this concern is not applicable and would certainly be useful to see their logo on the map or make searching easier:

    banks
    gas stations
    mobile_phone shops (for example Vodafone, Deutsche Telekom, AT&T, etc.)
    energy_supplier shops
    post_office or courier shops

One thing that I'd like to point out is that you'll have to take into account popular brands by country. Showing only world-wide or US brands only would be pointless since not all multinational companies are active in every country. I don't know how you're going to be implementing this but certainly you could simply take every brand that ID editor has in its database and include it in your app.

**Comment by dbf256** [comment]
Please don't pollute clean and consistent organic maps ui with logos.

**Comment by patepelo** [comment]
While for some users it would be a good feature, for many other it isn't well received. In any way, thanks for reaching out and giving ideas. Please keep doing so. I'm closing this issue as not planned. Anyone feel free to keep adding comments if you feel so.
