### ISSUE TITLE
Not optimal driving route

### ISSUE THREAD

**Issue by syborgxx** [organicmaps/organicmaps#1271]
I created a route from Ventura, CA to Los Angeles International Airport. The route that OM calculated includes many instances where the direction is to exit the freeway and then immediately enter the freeway. Here is an example where OM directed this behavior for two consecutive exits.
![Screenshot_20210908-082624_Trebuchet](https://user-images.githubusercontent.com/81539304/132545437-2fdd7ccc-b3a3-4fbf-91f3-c3bfc6fb96d0.png)

**Comment by vng** [comment]
Well, that is definitely looks bad, but let's look at Triunfo Corner.

[This](https://www.openstreetmap.org/way/43720426) Ventura Freeway has maxspeed=55;
[This](https://www.openstreetmap.org/way/40033989) connected link and [this](https://www.openstreetmap.org/way/700440615) and [this](https://www.openstreetmap.org/way/778741649) has maxspeed=65;

Do you familiar with the ground truth there and is it possible at all?

**Comment by vng** [comment]
So the app works straightforward here and choose more "speedy" ways here. Of course, we should add traffic light penalties here and it's in our plans.

**Comment by zyphlar** [comment]
I've held off commenting on other "suboptimal routing" issues or making my own because I'm sure eventually it'll get better, but yeah the routing algorithm seems boneheaded at best. For example it'll often tell me to make four rights and a left, going around the whole neighborhood, instead of two lefts and a right, the intuitively shortest path. Or it'll tell me to turn and take residential streets instead of tertiary streets... and then turn back onto the tertiary street anyway. It could be nice to save a few theoretical MPH or stoplights, but not this aggressively. In general, the fewest number of turns is probably the best.

**Comment by biodranik** [comment]
@zyphlar please send us wrong examples to email (or share here). Current algo relies on OSM data, and if something is weird, in 90% of cases it's related to OSM data (max speed, road type, etc). And it can be fixed by editing OpenStreetMap.

**Comment by syborgxx** [comment]
It looks to me like there are issues with the map. The freeway should be 
65 and the on and off ramps should not be 65. I'm making some 
corrections to OSM.

**Comment by zyphlar** [comment]
Ah I just looked into the weird issue in my area. I bet because the Primary road that's sensible to use is tagged as 25mph, but the Tertiary road next to it isn't tagged with a speed limit (probably 20mph by statute but no signage) there's an assumption that I'll save time by switching.

Even if this is what's happening that's a bad assumption though. The distance is like 5 blocks and it adds 4 turns to the route so it should be considered a lot of hassle for maybe a few seconds of benefit. (The Tertiary road has a dead end later, so I always have to get back on the Primary road anyway. Speed limit or not, it's a silly move.)

**Comment by biodranik** [comment]
The proper solution would show alternate routes too. We plan it.

**Comment by zyphlar** [comment]
Does the current algorithm consider number of turns? Even if each turn took five seconds and I sped on the Tertiary road I don't think it would be faster.

**Comment by biodranik** [comment]
@vng Not yet as I remember. It also does not count traffic lights yet.

**Comment by zyphlar** [comment]
That'll do it. Considering each turn to be say 30-60 seconds' worth would improve the algorithm substantially. More turns just to maybe save a few seconds encourages insane driving and creates traffic flow nightmares, and would eliminate these sorts of "well there was a slight speed limit change for this one mile stretch so..." bugs

**Comment by vng** [comment]
Fixed. Please, check on the latest app and maps data version (220103).

**Comment by syborgxx** [comment]
I just downloaded the latest app and maps. As you can see in the attached screenshots the app is still routing off then immediately back on to the freeway on some instances.

On January 26, 2022 12:27:13 PM PST, Viktor Govako ***@***.***> wrote:
>Fixed. Please, check on the latest app and maps data version (220103).
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/organicmaps/organicmaps/issues/1271#issuecomment-1022574381
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by biodranik** [comment]
There is no attached screenshot, it's not automatically attached from email replies, unfortunately.

**Comment by syborgxx** [comment]
Okay. You should get them now.

![Screenshot_20220126-132401_Trebuchet](https://user-images.githubusercontent.com/81539304/151262112-4f4646df-4433-47dc-8f95-9be4564cd866.png)
![Screenshot_20220126-132300_Trebuchet](https://user-images.githubusercontent.com/81539304/151262130-17d79d45-d9f3-4c73-a428-0491c0838f05.png)

**Comment by biodranik** [comment]
Just to check, do you have an FDroid version? If yes, did you update it or uninstall/install it? Currently, there is a bug with a not updated world map that can sometimes influence the routing (although it should not be this case).
Note: uninstall now deletes all bookmarks.

**Comment by syborgxx** [comment]
Yes f-droid version. Uninstalled the old and installed the new. I also deleted data and cache before installing.

On January 26, 2022 3:15:29 PM PST, Alexander Borsuk ***@***.***> wrote:
>Just to check, do you have an FDroid version? If yes, did you update it or uninstall/install it? Currently, there is a bug with a not updated world map that can sometimes influence the routing (although it should not be this case).
>Note: uninstall now deletes all bookmarks.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/organicmaps/organicmaps/issues/1271#issuecomment-1022690483
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vng** [comment]
Yes, confirm here https://www.openstreetmap.org/#map=19/34.17712/-118.87673

**Comment by syborgxx** [comment]
Yes, that is one of the two areas identified.
