### ISSUE TITLE
Navigation showing wrong path.

### ISSUE THREAD

**Issue by hurelhuyag** [organicmaps/organicmaps#1327]
I fixed the road map for Tes town a few years ago. It is working fine on the OsmAnd app. But MapsMe and OrganicMaps both are showing the wrong road path. 

From: https://www.openstreetmap.org/node/250944260#map=10/49.9803/92.0689&layers=YG
To: https://www.openstreetmap.org/node/1434103666#map=12/50.4777/93.5942&layers=YG

OrganicMaps route:
![Screenshot_20210921-125305](https://user-images.githubusercontent.com/1059242/134114406-d0a233de-9b59-4c9b-8775-9b02f5396eff.png)

OsmAnd route:
![Screenshot_20210921-120704](https://user-images.githubusercontent.com/1059242/134114415-6beba89a-ac82-452c-8a6b-af3650c5f22b.png)

**Comment by vng** [comment]
Well, definitely not good here. The reason is that app prefers [highway=tertiary] road instead of [highway=secondary, surface=gravel]. If _surface_ tag is not set, the app assumes [surface=asphalt] by default, so it routes from [this](https://www.openstreetmap.org/way/51590693) road and further.

We should definitely tweak this priorities for tertiary, residential, living_street, service, track, unclassified roads!

@hurelhuyag If you are familiar with this area, please, define surface for other nearby roads (I suspect it should be gravel too).
