### ISSUE TITLE
[routing] Cross-mwm doesn't work in the Great Belt Bridge in Denmark

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1389]
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=55.3075%2C10.8145%3B55.3486%2C11.1200#map=11/55.3344/11.0531

@vng OSM data looks ok. Please take a deeper look.

**Comment by vng** [comment]
Will be fixed in #1544, but keep open for the generator fixes.

Increment RouteWeight.m_numAccessChanges only when access is getting worse. Now it's always > 0 even in this case:
https://www.openstreetmap.org/#map=19/55.32997/10.95824.
E20 edge has m_numAccessChanges = 1, because of adjacent private link ?!
