### ISSUE TITLE
Landscape mode content density

### ISSUE THREAD

**Issue by Donkey-Doug** [organicmaps/organicmaps#1411]
The bottom and top bars take up too much space in landscape mode. I suggest grouping them: add the curremt street name to the bottom bar and remove the top bar.

![Screenshot_20211011-020457_Organic_Maps_1](https://user-images.githubusercontent.com/50382414/136717445-ccf1cd4b-2f3b-41f7-9df3-576f333988e4.png)

**Comment by biodranik** [comment]
Even better would be to put control elements on the left (for left-wheel cars) and center the map in the right part, as CarPlay does. Then the crucial vertical space will be 100% available for the map.

**Comment by zyphlar** [comment]
I agree that the side controls are on matters greatly by country driving handedness. I would probably crash trying to use controls on the left edge of the screen, because in America I'm holding the wheel with my left hand, touching the phone with my right hand, and using the right edge of the phone as an index. Then again I know some people mount their phones between the wheel and door instead of the center so maybe it needs to just be a preference.

**Comment by RedAuburn** [comment]
this issue is resolved now:
![Screenshot_20230830-222512_Organic Maps](https://github.com/organicmaps/organicmaps/assets/26939824/ed0b4d37-9b34-46af-bfcf-393cf47a540f)
