### ISSUE TITLE
Exclude garden:type=residential from garden POIs

### ISSUE THREAD

**Issue by kudlav** [organicmaps/organicmaps#1746]
Hi,
all [`garden:type=residential`](https://wiki.openstreetmap.org/wiki/Key:garden:type) are displayed on the map.
Those points are not useful for the public. The map is quite bloated with them and for example it can be easy to overlook usefull POIs.
https://omaps.app/44G1RBEYFx/

In the Czech Republic, we have mostly residental type: [czTaginfo](https://taginfo.openstreetmap.cz//keys/garden:type) (more than 1/3 of `garden:type` global usage: [globalTaginfo](https://taginfo.openstreetmap.org/keys/garden:type)).

![screenshot](https://user-images.githubusercontent.com/11516259/147412721-a7f33b85-c26c-42eb-a29b-6c912f326d02.png)

Similar bug report:
https://github.com/openmaptiles/openmaptiles/issues/1127

**Comment by biodranik** [comment]
I think the fix should remove icons. Right?

**Comment by kudlav** [comment]
Hi, I the Organic Maps would exclude residental type, yes, then there won't be any garden icon on the map.
From my view, it is fix, but generally this is just my propose.

**Comment by vng** [comment]
Well, the only idea is to make subtype leisure-garden-residential and don't draw icon for it.

**Comment by biodranik** [comment]
@pnmrnko what about motivating users to edit objects and add additional info to them by showing their icons?

**Comment by pnmrnko** [comment]
@biodranik Maybe it would be good for some users. For me and I think that for most Organic Maps has always been an application for viewing the map and not for editing. In any case, it will be a pleasure for me to use this application. Thanks to the developers!

**Comment by mpawelski** [comment]
from https://github.com/organicmaps/organicmaps/pull/3386 (I'm writing here to have discussion in one place)

> As I mentioned in the referenced issue, what about motivating users to edit/add missing data by showing clickable icons?

Good point, but I think showing icons for "named" gardens,forests,parks is enough in this case. For such places you can still easily click an icon to edit, for example, the opening hours (some parks and gardens are closed at night) and other info.

> What about hiding icons if the area of the feature is below a certain threshold?

This idea also crossed my mind. By I think it would be hard to came up with good threshold. In practice I also find small named `landuse=garden` (like the "[Skwer](https://pl.wikipedia.org/wiki/Skwer)" screenshot I [posted](https://github.com/organicmaps/organicmaps/pull/3386#issue-1368753721) in PR). This areas are quite small (for example a small "greenery" area in the middle of a street junction) and often have some sign with the name of the place (usually to commemorate someone).

---

The main problem [this PR](https://github.com/organicmaps/organicmaps/pull/3386) ties to solve is that `landuse=garden` (and to some lesser extend also `landuse=forest`s and `leisure=park`s) are often used for small "public greenery" areas that for me are the same significance as `landuse=grass`. And we don't show icon for `landuse=grass` (for a good reason). But on the other hand this tags are also used for bigger places, that can even have paid entrance and opening hours.

And I think that showing icons for "named" `landuse=forest`, `leisure=park`, `landuse=garden` areas is a really good practical heuristic to tell the significance of such places. Named places will still be easy to edit (without need to hold the finger on an area which is not very discoverable) plus such areas (even small) are still good for navigation because often in the real life there are signs with the name of such area.

**Comment by biodranik** [comment]
You've mentioned an important point here. Shouldn't these areas be marked as landuse=grass instead? E.g. if these pieces of land are mapped incorrectly, it would be a very bad way to avoid fixing it by hiding icons instead of properly re-tagging it.

**Comment by kudlav** [comment]
Nope, grass and garden are different things in the real world and it is totally fine to be mapped differently.
Everyone in our street has a garden, it's fine to be mapped, but it's not ok to be rendered as poi (for example).
see https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dgarden

**Comment by mpawelski** [comment]
> You've mentioned an important point here. Shouldn't these areas be marked as landuse=grass instead? E.g. if these pieces of land are mapped incorrectly, it would be a very bad way to avoid fixing it by hiding icons instead of properly re-tagging it.

IMO it should not be landuse=grass for sure. This are different things, as @kudlav said.

However, for me a lot of this places should be mapped as [`natural=shrubbery`](https://wiki.openstreetmap.org/wiki/Tag:natural=shrubbery) which is quite a new tag which unfortunately seems to be quite controversial (osm-carto decided [against rendering](https://github.com/gravitystorm/openstreetmap-carto/issues/4473) it.

But even if `natural=shrubbery` was less controversial and widely supported there still we be a lot of natural=shrubberyin use because for a long time there was no tag specifically for "maintained city greenery". And to be honest, before  `natural=shrubbery` (which I support) I would also in many case tag such areas as "garden" because it is quite vague term (as I described previously can be used for huge named facility or small part of city greenery).

To be honest the current tag situation for a "maintained city greenery" is kind of a mess. I see `leisure=garden` used for such areas most often. But I also see places where people use different tag for this purpose (like [`landuse=village_green`](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dvillage_green) or even [`landuse=flowerbed`](https://wiki.openstreetmap.org/wiki/Pl:Tag:landuse%3Dflowerbed), not to mention the new `natural=shrubbery`)

I think we need to accept how people currently use the `leisure=garden` tag and not discuss much how it should be tagged better. Because IMO, I don't see clear consensus in OSM community around it.

**Comment by mpawelski** [comment]
> You've mentioned an important point here. Shouldn't these areas be marked as landuse=grass instead? E.g. if these pieces of land are mapped incorrectly, it would be a very bad way to avoid fixing it by hiding icons instead of properly re-tagging it.

Just one last remark to make myself clear. 
I meant, the examples me and @pnmrnko provided are tagged correctly. I don't see clear OSM community consensus that such areas can be tagged better (IMO `natural=shrubbery` is better but this is just my opinion which some people disagree with)

**Comment by biodranik** [comment]
Ok. Let's merge #3386 for now.

@mpawelski @kudlav can you please make a list of mappings of the "similar" styles in OSM so we can easily replace them on the generation stage and map to one of our existing styles? E.g. map `natural=shrubbery` to `landuse=garden`, so these tags will be rendered in OM in the same way as some of our already existing tags?

Or you can make a PR with changes in data/replaced_tags.txt

**Comment by mpawelski** [comment]
I think we render most "green areas" right now in OM, but we don't use data/replaced_tags.txt often, we just style this areas in similar way (so they are different types and they show different names when you select them)

The missing ones that I found I would also not put in data/replaced_tags.txt, I would just style them in similar way.


This "green areas" tags that I miss the most are:
- [landuse=flowerbed](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dvillage_green) - quite popular (36k usage), [not rendered on osm.org](https://github.com/gravitystorm/openstreetmap-carto/issues/4564). Rendering it as `leisure=garden` would be better than nothing, but we can discuss how to render it better. This was mentioned [before](https://github.com/organicmaps/organicmaps/issues/3139#issuecomment-1209572295).
- [natural=shrubbery](https://wiki.openstreetmap.org/wiki/Tag:natural=shrubbery) - Usage pretty decent (almost 12k and growing) but, as I mentioned, osm-carto decided [against rendering](https://github.com/gravitystorm/openstreetmap-carto/issues/4473) it). I don't agree with osm-carto decision and was thinking about rendering this area with the same color as `barrier=hedge` (I _love_ that we render hedges now), because it's often recommended to use this tag also for hedge areas since `barrier=hedge` + `area=yes` [stopped](https://github.com/gravitystorm/openstreetmap-carto/pull/3844) being rendered as area in osm-carto. The [wiki](https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dhedge) for `barrier=hedge` also is saying to use `natural=shrubbery` for areas (it used to say that  `barrier=hedge` + `area=yes` could be used for hedge's areas but apparently OSM community decided against it)

This two are the most important missing "green areas" for me. Probably there are some more that we don't render but I didn't check all the tags.
