### ISSUE TITLE
[Android] Show opening hours week schedule in sequential order

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#1825]
Week schedule of a POI shows closed days at the bottom. I did it for Android because iOS has the same UI.
See [comment](https://github.com/organicmaps/organicmaps/pull/1599#issuecomment-1006774284) in PR #1599.
<img src="https://user-images.githubusercontent.com/39647898/148424778-85839984-fc05-4306-bfe3-670374369a6c.jpg" width="500px"/>

**Expected result:** weekdays in the schedule should go sequentially.

**Question:** What should be the first week day? I think device locale should be parsed to detect if Monday or Sunday should be the first week day.

**Comment by strump** [comment]
@biodranik pleas assign this ticket to me

**Comment by biodranik** [comment]
@strump you're always welcome!

**Comment by strump** [comment]
In case of sparse week days `"Mo,We,Fr 09:00-18:00"` week schedule should look like:

* Mo - 09:00-18:00
* Tu - Closed
* We - 09:00-18:00
* Th - Closed
* Fr - 09:00-18:00
* Sa-Su - Closed

Need more time to implement this.

**Comment by strump** [comment]
@xephos1one, could you please update OrganicMaps to version 2022-02-19 and verify if opening hours schedule look correct.

**Comment by xephos1one** [comment]
@strump 
I'm now on 2022.02.19-1-Google and the example at the top is still the same as before.
I think it's not fixed in that version yet so we'll have to wait until the next release.

And here are some other opening hours that currently behave strangely thay may be fixed with your commit:

Sunday somewhere in the middle and even before wednesday (Mi)
Mo 11:00-22:00; We-Su 11:00-22:00
![Screenshot_20220223-133126](https://user-images.githubusercontent.com/39647898/155394358-207873a1-2e66-4ec9-b77a-008a69d72be8.jpg)

Sunday named before Saturday:
Mo 07:30-18:00; Tu 10:00-20:00; We 09:00-14:00; Th 07:30-18:00; Fr 07:30-12:00; PH off
![Screenshot_20220223-132853](https://user-images.githubusercontent.com/39647898/155394680-1db0eb71-4cb3-4c8a-ad11-cb38cb054f39.jpg)

**Comment by strump** [comment]
@xephos1one , OrganicMaps update released this week `2022.03.23-4-Google`. Please install latest version from Google Play and check if issue is fixed.

**Comment by xephos1one** [comment]
It's looking great 👌 
Thanks
