### ISSUE TITLE
[android] Extra space on the top and left side in Settings

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1872]
![image](https://user-images.githubusercontent.com/170263/149722160-b8636aee-59d9-473e-83f3-05c4dfeae492.png)

**Comment by stloeffler** [comment]
The linked PR fixes the horizontal spacing. Note that this actually goes against the [material design guidelines](https://material.io/design/platform-guidance/android-settings.html), but it seems beneficial to me in the present case.

Regarding the vertical spacing at the top: this seems to be related to a camera cutout. When no camera cutout is [configured in the emulator](https://stackoverflow.com/a/52872669), everything looks normal for me. When I turn on the camera cutout, it looks like in your screenshot. This seems to be [by design](https://proandroiddev.com/android-material-toolbar-vs-displaycutout-6ae99b2b7ef0) to avoid the text "Settings" to "run through" the cutout. Note that on my physical device, the bar at the top is far less pronounced and really just encompasses the status bar (and the camera cutout).

**Comment by biodranik** [comment]
> Note that this actually goes against the [material design guidelines](https://material.io/design/platform-guidance/android-settings.html), but it seems beneficial to me in the present case.

+100500
We prioritize users, not guidelines.
