### ISSUE TITLE
Better rendering priorities for towns

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#1995]
Here is a screenshot of the app with the map of the area to the south of Vienna, Austria. The largest towns/cities here are (north-to-south) Mödling, Baden, and Wiener Neustadt. However, *none* of the labels shown on the map names those. While I more or less know this area and can navigate there regardless, this would not be true for somewhere unknown.

In short: labels are apparently not ordered by priority. The app should show the most important labels when it doesn't have much space (low zoom level), not some random ones.

Mödling: https://www.openstreetmap.org/relation/152072#map=10/48.0331/16.5337
Baden: https://www.openstreetmap.org/relation/111479#map=10/47.9931/16.1856
Wiener Neustadt: https://www.openstreetmap.org/relation/110451#map=10/47.9380/16.2076

You can even see them in your own app if you zoom out until details are not shown, only overview: label selection seems better there, though e.g. "Wiener Neustädter Pforte" shouldn't be shown, it's not a major geographical feature (e.g. only Wikipedia entry is in German).

![image](https://user-images.githubusercontent.com/170263/152078070-52a03e0d-0aa7-4990-b710-1a1cf54b5cdf.png)

**Comment by j5k** [comment]
I described a possible solution here: #1446 . Using of **wikipedia page view** can estimate the real priority very well.

**Comment by anton-koerbchen** [comment]
It should be even easier than that. E.g. Schöffelstadt is a part (district, not sure if even official) of Mödling. Militärflugplatz WNW is a military airbase in Wiener Neustadt. Two labels should be covered by trivial logic: don't show labels for objects in cities when they would overlap the label for the city itself (or: when the map is zoomed out enough to show the whole city). Baden would be a bit more tricky, but it should win out over Traiskirchen and Bad Vöslau due to being Bezirk Haupstadt, i.e. region capital or how it is called. Pretty sure OSM has this data.

**Comment by pastk** [comment]
In this particular case it seems like a bug in our styles also.

All 3 localities mentioned are `place=town` with a population between 20k and 39k.

Hence z10 rule doesn't work for them, although z9 and z11 do (but on z11 there are too many competing labels around).

https://github.com/organicmaps/organicmaps/blob/998d5cd0c88d3babc170a951f9264d351a5e5f3e/data/styles/clear/include/Basemap_label.mapcss#L347-L360

It should read `node|z10[place=town][population>=20000]` I think.

**Comment by pastk** [comment]
![Screenshot_1643997549](https://user-images.githubusercontent.com/18434508/152579487-1f78b45b-288f-4f9c-b0f5-fa09252e4709.png)
