### ISSUE TITLE
Improve fences and walls rendering

### ISSUE THREAD

**Issue by pastk** [organicmaps/organicmaps#2063]
At the moment fences, walls, hedges etc. are rendered as a very thin dotted line which is barely visible on the map, though its an important information for pedestrians and hikers.

![Screenshot_1644352467](https://user-images.githubusercontent.com/18434508/153071210-0e4f163a-339a-4135-ba0a-881d2820b2e8.png)

Let's make rendering more prominent and perhaps different for walls and fences (and maybe hedges too).

Samples:
fence https://www.openstreetmap.org/way/631353746
city_wall https://www.openstreetmap.org/way/129425886

### Discussed in https://github.com/organicmaps/organicmaps/discussions/2046

**Comment by pastk** [comment]
The current rendering rules:

https://github.com/organicmaps/organicmaps/blob/71de1db197343b8e02dada281327d99c74de3bdc/data/styles/clear/include/Basemap.mapcss#L670-L700

**Comment by aeshaganatra** [comment]
@biodranik  @rtsisyk  
I want to solve this issue. can you please give a hint on where to start looking at this code? as I am new to development, I have successfully done the local setup. 

thanks in advance.

**Comment by biodranik** [comment]
Check drape rendering engine.

**Comment by pastk** [comment]
@aeshaganatra please see [my comment above](https://github.com/organicmaps/organicmaps/issues/2063#issuecomment-1034082813) with a link to rendering rules.

Here is [documentation](https://github.com/organicmaps/organicmaps/blob/master/docs/STYLES.md) on details how to change and test it.

If you have any questions - feel free to ask!

**Comment by aeshaganatra** [comment]
@biodranik @pastk  
I'm trying to change above mention files. but while running the script  "tools/unix/generate_drules.sh", I have encountered this error. This should not happen, because in mapCss StyleChooser is present.  Have you ever occurred with this issue? 



rm: cannot remove 'tools/unix/../../data/classificator.txt': No such file or directory
rm: cannot remove 'tools/unix/../../data/types.txt': No such file or directory
rm: cannot remove 'tools/unix/../../data/visibility.txt': No such file or directory
rm: cannot remove 'tools/unix/../../data/colors.txt': No such file or directory
rm: cannot remove 'tools/unix/../../data/patterns.txt': No such file or directory
Building drawing rules for style clear/clear
rm: cannot remove 'tools/unix/../../data/drules_proto_clear.bin': No such file or directory
rm: cannot remove 'tools/unix/../../data/drules_proto_clear.txt': No such file or directory
Traceback (most recent call last):
  File "tools/unix/../../tools/kothic/src/libkomwm.py", line 1, in <module>
    from mapcss import MapCSS
  File "/home/abbas/devlopment/organicmaps/tools/kothic/src/mapcss/__init__.py", line 21, in <module>
    from StyleChooser import StyleChooser
ModuleNotFoundError: No module named 'StyleChooser'

**Comment by biodranik** [comment]
Looks like a python issue

**Comment by endim8** [comment]
> Have you ever occurred with this issue?

Make sure you've cloned the submodules, you can do this if you've already cloned the repo by running `git submodule update --init`

On the topic of fence rendering, https://github.com/organicmaps/organicmaps/issues/2275 should also be considered, although it's much more complex

**Comment by aeshaganatra** [comment]
@endim8 which python version you're using?
I'm using 3.6.0. 
I tried 
> git submodule update --init

but still not working for me.

**Comment by biodranik** [comment]
@pastk we need to finish kothic's migration to python3.

**Comment by pastk** [comment]
> @endim8 which python version you're using? I'm using 3.6.0. I tried
> 
> > git submodule update --init
> 
> but still not working for me.

Unfortunately scripts in `organicmaps/tools/kothic/*` require python 2.x still.
Do you have an opportunity to install python 2 alongside 3?
