### ISSUE TITLE
Change icon for Fuel Dispenser

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#2121]
The current rendering of a Fuel Dispenser has a vending machine icon, which is confusing. Could this possibly be replaced with something like a gas station icon?![image](https://user-images.githubusercontent.com/50059322/153990558-2f2bd8d6-4b18-44ea-ac86-8f117b76e341.jpeg)

**Comment by biodranik** [comment]
How does the Gas Station icon mix/overlap with fuel dispensers? Should dispensers be drawn only on the last zoom level?

**Comment by pastk** [comment]
At the moment fuel dispensers use the same icon and drawing rules as generic vending machines (display from z17-).

Yeap its a good idea to move them to z18 or z19 even and maybe use a small fuel icon ![fuel-s](https://user-images.githubusercontent.com/18434508/154032561-1c6dbfee-323c-4b4d-b551-b33195324706.svg) and less opacity - though the map might look less consistent because all other features use "medium" size icons at these zoom levels (e.g. ![fuel-m](https://user-images.githubusercontent.com/18434508/154032855-dc3da702-7a9b-438b-b176-88b3c6284719.svg))?

**Comment by pastk** [comment]
My understanding that in most cases fuel dispensers will be inside fuel stations `amenity=fuel` which have a proper icon already.
But probably there are cases with standalone fuel dispensers.

**Comment by biodranik** [comment]
Can we draw them with smaller icons, but WITHOUT a circle?

**Comment by j5k** [comment]
The same for "Excrement Bags Dispenser" which is also confusing with this icon.

**Comment by pastk** [comment]
**TODO:**

extract an inner shape from `data/styles/clear/style-clear/symbols/fuel-s.svg` and make a new icon based on it; make `[amenity=vending_machine][vending=fuel]` to use a new icon in `data/styles/clear/include/Icons.mapcss` and in `data/styles/vehicle/include/Icons.mapcss`

for the `vending=excrement_bags` we need to find a new icon (with an appropriate license) or draw it

**Comment by pastk** [comment]
Also check [this doc](https://github.com/organicmaps/organicmaps/blob/master/docs/STYLES.md) for a better understanding of styles and icons update workflow.

**Comment by santapan345** [comment]
Thank you
