### ISSUE TITLE
Disable automatic returning back to the "north-up" when rotating a map for a few degrees

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2219]
Some users say that it is annoying. The map can always be returned back into the "north-up" mode by clicking a compass button.

**Comment by Markus40** [comment]
I think it should be an option otherwise it is too easy to rotate it an few degrees when zooming and having to click the compass button. There could be three options:

1: current behaviour
2: like the current behaviour but don't latch onto north when the map was already rotated
3: don't latch onto north

**Comment by andrewshadura** [comment]
Related: #609, #1348, #1691.
