### ISSUE TITLE
Make it easier to load routes into OMAPS

### ISSUE THREAD

**Issue by smartyw** [organicmaps/organicmaps#228]
Regarding the Android mobile app:

It has always seemed difficult to load route files (e.g. KML files) into the bookmarks list. Maybe there's a procedure I'm unaware of, but I download my KML file (e.g. from Google Drive), find it in the file system, use the Share operation to send it to myself by email, open the email and then tap to open the file attachment. At this point, I am offered several applications with which to open the file and one of then is OMAPS. I select OMAPS, the app launches and my KML file is in the bookmarks list.

If there is an easier way, then perhaps a UI change would make this more obvious.

If there currently is not, perhaps there could be. An IMPORT button in the Bookmarks list might work, for example.

Thanks in anticipation

**Comment by ioctl-user** [comment]
In addition to this request:
If you will implement "import" button, please allow multiple files importing at once.
And multiple file exporting also very useful.

This can be used to backup/restore app data, and for sharing multiple bookmarks with other people.

Alternatively, standard KML/KMZ files can be used instead of KMB to store bookmarks.

Old maps.me stored bookmarks in KMZ files some years ago, so, there was no such problems. But for now proprietary binary format is used.

**Comment by rtsisyk** [comment]
>Old maps.me stored bookmarks in KMZ files some years ago, so, there was no such problems. But for now proprietary binary format is used.

Done

**Comment by ioctl-user** [comment]
> Done

I cannot find new bookmarks in the /sdcard/Android/ subdirectories.
Where did they stored?

**Comment by smartyw** [comment]
The IMPORT BOOKMARKS functions works well in Organic Maps. I don't see any need for anything to change now.

**Comment by ioctl-user** [comment]
Import is working, but complementary export is not. Multiple export is not implemented. Single kml export implemented but not working

**Comment by smartyw** [comment]
@ioctl-user I think you should open a new issue about Export. This issue is about importing kml.
