### ISSUE TITLE
Will OM get slower if you download more maps?

### ISSUE THREAD

**Issue by GutHib** [organicmaps/organicmaps#2291]
Hi guys,

Long-time Maps.me user - came across OM a few weeks ago and couldn’t be happier. It’s much faster and the GPS also seems to be working better. And the maps are finally up-to-date again (Maps.me became so bloated that I resorted to using an older version, but at some point Maps.me stopped to provide map updates for it). So I just sent a small donation to support the project.

Question: Will OM also get slower if there are more maps on the phone? With Maps.me, if you downloaded all the maps of the world, it would take almost half a minute to start, because Maps.me insists on preloading all maps on startup. Thanks!

**Comment by biodranik** [comment]
Please don't create issues for questions like this one, there are [Discussions](https://github.com/organicmaps/organicmaps/discussions) for that. I assume that you use Android and you store maps on SD card. The problem is in the slow SD. If you get the fastest possible SD card or store maps on the internal memory, the startup will be faster.

Maps are quickly scanned on the startup, but due to the slow SD it takes visibly way more time.
