### ISSUE TITLE
[android] Current location jumps due to unfiltered network locations

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#2302]
[logs (9).zip](https://github.com/organicmaps/organicmaps/files/8360689/logs.9.zip)
[logs (8).zip](https://github.com/organicmaps/organicmaps/files/8360690/logs.8.zip)

https://user-images.githubusercontent.com/170263/160351135-05a2494a-d7e8-4faa-98a1-481fb8e237e2.mp4

https://user-images.githubusercontent.com/170263/160351166-4849b939-0a15-40ea-b89a-04958cf7fd73.mp4

**Comment by rtsisyk** [comment]
This issue happened because `gps` and `fused` sources were accepted in the mix. Current implementation prioritizes `fused` location over any other sources (see 6c0b080235e5e359142e22db35bb90db9d386989). Google Play Location fused location still can jump in certain cases, but this is completely outside of our control.
