### ISSUE TITLE
Add Outdoors/Hiking map style

### ISSUE THREAD

**Issue by alensiljak** [organicmaps/organicmaps#2356]
As suggested in the parent topic #1577, this is a request specific to Hiking view of the map.

**Comment by julianfairfax** [comment]
I don't know if this is normal or not, but I entered a route and chose the walking option, only to have part of the route be a hiking trail. I was able to take the trail, but this might not always be the case depending on how equipped you are to go hiking vs to just go walking on a normal road. For this reason I believe hiking trails should only be part of routes made with the new hiking profile.

**Comment by julianfairfax** [comment]
> @julianfairfax, some of the paths I've walked through have been much much worse than the marked hiking trails. I don't think there's enough data on OSM to distinguish what exactly is meant by "walking on a normal road". You might as well choose the car navigation in such case.

Well in the app it shows as a brown dotted line meaning hiking trail. So they know it's a trail and not a road. The problem with car navigation is that it might take me on roads that don't have pavements made for walking, which is also dangerous. I don't know if "walkable" is a datapoint for OSM roads or not but I feel like it is cause they have a lot of data.

**Comment by MisterY** [comment]
The dashed or dotted line simply means a path, not necessarily a hiking one. OSM can't tell you whether you are equipped to walk on one or not. Even with the hiking trails there are so many variables and one can't know simply by looking at the map what equipment is necessary to go through it (ropes or other gear, what kind of shoes, etc.). When you add the weather, it becomes practically impossible.
What concrete suggestions do you have to achieve this?

**Comment by julianfairfax** [comment]
> The dashed or dotted line simply means a path, not necessarily a hiking one. OSM can't tell you whether you are equipped to walk on one or not. Even with the hiking trails there are so many variables and one can't know simply by looking at the map what equipment is necessary to go through it (ropes or other gear, what kind of shoes, etc.). When you add the weather, it becomes practically impossible. What concrete suggestions do you have to achieve this?

Well in that case, those should only be included in the hiking profile, and roads, if there's a walkable flag then that's even better, should be included in the walking profile. But even if there isn't such a flag, the car and walking profile will still be different since motorways can be excluded very easily, and as such routes will be different. Better yet, the two fastest routes or more should be shown as options, and the user should be able to pick one or calculate the second one if they prefer that.

**Comment by R1123345** [comment]
Mapy.cz has a feature where it shows hiking trails in coloured lines, corresponding to the signs on tthe road. As far as i know, this is already part of the osm data, not unique to mapy.cz. Is it possible to display these trails with a "hiking view" option in a similar fashion?

**Comment by MisterY** [comment]
In addition to the colors (which I'm not sure where the source is, as I see blue, green, yellow, and red paths but don't see the obvious tags in the hiking path feature), there is also the symbol tag - `osmc:symbol`. This usually represents the markings along the path.

**Comment by julianfairfax** [comment]
OsmAnd has a "steepness" feature, which lets you choose whether you want normal roads that aren't too steep, completely flat routes, or completely steep routes. So looking at the elevation difference for the bigging on the end of a user's time on a certain road as a part of a route could be used to determine how steep that road is and choose to avoid it or not.

**Comment by pastk** [comment]
> Mapy.cz has a feature where it shows hiking trails in coloured lines, corresponding to the signs on tthe road. As far as i know, this is already part of the osm data, not unique to mapy.cz. Is it possible to display these trails with a "hiking view" option in a similar fashion?
> 

Yeap, this info is usually embedded in a route=hiking relations. Usually only more prominent trails (e.g. of national/regional networks) are waymarked like that. It'll be good to support it in OM, I mentioned it in https://github.com/organicmaps/organicmaps/issues/1577#issuecomment-980177481

**Comment by pastk** [comment]
> OsmAnd has a "steepness" feature, which lets you choose whether you want normal roads that aren't too steep, completely flat routes, or completely steep routes. So looking at the elevation difference for the bigging on the end of a user's time on a certain road as a part of a route could be used to determine how steep that road is and choose to avoid it or not.

OM shows an elevation profile when the route is being built so one can have an idea of trail steepness from there. This graph could use some improvement though.

**Comment by pastk** [comment]
Here is an experimental OM build with an outdoors map style 
(there is no UI yet to switch styles).

Download for Android (F-Droid flavor):
https://drive.google.com/file/d/1WoHHSsRTyuhBXyy5nmFGcYRVwVbuC3fp/view?usp=sharing

Its a quick take on an outdoors style, it needs much more work and polishing.

It features bigger/thicker and/or visible at lower zoom levels
- paths/tracks, cliffs
- contour lines
- railways, powerlines and towers
- water sources, peaks, saddles, passes
- waterfalls, lighthouses, caves
- campsites, huts, shelters, picnic sites
- gates, stiles, fords
- etc.

Sample screenshots are in https://github.com/organicmaps/organicmaps/pull/2804
Patches and suggestions are welcome there too!

This build simplifies using/testing custom map styles by allowing to raise
features' visibility without regeneration of maps (up to 3 zoom levels change)
at the expense of somewhat worse performance (and, consequently, battery life) -
feedback is much appreciated, especially from users with low-end devices!
(the visibility override patch: https://github.com/organicmaps/organicmaps/pull/2798)

To test your own custom map style please put a compiled style file
(e.g. `drules_proto_clear.bin`) next to map files, e.g. `Android/data/app.organicmaps.debug/files/styles/`
(in Android 11+ its inaccessible without root).
Custom styles instructions: https://github.com/organicmaps/organicmaps/blob/master/docs/STYLES.md

**Comment by Misalf-git** [comment]
> feedback is much appreciated, especially from users with low-end devices!

**Samsung Galaxy S4**
I didn't test any features this build provides as I don't have the resources to create map styles. FWIW, I just took a look at the map, especially the woods.
The rendering is really slow and the phone gets quite hot. ;)

**Comment by pastk** [comment]
> > feedback is much appreciated, especially from users with low-end devices!
> 
> **Samsung Galaxy S4** I didn't test any features this build provides as I don't have the resources to create map styles. FWIW, I just took a look at the map, especially the woods. The rendering is really slow and the phone gets quite hot. ;)

Thanks for your feedback, it's valuable!

Does the "regular" release OM version work significantly faster in the same area?
Were your maps on SD card or in the internal storage?
(when comparing this build and a release OM version please make sure both have maps in the same storage so that the storage speed doesn't affect results).

**Comment by Misalf-git** [comment]
> Does the "regular" release OM version work significantly faster in the same area?
Yes.
> Were your maps on SD card or in the internal storage?
They were on SD card. I moved them to internal storage, like I have it for the release version, and checked again.
No noticible change.

**Comment by pastk** [comment]
> > Were your maps on SD card or in the internal storage?
> 
> They were on SD card. I moved them to internal storage, like I have it for the release version, and checked again. No noticible change.

Sorry, do you mean there is no noticeable change between SD/internal maps location or there is no uchange between the release and the "outdoors" version after moving the maps to internal?

I've tested the "outdoors" build on an Asus ZB501KL which has a ~20-30% slower spec (according to synthechic benchmarks) compared to the Galaxy S4.
The speed difference is apparent, especially in the cities, but far from the point when the app becomes a pain to use.

When the outdoor style is ready and is included into the OM release there will be no speed penalty, because the maps data will be pre-optimized for both regular and outdoor maps styles. The current "outdoors" build is for testing purposes and for enthusiasts wishing to explore custom map styles making.

**Comment by Misalf-git** [comment]
> Sorry, do you mean there is no noticeable change between SD/internal maps location or there is no uchange between the release and the \"outdoors\" version after moving the maps to internal?

I didn't notice any change in rendering speed after changing the maps location from SD card to internal storage.

**Comment by janusbenissa** [comment]
New outdoor style looks good, except the "intermittent" streams in a forest or scrup land cover.
They are barely visible and can be bigger/thicker and/or visible at lower zoom levels.

**Comment by Misalf-git** [comment]
I just tried `2023.04.08-1-Google-beta` posted on https://t.me/OrganicMapsApp.

Galaxy A20e
Android 12

`highway=track` is very prominent, too bold I'd say. It draws attention away from (or decreases readability of) certain icons/captions like `amenity=shelter`, `tourism=information`, `natural=peak` etc.
Maybe the same thickness as `highway=path` (or thinner) would be better?
Or both thinner and and same?

Railways being more visible seems to greatly help orienting at a glimpse on z10-z12 while not being too prominent. I think they are just darker until z13? This might even be suitable for the default style.
This differentiability (however implemented) is pretty much the result I might expect for outdoor features.

I haven't yet noticed drastic (or any) decrease in performance. I broke that Galaxy S4 were I installed the debug test build back then, but might be able to install on another old/slow device.

**Comment by alensiljak** [comment]
![Screenshot_20230410-105117_Organic Maps (Beta)](https://user-images.githubusercontent.com/462445/230868337-f2fa5ec3-619d-480e-8713-73b3c5725c76.png)

The first impressions: 
- seeing the names of massifs and/or mountain ranges would be great at higher levels 
- there might be a great difference between marked trails and ordinary, unmaintained, paths. Showing the paths in color (from a tag) would be ideal. Will probably create a separate issue for this feature, though, as it is not critical for the hiking mode. 
- there's too many paths on higher levels, as shown on the screenshot. If there were less path in the visible area, the priorities would be different, of course.

**Comment by abdullahO2** [comment]
@pastk 
Thank you for this style. As for me, I live in a country that is mostly desert areas. And we are interested in natural places such as mountains, wetlands, waterways and other natural places. We are also interested in the names of places (villages and hamlets) and we are interested in the names of uninhabited places. All these places help us to know our location It is correct in the desert and ensures that we do not get lost in it, and we also care about water sources such as wells and places of water supply.
These tags are suggested to be displayed from higher levels and the labels of these places are displayed on them:

**[natural places]**
natural=scrub
natural=grassland
natural=wetland
natural=water
waterway=river
waterway=stream
waterway=dam
natural=cave_entrance
natural=cliff
natural=dune
natura=peak
natural=rock
natural=sinkhole
natural=valley
natural=bare_rock
natural=saddle
mountain_pass=yes
geological=volcanic_caldera_rim

**[places]**
place=village
place=hamlet
place=farm
place=locality
place=isolated_dwelling

**[water sources]**
amenity=drinking_water
amenity=water_point
man_made=water_well

**[others]**
man_made=cairn [Important and used as guiding signs in the desert]
man_made=communications_tower
man_made=mast
man_made=tower
historic=castle

**Some ways like:**
highway=track
railway=rail
man_made=embankment
boundary=protected_area

These are the most prominent tags that I think are suitable for outdoors/hiking in my opinion, and may not be suitable for every person/country.

And we are also interested in displaying the name on all these features (in the desert, we put a name on everything, even trees, because they are signs that guide us when we are lost), so it is important to display [name=*]

Finally, thanks again for your interest and for your completely free and open-source app.

**Comment by pastk** [comment]
[abdullahO2](https://github.com/abdullahO2) thanks a lot for a very detailed feedback!
Your suggestions and a list of features to add will help us!

As you rightly noted, raising visibility of many features is tricky because it'll make the map cluttered / too dense in many densely mapped areas. And adding a separate Desert style is a long shot for now, because we have Outdoors, Cycling, Driving styles in the queue already :)
But the good news are we have some ideas how to make one style work both for dense and sparse areas - its in discussion stage now. Another thing is that we're planning to make creation of custom styles easier.

**Comment by abdullahO2** [comment]
@pastk You're welcome! Glad the feedback was helpful. Balancing visibility and clutter is tricky, interested to see your solutions. Custom styles and additional map types sound great, looking forward to those updates.

**Comment by RicoElectrico** [comment]
In my opinion the dashed lines at low zoom make the map too crowded.
![image](https://github.com/organicmaps/organicmaps/assets/1409116/cd92a133-d3d9-4919-8563-a7a6d52dfe0f)

**Comment by pastk** [comment]
yeap, that's right, they look terrible in the cities and densely mapped areas, the style is for wilder areas :)

there are some ideas how to improve these cases though (dynamic density based styling and/or filtering short lines)

**Comment by pastk** [comment]
The Outdoors style has been added in the last (Dec '23) release so I'm closing this issue.

There a lot of great ideas for improvement and issues to solve described here still, so we'll refer back here for sure. But its better to create separate issues for Outdoors-related things from now on instead of piling everything here.
