### ISSUE TITLE
Increase search radius

### ISSUE THREAD

**Issue by julianfairfax** [organicmaps/organicmaps#2401]
It seems to search in Organic Maps, either you or the part of the map you're viewing have to be near what you're searching for. For example, if I'm in Switzerland and want to search for something in the Netherlands, I have to move the map over to the Netherlands, otherwise I only get results for Switzerland. It would be nice if these a button to increase the search radius, instead of having to do this.

**Comment by biodranik** [comment]
How can you imagine the implementation of such a search with an increased radius? All downloaded maps "in the radius" should be scanned for some string in that case. That will take minutes on some devices, especially on Androids with slow SD cards. OM does not use online servers like Google and can rely only on scanning local files.

The search was deliberately limited to the viewport if you don't specify a town/city or country name. If you want to search in the Netherlands, then you need to give the search a hint, otherwise, it's hard to guess where are you trying to search.

**Comment by julianfairfax** [comment]
I did specify a town name. And I think I also tried specifying the Netherlands. But for me, it still didn't search for it as it was outside the viewport.

**Comment by biodranik** [comment]
Then it could be a bug. Did you download the region where you tried to search? Did the search work if you was looking at the object you were searching for?

Can you please reproduce the bug and tell us what was your search query (or send it by email if it's private)?

**Comment by julianfairfax** [comment]
Yes I did download the region and yes the search did work if I was looking at the object.

I did reproduce it but I can't send the query. Adding the country doesn't help but adding the state did, so I got it to work. This issue also doesn't seem to happen for everything, or at least not with the other address I tried. It seems it might just need more details every now and then.

**Comment by biodranik** [comment]
That's why it's important to have a query to reproduce the issue. Please let us know when you reproduce it with some other query you can share.
