### ISSUE TITLE
Request for an issue reporting template

### ISSUE THREAD

**Issue by Asteliks** [organicmaps/organicmaps#2459]
I would like to request an issue reporting template for this repository, so that we can have standardized bug and feature requests. I you want I can create something based on these:
* https://github.com/openstreetmap-polska/ua-2022-map/issues/new/choose
* https://github.com/nextcloud/desktop/issues/new/choose
* https://github.com/openstreetmap/iD/issues/new/choose
* https://github.com/firefly-iii/firefly-iii/issues/new/choose

**Comment by biodranik** [comment]
Firefly have more rich templates ) We may try them. Please check our existing issues and think how it can be improved.

**Comment by Jean-BaptisteC** [comment]
Fixed by #4386

**Comment by pastk** [comment]
[Jean-BaptisteC](https://github.com/Jean-BaptisteC) many thanks for keeping the issues in order!

**Comment by Jean-BaptisteC** [comment]
I try to keep organize issues but it's not easy.
Because we have a lot of issues, somes duplicates, somes are partially fixed, somes are stuck because we have 0 answer.
I try to know a most of issues and PR, to know which labels use, if new issues is duplicate or is not an issue and if bugs are fixed in next version.
