### ISSUE TITLE
Label jumps for amenity=recycle

### ISSUE THREAD

**Issue by strump** [organicmaps/organicmaps#2573]
Version: Android 2022.04.27-2-Google

**Steps to reproduce:**
1. Zoom to some way with `amenity=recycling`. E.g. https://osm.org/way/67028056
2. Zoom in and out

**Actual result:**
Label jumps while icon is not moving

https://user-images.githubusercontent.com/720808/168644249-b1e7d718-0a7b-45ec-887a-c67b1a223740.mp4

**Expected result:**
Label should not move

**Comment by vng** [comment]
@strump Glad you are back! I was worry about you and wrote you on E-Mail maybe 2 months ago.

**Comment by strump** [comment]
@vng thanks for your worry. I'm totally safe in Ukraine. Can't invest much time in OM for now :(

**Comment by vng** [comment]
Optimal solution here is to add offset_y into text draw rule in engine, if we have symbol and text (without offset) drawing rules.
Happens here because:
- recycling has text (with offset) from z19, symbol from z16.
- building has text (without offset) from z16

Or set "offset_y" for building text rules always in mapcss.

**Comment by vng** [comment]
Same issue with beaches. See screenshots [here](https://github.com/organicmaps/organicmaps/issues/2388)
