### ISSUE TITLE
I drew a new fountain icon

### ISSUE THREAD

**Issue by AlexValue** [organicmaps/organicmaps#2908]
Simplified the icon and added a stroke for better visibility.
In the night theme, the stroke is black and the color is overlaid with white by 40% according to material design

Демонстрация (вверху новая иконка, внизу старая)

![msg1036150146-12458](https://user-images.githubusercontent.com/107300467/177042075-6f2750a1-d854-4a2f-982e-d1d009cfcf4c.jpg)

SVG files:
[fountain.zip](https://github.com/organicmaps/organicmaps/files/9034865/fountain.zip)

**Comment by pastk** [comment]
If we accept this addition of contrast outline we should decide for which icon types to use it and update those icons to have a consistent style https://github.com/organicmaps/organicmaps/issues/2205

**Comment by pastk** [comment]
I tested it in the app and it doesn't look good, needs adjustment

![fountains](https://user-images.githubusercontent.com/18434508/177373688-7f439eee-64aa-4f8c-ba8b-cb3095ca3d54.png)

**Comment by pastk** [comment]
Its better now, but the outline has gone, so no difference to the current icon except the shape.

![fountain2](https://user-images.githubusercontent.com/18434508/177508124-1e7d2330-8719-4cd6-a676-a8f3634ad0a0.png)

Please set up your own environment to do the testing, screenshots, etc.
Its a very inefficient use of time otherwise :)

**Comment by biodranik** [comment]
It would be great to see new icons on some day and night mode screenshots first, surrounded by other icons.
