### ISSUE TITLE
Routing options not centered

### ISSUE THREAD

**Issue by TheAdventurer64** [organicmaps/organicmaps#3041]
Currently, the list of routing options is not centered in the middle.
![image](https://user-images.githubusercontent.com/50059322/181466667-75c73e2a-8f28-4868-9706-1e48334993da.jpeg)

**Comment by strump** [comment]
Do you see it on iOS or Android?

**Comment by TheAdventurer64** [comment]
> Do you see it on iOS or Android?

iOS

**Comment by chereskata** [comment]
Hello,

i found, that the icons themselves are indeed centered and it is just an optical illusion, or it has been indeed fixed, because going from the centered nodge of the simulator, both outer icons go exactly 11px wider than the nodge.

![1](https://user-images.githubusercontent.com/87526889/195336262-2c523092-b0d2-494c-bca6-3f2aa3c1b8ef.png)
![3](https://user-images.githubusercontent.com/87526889/195336302-ea99d8f9-8ab8-4dbe-acea-b1550d3c395c.png)
![4](https://user-images.githubusercontent.com/87526889/195336312-f6fa33ba-da6b-4535-8cc2-764f27b52eb3.png)

**Comment by biodranik** [comment]
Yes, it was recently fixed.
