### ISSUE TITLE
bring back the full Wikipedia articles

### ISSUE THREAD

**Issue by TimMagee** [organicmaps/organicmaps#3052]
One of my favorite features of Organic Maps was the integration of Wikipedia articles, offline, in a readable fast format. 
Now, Organic Maps just shows the intro to each wikipedia article with a button to click through and open a web browser, download wikipedia's mobile viewer, download the page, and read the article in Wikipedia's inferior default format.

**Comment by jpds** [comment]
There's some discussion and figures about how this negatively impacted the map data file sizes on #2410.

**Comment by biodranik** [comment]
@vng did we apply #2410 for wiki? I think not.

**Comment by vng** [comment]
It's not working or I wasn't able to test this patch because of errors downloading wiki on server side ..

**Comment by vng** [comment]
@TimMagee I didn't get your point. We do store full article, without unnecessary sections like:
```
        "External links",
        "Sources",
        "See also",
        "Bibliography",
        "Further reading",
        "References"
```

Could you please provide an example article, that is not fully offline in OM?

**Comment by TimMagee** [comment]
Here is one: Falwell Airport.  om://0mjdN0jVS_/Falwell_Airport or this link https://omaps.app/0mjdN0jVS_/Falwell_Airport to see the place on the map.

Jul 30, 2022 14:18:43 Viktor Govako ***@***.***>:

**Comment by vng** [comment]
We do save full articles, but:
- the last valid wiki dump we have is from March 2022 (or even earlier). All subsequent attempts to download wiki pages was failed, probably due to the crawling protection on wiki server side ..
- https://en.wikipedia.org/wiki/Falwell_Airport page become alive in the end of April 2022
- https://www.openstreetmap.org/way/501754672 has reference on https://www.wikidata.org/entity/Q5432839, not a wiki page

**Comment by TimMagee** [comment]
Closing this issue as it seems I was confused.
