### ISSUE TITLE
[android] Ability to disable rotation snap.

### ISSUE THREAD

**Issue by CortexReaver** [organicmaps/organicmaps#3065]
When you trying to rotate the map with your fingers it sometimes snaps to fixed angle (according to "north" direction of your compass I believe) which is really annoying (because I rotate it a lot and need some roads to be straight to understand where I came from). This and also "smooth pan view" (or "pan acceleration", whatever its called) needs their own checkboxes.
I know this app has a ton of suggestions and bug reports, but I'm very happy with it as it is. Just some small quirks that need to be fixed. Not to mention it's very fast as well, compared to other navigation apps.

**Comment by biodranik** [comment]
We can try to remove it and see if someone complains.

**Comment by CortexReaver** [comment]
Why remove it completely? Make an option for disabling.

**Comment by thany** [comment]
I reported this issue in MAPS.ME a few years ago. It's not possible to rotate the map "a little bit", but my OCD sometimes needs a road to look vertical on the screen, not angled 3 degrees. But if you rotate the map less than a certain threshold, it snaps right back.

I know it's a nitpicky, but I can't help being triggered by this 🙂

**Comment by biodranik** [comment]
> Why remove it completely? Make an option for disabling.

Why make an option for disabling? It takes more time to develop and support.

**Comment by CortexReaver** [comment]
> Why make an option for disabling?
Customization is always good.

**Comment by biodranik** [comment]
Customization makes the interface clumsy, complex to support, and in many cases means that the UX is bad and should be tuned by customization instead of doing it right. There are not so many exceptions for useful customization.

**Comment by biodranik** [comment]
If all people are ok to disable it, why bother with an option?

**Comment by Markus40** [comment]
I would prefer the current functionality or an option menu.

As I said in #2219 it is too easy to rotate the map a little bit and having to touch the compass button to return to north. I have used an app that did it this way and it was pretty annoying.

If you really want a unified solution, I would be fine with it snapping back if you have already started the rotation from north, but not snapping if it was not north when you started the rotation.

**Comment by thany** [comment]
@Markus40 

> I have used an app that did it this way (although it was easier to accidentally rotate the map) and it was pretty annoying.

Subjective. But I'm guessing you mean Google Maps?

> Is there even a use case where the user wants to rotate the maps only a few degrees from north?

I need things to look neat and straight. I's a condition, I know, but to me it isn't something to brush off. Humans are not perfect, and saying it's annoying to have a feature that deals with that, feels dimuitive.

As an analogy, imagine an app that doesn't have dark mode, simply because a developer doesn't like it. But then imagine someone suffering from light sensitivity (temporary or permanently, doesn't matter for now). They couldn't give two tosses about what a developer thinks looks nice, because they actually _need_ dark mode, even if it looks ugly.

> If you really want a unified solution, I would be fine with it snapping back if you have already started the rotation from north, but not snapping if it was not north when you started the rotation.

I would rather it snaps to straight-looking paths, rather than north 🙂 When you're out and about, is it really that useful for north to be pointing up? I mean, is your direction to the magnetic north pole really so important that it should snap to that, rather than literally anything else?

When I'm looking down a road, I don't care whether it leads perfectly northbound, or anywhere else. And no, even in this case, following the compass still has disadvantages:

* Battery usage
* No one always walks perfectly straight
* No one keep their phone pointing forward, perfectly straight
* And then when the map rotates just because I look around, it's confusing, especially at an intersection.

Besides, when navigation by car or bicycle, you wouldn't follow the compass anyway. You would rotate the map to match the road that you're on. That's why navigation in Google Maps works perfectly even when the phone is upside down, or the compass is broken.

**Comment by RicoElectrico** [comment]
What about reducing the snap angle to some lower value? Current value of 25° clockwise AND counter-clockwise is ridiculous to me :)
On top of that, there is already some hysteresis in rotation gestures regardless of current map orientation.
I shall do experiments and provide sensible values in a pull request.

**Comment by thany** [comment]
I say both. Reduce snapping angle and an option to enable it.

Customisation is good. Don't try to make a UI that will fit everyone - you *will* fail. There's no such thing as an average or perfect user.

**Comment by biodranik** [comment]
@thany the approach to make UI and UX that fits fit _as many users as possible_ actually works for more than a decade for Organic Maps, starting from MapsWithMe. Otherwise, you get another OSMand.
The most complex task is to choose the best _default_ value.

**Comment by thany** [comment]
> @thany the approach to make UI and UX that fits fit _as many users as possible_ actually works for more than a decade for Organic Maps, starting from MapsWithMe. Otherwise, you get another OSMand. The most complex task is to choose the best _default_ value.

Please don't twist this request into "make everything customisable". Some customisations make sense, others certainly don't. The most complex task is to choose where the balance lies between too many and too few options.

If you _really_ don't want an option for this, at least I would like it to snap not to an arbitrary angle, but to a road. Perhaps the biggest or most prominent road that happens to be on screen. The world's roads don't snap to neat 5-degree increments of angles, so why should a map?
