### ISSUE TITLE
Advanced edit of opening_hours disappers as soon as I start typing

### ISSUE THREAD

**Issue by mnalis** [organicmaps/organicmaps#3077]
Even on simple opening_hours (non overlapping, only two ranges) when I click on `EDIT BUSINESS HOURS` and `ADVANCED MODE`  I get shown `opening_hours` raw tag value which is great. I can click on it and move cursor without problems. However, as soon as I try to type **any** number or letter anywhere in it, **input field disappears**. 

Interestingly, it seems I can type `,` and `;` without input field disappearing (but that is obviously not very useful on its own, as any alphanumeric I try to type after that cases the disappearance again)

Example video:

https://user-images.githubusercontent.com/156656/182380607-80694a75-5557-4d53-bf0c-b1edcd642f96.mp4

I've searched issues and found possibly somewhat related this one https://github.com/organicmaps/organicmaps/issues/1366 (and others linked in it), but this still looks as a different problem. 

Android 10, OrganicMaps 2022.07.27-3-FDROID

**Comment by arnaudvergnet** [comment]
IMO the underlying issue is the same as in https://github.com/organicmaps/organicmaps/issues/1247 and https://github.com/organicmaps/organicmaps/issues/1366. The edit page becomes blank as soon as the value is considered invalid. In your case the input becomes invalid when you start typing.

Try editing the opening hours in advanced mode again and delete `-Sa` from `Mo-Sa`. The page will be blank when you start removing the characters, but as soon as you remove all characters and `Mo-Sa` becomes `Mo`, the UI will reappear because the open hours format is now valid.

**Comment by mnalis** [comment]
Yes, I can confirm that behaviour as you suggest @arnaudvergnet !

**Comment by BelKed** [comment]
This issue has been resolved in https://github.com/organicmaps/organicmaps/pull/3159.
Is there anything preventing this issue from being closed?
