### ISSUE TITLE
[editor] Duplicating postcode and levels fields in UI.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#3404]
https://www.openstreetmap.org/way/163629174

iOS (Android?) Edit this place. Got:
![photo_2022-09-13 23 12 40](https://user-images.githubusercontent.com/175612/190000098-c50b78a4-5345-4c3a-a655-4f93a1ded3a2.jpeg)

**Comment by endim8** [comment]
can confirm not an issue on android 👍

**Comment by biodranik** [comment]
@dvdmrtnz can you please take a look? It can be related to your level changes.

**Comment by dvdmrtnz** [comment]
I don't think it's actually related to my level changes, because the tag that is duplicating is `building:levels`, not `level`.

Anyway, I think I found where this duplication is coming from. The tags `postcode` and `building:levels` are getting added manually in https://github.com/organicmaps/organicmaps/blob/master/editor/editor_config.cpp#L139. I did some tests removing these two lines of code and the problem seems to be fixed.

I can make a PR with the changes if you want.

**Comment by vng** [comment]
@dvdmrtnz You are right, but I have doubts now that this change will not break the Android.
Thanks for your investigation, I will make a deeper look here ..

**Comment by Jean-BaptisteC** [comment]
@biodranik #4521 fix postcode and level duplicates ?

**Comment by biodranik** [comment]
@Jean-BaptisteC thanks! You're right, it was already fixed.
