### ISSUE TITLE
Faulty navigation on some interchanges on Autobahn

### ISSUE THREAD

**Issue by thosoo** [organicmaps/organicmaps#3502]
In some situations organicmaps routes me onto the out lane of an interchange just to go straight and get back onto the Autobahn again. I have observed this behavior multiple times on some interchanges, but not all of them.
This is especially confusing and problematic in crowded situations.

I am using version 2022.09.22-3-Huawei.

![Screenshot_20220924_094432_app organicmaps](https://user-images.githubusercontent.com/8445255/192781384-8b2969b7-dd15-46ea-a676-44c8d92bb2e3.jpg)

**Comment by strump** [comment]
Thanks for the issue.

As far as I can see, when OrganicMaps build route from [49.5260, 8.6357](https://www.openstreetmap.org/?mlat=49.5260&mlon=8.6357) to [49.58899, 8.63303](https://www.openstreetmap.org/?mlat=49.58899&mlon=8.63303) it tells to use this [motorway_link](https://osm.org/way/194829626) road instead of this [motorway](https://osm.org/way/143598251).

Maybe it's because [motorway](https://osm.org/way/143598251) has `surface=concrete` tag in OSM.

**Comment by biodranik** [comment]
See also #3033
