### ISSUE TITLE
Stop navigation button  partly visible when info panel pulled down

### ISSUE THREAD

**Issue by j13m126** [organicmaps/organicmaps#3740]
Seen on a Samsung Galaxy Tab s6 lite running android 12 with om version 2022.09.22-3-FDroid and also 2022.10.25-2-Google-beta.
Landscape mode is fine.

https://user-images.githubusercontent.com/7961926/198145373-29f6597b-9141-4896-8746-c2eb49070b34.mp4

**Comment by biodranik** [comment]
@arnaudvergnet do you have any ideas on how to make it look better?

**Comment by arnaudvergnet** [comment]
I thought the bottom sheet would stick to the left when the screen was too large but it turns out this is only the case in landscape.

The current logic tells the view supposed to hide the bottom sheet under the navigation bar to stick to the left when the screen is too large. A fix would be to make it stick to the left only in landscape.
