### ISSUE TITLE
Add truck stop OSM type

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3767]
Also into the editor

**Comment by dvdmrtnz** [comment]
What is the OSM tag?

**Comment by patepelo** [comment]
> What is the OSM tag?

Since [amenity=truck_stop](https://wiki.openstreetmap.org/wiki/Key%3Aamenity%3Atruck_stop) is not well documented nor de-facto (only 71 elements), it would fall under the umbrella: [highway=services](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservices). I've been thinking about redoing the rest area icon into something like these with white outline: 
![image](https://github.com/organicmaps/organicmaps/assets/23003127/1ccc5467-26ce-4af6-8022-cf1aefd35c1e)


Currently is only a picnic table.

**Comment by pastk** [comment]
highway=services is supported, amenity=truck_stop is not used
