### ISSUE TITLE
Name POI is cropped when you update maps

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#3851]
How reproduce:
(You need to use old maps)
- Search POI on downloaded maps
- Start maps download  where you have find POI
- Select your POI on map
- On bottomsheet, loader is show before name of POI, if name is to big, name is cropped

Example:
- https://www.openstreetmap.org/node/639590028

With loader
<img src="https://user-images.githubusercontent.com/87148630/200933832-6d9649da-4ff9-4951-9d01-3fed02294ca1.png" height="500"/>
Without loader
<img src="https://user-images.githubusercontent.com/87148630/200933987-4d7c5648-3bd7-4e4e-9b19-780f58b14be0.png" height="500"/>

**Comment by biodranik** [comment]
You probably can also reproduce it by selecting a long city name on the empty world map.

**Comment by Mr-Mime** [comment]
> You probably can also reproduce it by selecting a long city name on the empty world map.

I was not able to reproduce this on the world map.
I checked it on some airports and states, see screenshots below.

However it might be different on the map update.
Because right now it renders the "download" button in front nad maybe handles the line wrap correctly therefore.

In the screenshots above you see that the PP is created "normally" and then gets the "downloading" spinner in front, whicht might simply shifts the text to the right, which then moves behind the box of the "direction" arrow (the blue one)

| Without loading | With loading | With location enabled | 
| --- | --- | --- |
| ![signal-2022-11-10-135006_005](https://user-images.githubusercontent.com/37423773/201096461-235a2d69-603f-4b43-9845-4f86b4ac4e2f.png) | ![signal-2022-11-10-135006_004](https://user-images.githubusercontent.com/37423773/201096471-accfc9ec-07a2-48ea-96f1-ec1db8eb71d1.png) | ![signal-2022-11-10-135006_002](https://user-images.githubusercontent.com/37423773/201096490-5c0d69c6-19cf-49ec-9c04-9224c1397a93.png) |
| ![signal-2022-11-10-135006_007](https://user-images.githubusercontent.com/37423773/201096259-6b42bdb5-e2c8-4d95-a096-66a7aeee90cf.png) | ![signal-2022-11-10-135006_006](https://user-images.githubusercontent.com/37423773/201096277-f4cc2a17-3139-4e2e-ac1f-606f0d78c2d1.png) |

**Comment by Jean-BaptisteC** [comment]
Probem doesn't appear on my Pixel 6 - Android 13
v2023.01.25-3-Google
