### ISSUE TITLE
[android] Location is not detected if enabled in the system settings after OM is opened

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#3899]
> There seems to be a problem with getting a location signal on android 13 (pixel 6).
   I don't get a location signal when I enable location services after starting om.
>   Steps to reproduce:
>   - make sure OM is not running in the background
>   - location services disabled
>   - start OM
>   - enable location services
>   - om fails to get location after several seconds
>   - close and reopen OM and there's a GPS signal immediately.

**Comment by biodranik** [comment]
@rtsisyk is it also fixed in your PR?

**Comment by biodranik** [comment]
@rtsisyk does your recently merged location PR fix it?

@Jean-BaptisteC can you please check it?

**Comment by Jean-BaptisteC** [comment]
Yes problem is fixed,
- If you skip pop-up -> OM stop to search location
- If you enable location and touch button to search location -> OM find location

Other problem fixed with Google Play Services
In previous version, when i allow Play Services to locate me, i need to restart app for OM find location

**Comment by biodranik** [comment]
Fixed by #3944
