### ISSUE TITLE
Remove circle from dog_park icon

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#4002]
Let's follow the pattern "circles are used only for businesses".

The icon can also be improved, this one is used in osm-carto:

![image](https://user-images.githubusercontent.com/170263/204820278-23d22a3d-f577-422b-bd74-0546c6293a3c.png)

**Comment by not-available-username** [comment]
@biodranik feel free to use the one you prefer, I used the one from osm-carto since is CC0

![dog_park-m_2](https://user-images.githubusercontent.com/92886370/205377569-9d905613-d2e3-4ef7-b63d-3650d9d2004c.svg)
![dog_park-m_1](https://user-images.githubusercontent.com/92886370/205377572-07ba5b31-6e69-4ca5-9cc5-cd22da1d4d2f.svg)
