### ISSUE TITLE
Route calculation algorhytm ignores pedestrian crossing in pedestrian navigation mode

### ISSUE THREAD

**Issue by d4f5409d** [organicmaps/organicmaps#4007]
See the images via Matrix (confidential).
I'll link on Matrix this issue's number.

**Comment by Jean-BaptisteC** [comment]
Can you add start and end position route in osm.org

**Comment by d4f5409d** [comment]
> Can you add start and end position route in osm.org

No, because it's my neighbourhood, and I don't want to share it with anyone. Except Alexander, (the dev), because I trust him.

**Comment by Jean-BaptisteC** [comment]
<img src="https://user-images.githubusercontent.com/87148630/205376548-f19de2d9-31b6-42f7-9622-013a7b6b2e04.png" height="500" />

I'm able to reproduce
Start point https://www.openstreetmap.org/way/1094612292
End point https://www.openstreetmap.org/way/103134860

OM doesn't follow this pedestrian crossing https://www.openstreetmap.org/way/929836181

Maybe in my case OM doesn't use pedestrian crossing because he don't find sidewalk.

OM support sidewalk key on road ?

**Comment by biodranik** [comment]
@vng do we support pedestrian crossings?

**Comment by vng** [comment]
Crossings don't need any additional support.
Key fix here is to add additional penalty when transiting from/to _non-pedestrian_ road. So the algo will prefer transiting on footways ..

**Comment by d4f5409d** [comment]
> Thanks @vng  Ok for me
> @d4f5409d is it ok for you ?

Idk what the hell you're talking about, but probably yes.

**Comment by Jean-BaptisteC** [comment]
If explanation give by vng for my example answer to your issue
