### ISSUE TITLE
[Android] Bookmark import 

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#407]

**Comment by ioctl-user** [comment]
Please add bundle import/export feature for multiple files at once.

In recent versions bookmarks can be directly reached only with adb root access, making multiple files import/export impossible for the most users.

This feature can be very useful for manual backup and bookmarks sharing between users.

To minimize interface changes, multiple import can use standard Android files multiselect. And additional button can allow exporting of all visible bookmarks.

**Comment by ioctl-user** [comment]
Was this request implemented or rejected?

**Comment by rtsisyk** [comment]
Implemented. Try the latest beta https://appdistribution.firebase.google.com/pub/i/4fa64e2439ca20ff

**Comment by ioctl-user** [comment]
I installed the lasted version from F-Droid: 21.06.07-... There is multiple import of all files from the directory, but no multiple export. Could you clarify, now can I do it?

And even single export is not working: app stuck on export notification. It seems, because there is no filesystem access rights. And there is no bookmarks "share" possibility too.
