### ISSUE TITLE
Error message is hide in editor by next field

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#4343]
How reproduce:
- Start OM
- Select POI and open editor
- Update field name with forbidden characters --> red error message is hide
<img src="https://user-images.githubusercontent.com/87148630/214959821-5082cfeb-5b23-4f33-b519-08a5ea27fa77.png" height="500" />

Pixel 6 - Android 13
v2023.01.25-3-Google

https://github.com/organicmaps/organicmaps/blob/master/android/src/app/organicmaps/editor/MultilanguageAdapter.java

CC @biodranik

**Comment by biodranik** [comment]
@arnaudvergnet that should be very easy to fix, right?

**Comment by jaivsh** [comment]
Hi, can I do this one please?

**Comment by Jean-BaptisteC** [comment]
Yes, of course :), you can find more information about contributing here https://github.com/organicmaps/organicmaps/blob/master/docs/CONTRIBUTING.md

**Comment by prabs3257** [comment]
hello, can i please work on this issue ?

**Comment by biodranik** [comment]
Please don't ask a permission. Fix it instead.

**Comment by hiteshshimpi-55** [comment]
I would like to contribute , can you assign me with this issue ?

**Comment by biodranik** [comment]
Your requests look like spam. We do not assign newcomers to issues. If you want to fix something — do it without asking permission.

**Comment by satvik2131** [comment]
![Screenshot_20230209-005554](https://user-images.githubusercontent.com/59243339/217632202-f4f2224a-05a6-4d5d-a94a-0475b91f8fbd.jpg)

is this approach is ok?

**Comment by Jean-BaptisteC** [comment]
You can't keep error message below field and just update disposition to see error message correctly ?

**Comment by satvik2131** [comment]
> You can't keep error message below field and just update disposition to see error message correctly ?

Yes , I can do that, it's just this way also it was looking good so I thought to share with you , No issues , I will fix it with below field style.

**Comment by Jean-BaptisteC** [comment]
Your first look is very good, but if you add this on name field, we need to add this foreach fields
Our priority is to show an error message properly :)

What do you think @biodranik ?

**Comment by biodranik** [comment]
@satvik2131 I like your proposed approach because it doesn't change the layout of other elements. Using it, we don't need to fix jumping icons, because they won't jump anymore.

1. Does it require a lot of code changes?
2. Will it work on older Android 5 devices?
3. How longer error messages will look? (you can set a larger font in the device's settings to test it and check, for example, building levels).

If it is trivial to implement and works on Android 5+, then we can proceed with your solution with these points in mind:
1. Please make sure that you remove old unnecessary code and layouts.
2. Please fix all relevant fields where an error message could be displayed (including other dialogs and popups), so the UI will look and work consistently.
5. Please test it on older Android versions (emulators can be used).

Not directly related, but it would be also great to automatically scale some texts that do not fit on the screen if the font is set by a user to the largest one. @Jean-BaptisteC can you please check what texts do not fit properly in this scenario and create a separate issue for it, with some screenshots?

**Comment by satvik2131** [comment]
@biodranik Thanks for observing my approach  , I have tested  with your mentioned scenarios and 

1. No , it does not require lot of code changes , we were setting error in TextInputLayout , I have setted it to EditText

2. I have tested setting up my font size to the max and also tested with the paragraph of info(photos attached) and it is working as it is  .
![1](https://user-images.githubusercontent.com/59243339/217762547-ac33aadc-15b6-4640-b0f7-a5b22738d173.jpg)
![2](https://user-images.githubusercontent.com/59243339/217762562-7d4bac75-7489-4a79-9618-5c904a3a7b04.jpg)



 I have changed it to the editor where there is adapter with recycler view present , so it will be same for the whole editor page .

The only thing I wasn't able to test is the compatibility in old version
I got this error , when running the app with API 25
_"The currently selected variant "fdroidDebug" uses split APKs, but none of the 1 split apks are compatible with the current device with ABIs "x86""_
Device : Pixel 4 API 25 (Emulator)

**Comment by biodranik** [comment]
You need to build the APK for x86 to run it on x86 emulator. If you build apk manually, you can use `gradle installFdroidDebug -Px86` command. Or you can temporarily edit build.gradle and specify only x86 target ABI for your build.

And please use Android 5 API to test (API 21, not 25).

**Comment by satvik2131** [comment]
@biodranik , I have tried testing it with both the methods and getting this error <a href="https://pastebin.com/1ddkcsXV">Error Link</a> , I have tried to reinstall my python software and also reload the project. Can you please help me if you have any idea why is this occuring .

**Comment by satvik2131** [comment]
@biodranik , done testing with API 21 ,it's working fine there as well 
![Screenshot_20230210_125405](https://user-images.githubusercontent.com/59243339/217916692-4f10d4e9-5c4f-468c-bf52-fbbc5f4e4145.png)
should I push the code ?

**Comment by biodranik** [comment]
Yes, of course )
