### ISSUE TITLE
Long map names are cut in map search list

### ISSUE THREAD

**Issue by gpesquero** [organicmaps/organicmaps#4449]
In the result list of map search on the Android app, the names of the maps are not displayed completely if the map name is too long, as shown in the following figure for map name _"Cataluña - Provincia de Barcelona"_:

![search_list](https://user-images.githubusercontent.com/25888296/218280826-bc6b0a87-8126-4eda-a87b-8a0d1a16499b.png)

But in the downloaded map list, the name of the map is displayed correctly in two lines, as shown here:

![downloaded_map_list](https://user-images.githubusercontent.com/25888296/218280832-140597b1-d6d7-4378-9a8d-27dd04434682.png)

This happens in the current Beta version on Android (and probably on older versions). On iOS everything looks fine.

I've checked the Android code, and both lists (search and downloaded maps) use the same item layout `android/red/layout/downloader_item.xml`, so I don't understand why the maps names are displayed differently.

**Comment by gpesquero** [comment]
Reviewing the code in `DownloaderAdapter.java`, I've confirmed that the map name field is limited to 1 line in search mode. I've launched the [PR 4468](https://github.com/organicmaps/organicmaps/pull/4468) to allow at least 2 lines (as in downloaded map mode of the list).
The commit also allows multiple lines for the _subtilte_ (map city list).

**Comment by biodranik** [comment]
@gpesquero thanks!
1. How does it look now with your changes? Is the issue fixed? (you may test it on the emulator with a narrow screen, or increase the font size in your device's settings).
2. Do you think that 2 lines will always be enough? Would it be better to make an unlimited-length line instead?

**Comment by gpesquero** [comment]
I've made different tests, increasing the system font size and with different screen resolutions and everything looks fine in both search and downloaded map lists.

![multi-line2](https://user-images.githubusercontent.com/25888296/218572380-ad2e5770-afda-40cc-a4dd-4a02d60f5903.png)

I agree that we can remove the limitation of 2 lines. I've make some tests with a much longer map name and it still looks OK even with 4 lines:

![multi-line4](https://user-images.githubusercontent.com/25888296/218572414-79666a40-a554-4770-8671-2b1670957c18.png)

**Comment by adityarai004** [comment]
I am an android developer, chose to contribute here as numbers of issues are more here and i find the code and issues very understandable here.
I tried to set up the android code in my PC first it showed error bcoz of some secure.propeties that was solved with ./configure.sh
then after again an error shows up that was related to some sdk tool so solved it.
then i got some error in colors.xml and strings.xml they shows "..values-tr/colors.xml" got to know it is a issue due to symlink 
did the symlink many time even reinstalled git and CHECKED the BOX of symlink. constantly trying to find solution from last 6 hours found a solution but it is not solving my problem here the reference https://github.com/orgs/organicmaps/discussions/3095#discussioncomment-3436114

Now now I talked with some members they said to follow every instruction given in INSTALL.md then after literally deleted everything and restarted but no use.
Please Somebody do something about this issue feeling very demotivated rn. 
Expecting a solution asap

Windows 11 user
![image](https://user-images.githubusercontent.com/86659578/219101081-8e70247f-d117-421c-be9e-1bb2fbc55d5d.png)

**Comment by gpesquero** [comment]
Hello @adityarai004, I use Ubuntu/Linux for my Android development environment, so I don't have any experience getting a development environment working on Windows.
In any case, I'm going to try to build it on my Windows 10 system, to check if I can help you somehow...
