### ISSUE TITLE
Connection failure

### ISSUE THREAD

**Issue by stemy2** [organicmaps/organicmaps#450]
Hello,

I can't download any map because of a so-called "connection failure", even when connection actually works.

**Comment by biodranik** [comment]
@stemy2 Hi, can you please provide us more details? Your device, connection type, what do you do and see? Did you also try to use another connection/WiFi router?

**Comment by stemy2** [comment]
Samsung galaxy S7
It happens when the app ask me to download maps after first launch.
I tested the 4G and many actually working wifi networks, the app can connect on none of them.

**Comment by biodranik** [comment]
Wow, that's definitely a bug. Which version did you install and from where? Google Play? F-Droid? APK from github?

**Comment by stemy2** [comment]
From F-droid.
Is this map a fork from the Maps app, wich had forked from maps.me ? Because they have a similar bug.

**Comment by biodranik** [comment]
Yes, it's a fork of MAPS.ME. Which country are you from? Do you see _403 Forbidden_ error if you open [this page](https://cdn.organicmaps.app/maps/) from the browser?

**Comment by stemy2** [comment]
Yes.

**Comment by biodranik** [comment]
Very interesting. Can you please record and share `adb logcat` logs for us while you're trying to download any map in the app? We can try to find the bug by analyzing app logs.

**Comment by stemy2** [comment]
[My logcat](https://zerobin.stemy.me/?7768fd63c44e9875#CGrDT12ZJ2QAiUVr5kkP2yyGvhAJR9zKiBLtNYuXVZYi)

**Comment by biodranik** [comment]
Can you please try to download it once again?

**Comment by stemy2** [comment]
Still not working.

**Comment by biodranik** [comment]
Interesting, by some reason our server is not accessible for you (HTTP 403). Do you use any custom DNS provider/filter? What happens if you `curl -v http://cdn.organicmaps.app/maps/210503/WorldCoasts.mwm`, `curl -v https://cdn.organicmaps.app/maps/210503/WorldCoasts.mwm` and if you try to open these links in the browser on your mobile device?

**Comment by stemy2** [comment]
[Result 1](https://zerobin.stemy.me/?15da3a9b52962287#J5EQcYdzdXSvTCu9JjrmXsAXzQ8YfsCC892jeXoDc8tg)
[Result 2](https://zerobin.stemy.me/?bbaed06731fcd756#4iMts5htvmgVnWonTPoqGrZLEVBfAAMFMzTbgnb2yKFW)

**Comment by homlett** [comment]
Same issue here. Fdroid build too and 403 Forbidden error on https://cdn.organicapps.app (mobile broadband, regular ISP, Tor, etc.).

**Comment by biodranik** [comment]
403 on that url is perfectly valid.
If it doesn't work from the app, please share adb logcat.

**Comment by rustybird** [comment]
I have the same problem connecting through Orbot: That HTTP 403 error is Cloudflare serving a CAPTCHA to Organic Maps, instead of the https://cdn.organicmaps.app/maps/210529/WorldCoasts.mwm map file.

The CAPTCHAs can be disabled by lowering the [Cloudflare Security Level](https://support.cloudflare.com/hc/en-us/articles/200170056) for `cdn.organicmaps.app` to `Off` (Enterprise customers only) or `Essentially Off`, either in general or just for the [`T1` (Tor) pseudo-country](https://support.cloudflare.com/hc/en-us/articles/203306930).

**Comment by biodranik** [comment]
Wow, thanks for the hint! We're not on Enterprise plan, let's hope that Essentially off will fix that. @rustybird Can you please recheck again?

**Comment by rustybird** [comment]
Works great, thank you!
