### ISSUE TITLE
[android] `res/xml/locales_config.xml` is not updated automatically

### ISSUE THREAD

**Issue by rtsisyk** [organicmaps/organicmaps#4542]
**Unused Translation**
[../../AndroidManifest.xml](android/AndroidManifest.xml):67: The language et (Estonian) is present in this project, but not declared in the localeConfig resource

```
  64       android:dataExtractionRules="@xml/backup_content_v31"
  65       android:icon="@mipmap/ic_launcher"
  66       android:label="@string/app_name"
  67       android:localeConfig="@xml/locales_config"                                                    
  68       android:theme="@style/MwmTheme"
  69       android:supportsRtl="true"
  70       android:networkSecurityConfig="@xml/network_security_config"
```

If an application defines a translation for a language which is not included in the app's localeConfig file (when declared in the manifest), that language will be "unused"; it will not be presented to the user. Usually this means you have forgotten to include it in the locale config file.
More info: https://developer.android.com/about/versions/13/features/app-languages

This file should be auto-generated like `supportedLocalizations`.

See 73049543b6510ef3027d76493f7ceb87d8d6db00 and 339424be24f1b6e2ecdba8cce7ee28205ab46332

**Comment by Jean-BaptisteC** [comment]
I have not idea how to develop this in unix, but i know how script can be work
Script:
- Doing a `ls` here https://github.com/organicmaps/organicmaps/tree/master/android/res and use grep with this regex `values-([a-z]{2}(-r[A-Z]{2})?)` -> save result in var
- use Sed to remove r
- use Sed to get languages from here https://github.com/organicmaps/organicmaps/blob/master/android/res/xml/locales_config.xml with this regex "([a-z]{2}(-[A-Z]{2})?)" -> save result in other var
- Add if to check if variables is different
  - if condition matched
  - `cat <?xml version="1.0" encoding="utf-8"?> > locales_config.xml`
  - `cat <locale-config xmlns:android="http://schemas.android.com/apk/res/android"> > locales_config.xml`
  - `cat <locale android:name="en"/> > locales_config.xml` (because values-en doesn't exists)
  - Add foreach to generate others lines with results get from var
  - `cat </locale-config> > locales_config.xml`

@biodranik what do you think ?
