### ISSUE TITLE
Cycle routing avoids paths in parks

### ISSUE THREAD

**Issue by jpds** [organicmaps/organicmaps#4638]
**Describe the issue**

I initially observed this with asking for directions that would normally go through Victoria Park in London:

![signal-2023-02-27-152042_002](https://user-images.githubusercontent.com/29158971/221604232-fdb94fc3-e878-4a1a-9710-55d8c63ed490.jpeg)

There is however no cycle restriction on the OSM data: https://www.openstreetmap.org/way/8011428

I have also noticed that this odd decision happens at Finsbury Park too:

![signal-2023-02-27-152329_002](https://user-images.githubusercontent.com/29158971/221604959-f235453e-2b00-482a-87f5-5d1165c22d60.jpeg)

However, I would expect the route on https://www.openstreetmap.org/way/582718283 and on the road up north to be quicker.

**Comment by biodranik** [comment]
What routes are built by osrm and graphhopper in OSM?

**Comment by jpds** [comment]
Interestingly, Graphhopper turns in, but not through the entrance I would take - the park itself has a number of marked cycle routes:

![Screenshot from 2023-02-28 11-15-54](https://user-images.githubusercontent.com/29158971/221838411-7a4f94db-471b-4605-9078-2b40963292e8.png)

This is what I would expect for the second search:

![Screenshot from 2023-02-28 11-13-14](https://user-images.githubusercontent.com/29158971/221838460-e0fdda15-983d-4693-b7c4-72131d829449.png)

**Comment by vng** [comment]
GraphHopper and Valhalla make the same detour (https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=51.5404%2C-0.0447%3B51.5382%2C-0.0269#map=15/51.5411/-0.0345).

The problem here is that there are a bunch of barrier=gate entering and leaving this park (Victoria Park).
 These gates are marked as foot=yes only. They have some access:conditional (sunset-sunrise), but the routing engine can't say for sure that these gates are accessible for bicycles. So engine adds some penalty for each gate and make a detour is better according to this penalties.

**Comment by jpds** [comment]
This is resolved as of last month's map updates, thanks for the tip on the gates.
