### ISSUE TITLE
Search for hospital returns every doctor 

### ISSUE THREAD

**Issue by telluroid** [organicmaps/organicmaps#4746]
**Describe the issue**
When searching for hospitals every kind of doctor appears in the search results list in addition to hospitals.

**Steps to reproduce**
Seaching manually or using the categories menu

**Expected behavior**
Only hospitals show up in search results and on the map.

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.03.05-5-Google
 - Device Model: Pixel 4a

**Comment by matkoniecz** [comment]
Can confirm: searching "hospital" in English interface finds doctors.

**Comment by Kazing** [comment]
See categories.txt, amenity-doctors is in group `@hospital`, which contain hospital, clinic & doctors
https://github.com/organicmaps/organicmaps/blob/05934fabd14e480be3b2686629e87b82fcf7e848/data/categories.txt#L4663

If we don't want that search hospital returns doctors, amenity-doctors could be removed from group `@hospital`
* Searching doctors should show hospital (since you can consult a doctor in hospital)
* But probably searching hospital should not return doctor (a doctor's office is not equivalent to an hospital)

**Comment by pastk** [comment]
- duplicated / continued in #7776
