### ISSUE TITLE
Sanitary dump station rendered above marina icon

### ISSUE THREAD

**Issue by Mr-Mime** [organicmaps/organicmaps#4819]
**Describe the issue**
If a marina has the `sanitary_dump_station=yes` tag, the sanitary icon will be rendered above the marina icon.

**Steps to reproduce**
1. Visit this place https://www.openstreetmap.org/node/290287247#map=19/12.04641/-61.74778
2. In Omaps it is shown like this:

![image](https://user-images.githubusercontent.com/37423773/226211231-5811c3a9-b89d-45d3-8923-721fa57d03d3.png)

**Expected behavior**
It should have the same icon as "The Lagoon" on the bottom.

**System information:**
 - Operating system and its version: Android 11
 - Organic Maps version: 2023.03.05-5-FDroid
 - Device Model: OnePlus 7

**Additional context**
I guess it is just an issue with the priority set in the drawing rules.

**Comment by biodranik** [comment]
@vng should it be added as a "secondary" priority type?

**Comment by patepelo** [comment]
I was about to open the same issue and did some research on the current tagging scheme with the community via Discord. There is a difference that is not clear that indicates a POI is the main or host ammenity and has some ammenities/services inside.

![image](https://github.com/organicmaps/organicmaps/assets/23003127/99a21e4b-f4f0-4c7a-b88b-301c56e319f2)


There is a difference:

amenity=sanitary_dump_station is the host POI --> Icon should be sanitary dump station alone.

leisure=marina is the host POI and has:
sanitary_dump_station=yes

This is the approach that comes in the example of  Boat Rental wiki: --> https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dboat_rental

There are some amenities that don't have this tagging scheme and lead to software missinterpretation like this example:

![image](https://github.com/organicmaps/organicmaps/assets/23003127/3c6dff51-efd9-46f2-85b0-88d7c2d9a390)
https://www.openstreetmap.org/node/9858522817

amenity=swimming_pool
leisure=fitness_centre
wheelchair=yes

The community of OpenStreetMap should come with the alternative:

leisure=fitness_centre
swimming_pool=yes
wheelchair=yes


Otherwise, is hard for ammending this via software.

**Comment by patepelo** [comment]
This is still happening on the latest beta 2023.10.09-1-Google-beta. For example at this location: https://www.openstreetmap.org/#map=18/41.38558/2.20155

**Comment by dvdmrtnz** [comment]
> This is still happening on the latest beta 2023.10.09-1-Google-beta. For example at this location: https://www.openstreetmap.org/#map=18/41.38558/2.20155

Is that the outdoors style beta? It seems to be built from the [vng-outdoors](https://github.com/organicmaps/organicmaps/tree/vng-outdoors) branch which does not include the commits that fixed this yet. I have built from latest master and it looks good:

<img src="https://github.com/organicmaps/organicmaps/assets/47610359/c686f68e-664c-410c-b761-eb116fdf7700" width="320"/>

**Comment by patepelo** [comment]
Good. Thank you. Are we planning to update the marina icon in the future as proposed to match with blue for transport hub?

![image](https://github.com/organicmaps/organicmaps/assets/23003127/7298f2df-abd8-4b1d-a3de-59eba7adf3c7)

What's your opinion? @biodranik @vng @pastk  @RedAuburn @dvdmrtnz

**Comment by dvdmrtnz** [comment]
@patepelo I think it's better if you open an issue where that can be discussed properly!
