### ISSUE TITLE
[android] Open OSM coordinate links from the wiki's page doesn't work.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#4867]
Browser, find any article in the wiki with coordinates, press OSM coordinates, and select OM app.
OM opens but doesn't show selected coordinates.

**Comment by chiraqL** [comment]
I believe that the problem lies with the parsing of a specific type of URI obtained from the wiki page OSM coordinates. It seems that the current implementation in the geo_parser file does not account for the  '[URI format](https://www.openstreetmap.org/?mlat=51.507222&mlon=-0.1275&zoom=12&layers=M)'. So, when clicking on the OSM coordinates from the wiki page, the app opens, but it shows one's geo_location instead of the selected coordinates

**Comment by chiraqL** [comment]
The problem seems to lie with the parsing of URI obtained from the wiki page OSM coordinates, and the current implementation in the geo_parser file does not account for the URI format 'https://www.openstreetmap.org/?mlat=51.507222&mlon=-0.1275&zoom=12&layers=M'. So, clicking on the OSM coordinates from the wiki page, the app opens, but it shows one's geo_location instead of the selected coordinates

**Comment by rtsisyk** [comment]
> The problem seems to lie with the parsing of URI obtained from the wiki page OSM coordinates, and the current implementation in the geo_parser file does not account for the URI format 'https://www.openstreetmap.org/?mlat=51.507222&mlon=-0.1275&zoom=12&layers=M'. So, clicking on the OSM coordinates from the wiki page, the app opens, but it shows one's geo_location instead of the selected coordinates

Yes, `mlat=51.507222&mlon=-0.1275` is something new and is not supported yet.

**Comment by Mandeep-009** [comment]
It works on my mobile, now I tried. Can you tell if the issue is still there @vng ?

**Comment by vng** [comment]
The issue is still present.

Quebec article, tap on coordinates forwards to this page: https://geohack.toolforge.org/geohack.php?pagename=Quebec&params=52_N_72_W_type:adm1st_scale:30000000_region:CA-QC

And the OSM link is: https://www.openstreetmap.org/?mlat=52&mlon=-72&zoom=4&layers=M
Which is still not supported.

**Comment by RedAuburn** [comment]
seems to work now:

https://github.com/user-attachments/assets/18a7a3ed-c1be-48da-b770-42e7ec1ce8a1

**Comment by vng** [comment]
Well, I still can't open the openstreetmap.org links in OM. Neither from wiki nor share from browser - no OM in suggested options.
Samsung Z5 stock.

**Comment by vng** [comment]
- More context: https://github.com/organicmaps/organicmaps/pull/4415
- Looks like it depends on OS version and Android 12+ doesn't allow link interception.
- We can still fix link sharing here.
