### ISSUE TITLE
Add hours for subway station

### ISSUE THREAD

**Issue by devbreath** [organicmaps/organicmaps#4959]
Hi,
Could you add possibility to input working hours into info-card for subway stations?

**Comment by Jean-BaptisteC** [comment]
Can you give an example on OSM ?

**Comment by devbreath** [comment]
I don't have a good example on OSM. I want to see working hours for subway stations like it’s done for organizations, because not all stations work 24/7.

**Comment by Jean-BaptisteC** [comment]
For me opening_hours about metro station follow hours of metro, but you right some station have opening_hours
https://overpass-turbo.eu/s/1tE4

**Comment by biodranik** [comment]
Subway stations are already displaying opening hours. If you found an example where opening hours are present at osm.org but are absent in Organic Maps, please share them. 
Allowing editing opening hours for subway stations through Organic Maps may be risky due to possible vandalism. We may enable it later after implementing some kind of protection against random edits. 

So far, if you don't see opening hours on some objects, please add missing opening hours at OpenStreetMap.org

**Comment by devbreath** [comment]
I've added opening hours at OpenStreetMap https://www.openstreetmap.org/node/729562894, but I don’t see it on OrganicMaps

**Comment by biodranik** [comment]
Organic Maps does not instantly load OpenStreetMap.org edits. Your changes will be available in the next OM maps data update.

**Comment by devbreath** [comment]
Thank you! I've tested with new OrganicMaps update. Issue closed.
