### ISSUE TITLE
Strange postcodes in Paris.

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#5050]
Take any POI like [this](https://www.openstreetmap.org/way/54175265) or [this](https://www.openstreetmap.org/node/683370127). Have a long list of postcodes (75000;75001;75002;75003;75004;75005;75006;75007;75008;75009;75010;75011;75012;75013;75014;75015;75016;75017;75018;75019;75020;75116). But how??

It also affects Editor like [this](https://www.openstreetmap.org/node/10002259617) or [this](https://www.openstreetmap.org/changeset/135103652)

**Comment by biodranik** [comment]
Were these postcodes taken from some OpenStreetMap.org node created manually? If yes, which one?

**Comment by vng** [comment]
Yes. Actually there are 2 bugs here:
- Fix the generator to filter dummy relations like [this](https://www.openstreetmap.org/relation/7444). What sense having such kind of relations that enumerate _all_ postcodes in a city ??
- @biodranik Should also fix Editor. We upload POIs changes that were not actually modified by a user, but assigned by the generator (like addr:postcode). Why?

**Comment by biodranik** [comment]
I don't remember that we made a flag for the editor that the field was actually _edited_ or _changed_ by a user. The editor now stores everything we have in the feature and merges it when uploading into OSM. It is a big issue if we transform many tags at the generation stage that should not be otherwise uploaded into OSM.

The proper fix, assuming that we'll continue that approach with the generator, could be to mark fields as _changed_ or _edited_, and use other _non-edited_ fields only for feature matching purposes.

**Comment by Jean-BaptisteC** [comment]
Problem is solved
