### ISSUE TITLE
Unable to add POI in bookmarks with tracks

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#5141]
**Requirements**
- Default bookmark list
- Bookmark list contains a track

**Steps to reproduce**
1. Go to bookmarks
2. Disable default bookmark and enable bookmark with track
3. Go back to map
4. Select POI and use save button -> POI is save in default bookmark not in bookmark with track (default bookmark has been enabled)
The only way solution to add POI in bookmark with track is we have only 1 bookmark list in app

**System information:**
 - Operating system and its version: Android 13
 - Organic Maps version: 2023.05.08-7-Google
 - Device Model: Pixel 6

**Comment by biodranik** [comment]
Aren't bookmarks added in the last used list? You can manually select a different list by pressing Edit bookmark when bookmark is selected. Then any new bookmark should be saved in that list. 

Saving bookmarks to a visible list instead of the last used may be a good idea. But what if there are several visible lists? Where to add bookmark?

**Comment by Jean-BaptisteC** [comment]
Yes you right, bookmark is added to the latest list used
Change how we select list to save bookmarks can disturb users
I close this issue
