### ISSUE TITLE
Lots of issues reported for mapsme are also valid in this app

### ISSUE THREAD

**Issue by jidanni** [organicmaps/organicmaps#523]
https://github.com/mapsme/omim/issues/created_by/jidanni has 16 open issues, which I bet are also valid for this app.

**Comment by rtsisyk** [comment]
Hi @jidanni,

Thank you for your interest in this project! Please feel free to create tickets here for all problems you think are important. We are already overwhelmed by tickets in this repo to start looking for something else.

At least https://github.com/mapsme/omim/issues/10827 problem is already on review, see https://github.com/organicmaps/organicmaps/pull/491

BTW, we also have Telegram Group you can join: https://t.me/organicmaps

**Comment by tangsgod** [comment]
Hi @rtsisyk ,
Do you think about creating a Signal group ?
As Signal is more about privacy than Telegram, that would be a logic gestur don't you think?

**Comment by biodranik** [comment]
We see many people using Telegram from countries with heavy censorship, and it's more convenient to use at the moment.
Maybe we'll consider Signal in the future.

**Comment by tangsgod** [comment]
There are many reviews everywhere on the internet that compare those two apps. And about privacy, Signal is always a winner for many reasons. Few are that Telegram only encripted messages from end to end if you use "secret message" feature, that is not by default, and not available for group chat. While the app is open source, the messages go through a server that is not (open source),
Telegram also collect much more data than Signal, like ip adress or your contacts...

Here is one of those reviews:   https://www.tomsguide.com/news/signal-vs-telegram

But you'll find more, just duckduckgo it :)

**Comment by biodranik** [comment]
I know all details/comparisons about the apps, it was interesting to know your opinion. Do you know projects that actively use Signal groups/channels for communication with many users?

**Comment by tangsgod** [comment]
No, but I don't know so many group/channel neither :)
if you want i could dig it, but how relevant would it be to know many groups/channels using Signal I know?
I know that a lot of people are using Signal against Telegram because if privacy concern and a lot of people think that because they are using Telegram they are privatly communicating, but this is not true.
Anyway, i'll be glad to follow the project on Signal, meawhile i'll continu to follow it from here :)

**Comment by biodranik** [comment]
To invite people into Signal groups you should know their phone number. It's not very private, right? And there is no way to create a public Signal group (please correct me if I'm wrong).

Signal is the best for one-to-one communication, but for public groups there is no better tool now than Telegram IMHO.

**Comment by rtsisyk** [comment]
We tried Signal before on the previous project, and it died after two weeks because nobody wanted to use it.

**Comment by natrius** [comment]
This could be closed because the chat-question is continuoud in #617 anyway. I like Signal but i think its not good for this way of project. But matrix would be good choice, in my opinion. 

To answer the question above: Telegram just the client is open source, the server is closed source - not chance of knowing what is happening there. They invented the crypto themself and had also problems already with that already as well. There is nothing quite clear about the background. There is a bigger comparison of a lot of messengers https://www.messenger-matrix.de/ And more and more people and government organisations are switching to matrix as well, like french government, german health care system, german military communication, mozilla and other open source projects as well.

And, to add: It is possible to add a telegram-bridge so the people who still like Telegram can use it and write in the channel as well.

**Comment by RedAuburn** [comment]
as far as i can tell, there are now OM issues open for all the MM issues that remain, so i'm going to close this
