### ISSUE TITLE
Modular updatea

### ISSUE THREAD

**Issue by RustoMCSpit** [organicmaps/organicmaps#5536]
Instead of having to re-download all the data from one version to another, why not only download the different data (modified, added, removed). Would save a lot of time and bandwidth resources rather than just re-downloading the whole thing

**Comment by Misalf-git** [comment]
Because, if you add more and more ingredients into your old soup and cook it again, it won't be a fresh soup and will still go bad at some point?

Osmand has a (experimental?) live update feature that sometimes fails to correctly mix old and new data, resulting in displaying one feature multiple times. Probably a very complex topic.

I'd guess downloading those (actually rather small) map parts provided by Organic Maps is a good compromise between downloading the hole planet or having buggy maps.

**Comment by biodranik** [comment]
See #2317 and #835

**Comment by RedAuburn** [comment]
closing as duplicate
