### ISSUE TITLE
Android App not showing download progress notification 

### ISSUE THREAD

**Issue by mijorus** [organicmaps/organicmaps#5552]
I am running android 13, notification permission has been given.

**Comment by strump** [comment]
@mijorus What version of OrganicMaps do you use?
You can find version by tapping button with green OrganicMaps logo on the bottom.

**Comment by mijorus** [comment]
> @mijorus What version of OrganicMaps do you use?
> You can find version by tapping button with green OrganicMaps logo on the bottom.

2023.07.13-10-Google

**Comment by biodranik** [comment]
The system notification is not displayed because we're not using standard Android download API. The system can stop the app and not allow it to download maps in the background without either using a system download API (that downloads in one thread compared to our multithread/multiserver downloader) or wrapping our downloader into a foreground service (that may be an ideal implementation).

**Comment by mijorus** [comment]
> The system notification is not displayed because we're not using standard Android download API. The system can stop the app and not allow it to download maps in the background without either using a system download API (that downloads in one thread compared to our multithread/multiserver downloader) or wrapping our downloader into a foreground service (that may be an ideal implementation).

So is that expected? Should I close this?

**Comment by biodranik** [comment]
Well, for better UX and reliable downloads when OM is not in the foreground _we should use system downloader + notifications_, but it breaks downloads for many users...

Was there an issue already about unfinished downloads when OM goes into the background or when the screen is locked? I would update it with the foreground service implementation if it's not mentioned already.
