### ISSUE TITLE
Parking not rendered when combined with building

### ISSUE THREAD

**Issue by map-per** [organicmaps/organicmaps#5801]
**Describe the issue**
Since the parking rework #3896 in the latest (2023.08.18) release parking facilites are not rendered any more when combined with `building=*`

**Screenshots**
|    | Before | After | OSM |
|------|--------|-------|-----|
| amenity=parking | ![Screenshot_2023-08-22-12-22-51-020_app organicmaps beta](https://github.com/organicmaps/organicmaps/assets/79519062/e6209686-e841-4682-b037-3c37043a3df0) | ![Screenshot_2023-08-21-16-59-13-200_app organicmaps](https://github.com/organicmaps/organicmaps/assets/79519062/48b46348-a8c4-4c98-bb41-757951d08d15) | [OSM](https://www.openstreetmap.org/way/31126743) |
| amenity=bicycle_parking | ![Screenshot_2023-08-22-12-23-18-951_app organicmaps beta](https://github.com/organicmaps/organicmaps/assets/79519062/669a096e-9809-4f21-ad28-afdeafc03a04) | ![Screenshot_2023-08-22-21-38-43-796_app organicmaps](https://github.com/organicmaps/organicmaps/assets/79519062/c87f5463-3aff-4549-bd6c-0babcb529188) | [OSM](https://www.openstreetmap.org/way/200576778)

**Comment by Jean-BaptisteC** [comment]
CC @RedAuburn

**Comment by RedAuburn** [comment]
looks like it might have been caused by https://github.com/organicmaps/organicmaps/pull/5712, now parking has priority 300, but building has priority 400. will fix 👍

**Comment by pastk** [comment]
> looks like it might have been caused by #5712, now parking has priority 300, but building has priority 400.

Yeap, that's the reason. The renderer chooses only one type for rendering overlays (icons + captions) with the highest priority.

So maybe we should re-think the priorities. We made them lower than buildings so that parking icons won't displace adjacent buildings' captions.. FYI @biodranik 

> @pastk it seems strange that the parking icons aren't rendered even when the building has no icon or caption, is it a bug?

I think atm its quite logical that only one type is rendered in multiple-type features. Before we had drawing rules mixed from different types and there were more serious issues, see #4590 

Also its impossible to say whether a caption/name belongs to a building or to a parking, because a feature can have only one `name` tag :)

So here the renderer chooses between a building caption drule or parking's caption + icon drules. And the building wins because of higher priority.

**Comment by biodranik** [comment]
Buildings are a special type without icon. If they don't have a specific icon, then parking (or other) icons should be displayed, no?

**Comment by map-per** [comment]
> Also its impossible to say whether a caption/name belongs to a building or to a parking, because a feature can have only one `name` tag :)

I think in 99% of all cases it's the name of the parking POI. 
(But maybe it's not that good that violating 'one feature one OSM element' is common mapping practice in such cases)

> An easy option is to just put parkings priorities just above buildings (now they're just below).

I think thats a good option.
