### ISSUE TITLE
Remove useless button

### ISSUE THREAD

**Issue by Qwakr45** [organicmaps/organicmaps#5954]
Hello.

I made an investigation, and the button I mentioned on screenshot is totally useless.

It do nothing special, that can’t be done via search or long click on required place.

![IMG_0049](https://github.com/organicmaps/organicmaps/assets/144239514/302ad27b-fb7e-4e9e-bf21-b196c856f22d)

It will be better to remove it to make interface less confusing

**Comment by auge8472** [comment]
That's the button to start the navigation mode. You can't remove the button without removing one of the core features of the app.

**Comment by biodranik** [comment]
That button was removed on Android more than a year ago. Navigation mode in OM starts by selecting a destination, and then "Route To". It saves users from an unnecessary click on that button => fewer clicks, easier to build a route.

**Comment by biodranik** [comment]
@kirylkaveryn is it hard to do?

**Comment by kirylkaveryn** [comment]
@biodranik 
it easily can be removed from ios too:
![image](https://github.com/organicmaps/organicmaps/assets/79797627/4593e3d0-fb9c-4f74-b5d9-1e8b962bf0a7)

**Comment by Jean-BaptisteC** [comment]
Yes go to open PR

**Comment by auge8472** [comment]
> Navigation mode in OM starts by selecting a destination, and then "Route To".

Is that clear for everyone? And what's the advantage to hide the button only until one taps on a possible destination and the "Route To" button is in the game again? How to clarify how to add an intermediate stop when one cannot see the according buttons that are now present in the "routing mode"?

*IMHO* removing the button clarifies nothing and hides one of the core features.

**Comment by biodranik** [comment]
@auge8472 A few Android users complained when we removed it more than a year ago. Now everyone got used to it. Because you can do the same with one less button press. Did you try it and count the number of clicks with and without that button?

@kirylkaveryn can we make some hints to make the transition less painful? The simple idea was to highlight the "Route to" button on the panel with a blue (or firm green?) color for example. Also a toast can be shown (but when?). The main text message to a user is: "Select the search result, or tap/long-tap any place on the map to build a route".

Note that there is the opposite issue #5698. When we add Home/Work buttons and add recent route destinations to the Search history, it won't be necessary.

**Comment by kirylkaveryn** [comment]
@biodranik Apple human design guides recommend showing such kind of info with PopOverPresentationController
we can show it on the first appearance after app update and disable it after that.
This cloud-style popover controller disappears after the user taps on someplace on the screen. And we can it's change style/background etc
https://developer.apple.com/design/human-interface-guidelines/popovers

And optionally we can add switcher to settings that allow user to enable/disable this tab 

![Simulator Screen Recording - iPhone 14 Pro - 2023-10-06 at 18 23 00](https://github.com/organicmaps/organicmaps/assets/79797627/1632c12a-ce9c-4ff3-a9ce-f1055a7645f3)

**Comment by biodranik** [comment]
0. I like that popover to educate users, let's try it here and for other issues too. Can you please create a separate issue/request for it?
1. Additional unnecessary settings are a bad idea, we try to keep OM as simple as possible and introduce only those settings that are really, really needed.
2. Buttons should be in sync with Android.
3. Android already has floating buttons instead of the toolbar. It should be also implemented in iOS, as it allows one to see more map, and has a better "full-screen" feeling.
4. The "remove" message should only appear if it is not the first-time installation, but the upgrade. Is it feasible? There was an isFirstLaunch check or similar, need to test it carefully.
