### ISSUE TITLE
Distinguish primary, secondary, tertiary roads by colors

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6128]
At the moment many roads in OM have the same white color. It was done like in Google Maps, to match the expectations of the general public and to avoid map cluttering.

Maybe we can try to introduce some _slight_ visual differences without much cluttering for the general style? Maybe at least for primary/secondary roads?

As we plan to introduce different map styles for specific activities #1577 we can properly distinguish road types by colors to make it easier for some specific planning.

We have also discussed that there are two main high-level use cases of OM that may also have different styles/coloring:
1. Route planning mode.
2. Active "in-field" navigation mode.

For cars actually, we can already do it in the vehicle style (although it's not used _yet_ for planning the route, only when car navigation is active).

@pastk WDYT?

**Comment by Misalf-git** [comment]
IMO differentiating roads by color would make sense in all map styles because I always have to be aware of traffic.
One might prefer or want to avoid roads that likely allow higher speeds or are more frequented than others, regardless of the current means of transportation.

**Comment by pastk** [comment]
Sounds good!
If there is someone who is good working with colors - feel free to submit a PR! Or a mock up at least and we can help integrate the colors :) Its important to avoid conflicts with other colors used in OM so that roads are distinguishable / contrast enough when drawn above different areal features (e.g. different shades of yellow are used for parkings, beaches and farmlands already).

**Comment by pastk** [comment]
A slightly different idea is to keep the number of road colors the same (now its 2 kinds of orange for motorways/trunks/primaries and a white for the rest) at low zooms, but start using orange for lesser roads (secondary, tertiary) when zoomed in - because at higher zooms roads start to be more apparently different by their widths also.

**Comment by biodranik** [comment]
Using width for visual difference is more intuitive than a color. How can someone decide what is which road type by just a color, with the same width?
