### ISSUE TITLE
Summary Wikipedia in the app language

### ISSUE THREAD

**Issue by DavidMacalister** [organicmaps/organicmaps#6153]
**Summary Wikipedia in the app language**
I'm Brazilian, so my app is in Portuguese, but the articles are always in English, I don't know if it's a question of the Wikipedia API, but if possible, it would be cool if the summary was in the app's language

In some cases, as the article doesn't even have an English version, it doesn't even have an abstract.

![image](https://github.com/organicmaps/organicmaps/assets/114320580/845a18a4-d2c7-4a98-99dd-506426335a1d)

**Comment by biodranik** [comment]
We can add wiki articles in other languages too, that's not hard. But the maps size may increase. @vng let's experiment? Not sure though that non-two letter language codes like pt-BR will be properly supported from the start. @newsch can you please confirm that?

@DavidMacalister can you please help by making a list of unnecessary article sections that should be ignored/removed from stored wiki pages, like it's done here? https://github.com/organicmaps/wikiparser/blob/main/article_processing_config.json

@newsch it is enough to update the file mentioned above to add a new language into the parser, right?

**Comment by matheusgomesms** [comment]
PT and PT-BR, on Wikipedia, are the same (pt), just to let you know. Probably the same case here with ES-MX, which should have ES wiki articles.

> @DavidMacalister can you please help by making a list of unnecessary article sections that should be ignored/removed from stored wiki pages, like it's done here? https://github.com/organicmaps/wikiparser/blob/main/article_processing_config.json

Here it is:

    "pt": [
      "Notas",
      "Referências",
      "Referências e Notas",
      "Bibliografia",
      "Ligações externas",
      "Ver também",
      "Leitura complementar"
    ],

**Comment by newsch** [comment]
> Not sure though that non-two letter language codes like pt-BR will be properly supported from the start. @newsch can you please confirm that?

The wikiparser only looks at Wikipedia's subdomains, which mostly use standard language codes [with some exceptions](https://meta.wikimedia.org/wiki/List_of_Wikipedias#Nonstandard_language_codes). If you want to support any of the wikis in that list, we may run into problems and need to create a mapping of wikis to language codes.
As mentioned above, since there is no `pt-BR` Wikipedia it wouldn't work, but `pt` will.

I think the apps/cpp should handle falling back to `pt`/`es`/`en` from `pt-BR`/`es-MX`/`en-GB`? I don't know how that works, but it looks like [the supported languages in the descriptions section](https://github.com/organicmaps/organicmaps/blob/2023.09.22-27-android/coding/string_utf8_multilang.cpp) don't include the "region subtags"
 
> @newsch it is enough to update the file mentioned above to add a new language into the parser, right?

Yes, once the new language is added it will be downloaded on the next run.

If you want to try a language once and don't care about the removed sections, you could download and extract only that language:
```
LANGUAGES=pt ./download.sh $DUMP_DIR
./run.sh $DESCRIPTIONS_DIR $PLANET.osm.pbf $DUMP_DIR/latest/ptwiki-*.json.tar.gz
```
I think the generator will pick it up automatically

**Comment by matheusgomesms** [comment]
Is this working? I don't see Wikipedia in Portuguese (both PT-PT and PT-BR) with this last November update.

**Comment by biodranik** [comment]
Hm, looks like there is an issue on the server, I'll investigate.

**Comment by davidmacalister** [comment]
> Is this working? I don't see Wikipedia in Portuguese (both PT-PT and PT-BR) with this last November update.

No

**Comment by matheusgomesms** [comment]
Confirming now it works, thanks a lot guys!!!

![IMG_1872](https://github.com/organicmaps/organicmaps/assets/86851490/d5ea87ea-028f-4694-a65e-fe5939a84e56)
