### ISSUE TITLE
The official chat is on a closed network

### ISSUE THREAD

**Issue by opk12** [organicmaps/organicmaps#617]
I am an OpenStreetMap mapper, active in some regional OSM local and global chats. I am curious to try Organic Maps and read the chat to grab general knowledge.

But it is not Open or convenient to require the installation of any specific app; and I would avoid Telegram for the well-known issues of security and freedom.

The OSM chats have a bot to copy-paste Telegram messages to a dedicated [Matrix](https://wiki.osm.org/Matrix) or [IRC](https://wiki.osm.org/IRC) room, to allow anyone to participate with many independent FLOSS clients. Matrix is preferred, because it connects the OSM chat networks and can reach the most OSM users and official chats.

The Telegram users see no difference, except that one user copy-pastes messages typed by non-Telegram users.

If desired, I can provide contacts of OSM staff that is knowledgeable in this Matrix bridging.

**Comment by j5k** [comment]
I'm very interested in this chat too, but I don't want to use Telegram for the same reason as mentioned mentioned.

In the github discussion section you see an answer for this request (Idk how to link to a discussion topic).

**Comment by natrius** [comment]
Hey, in my opinion an open source project should use an oss chat as well, not telegram (but i undestand the reach might be higher in Telegram). I set up a channel on the matrix-main-server. If some of the main-developers show up there i can give them admin-rights. #organicmaps:matrix.org and i added some additional adresses as well. 

I'm myself admin of the #osm-at:matrix.org channel and moderator of #osm-de:matrix.org - both are bridged to IRC-Channels.

**Comment by jwsp1** [comment]
> Hey, in my opinion an open source project should use an oss chat as well, not telegram (but i undestand the reach might be higher in Telegram). I set up a channel on the matrix-main-server. If some of the main-developers show up there i can give them admin-rights. #organicmaps:matrix.org and i added some additional adresses as well.

Personally, I would also like to see OrganicMaps advertise Matrix instead of Telegram. But an official group created and advertised by one of the core devs would be better.

Since I quite follow the Matrix project, I would personally wait for another couple of weeks - they will release a feature called Spaces soon. It's a game-changer in many aspects. You can imagine it like a file explorer folder structure. Join the Space and see lots of groups/channels. One could join a basic discussion group (maybe several for general basic questions [not followed by dev-team, managed by users helping users] or Android/iOS issues), a release announcment channel (read-only, maybe several for different langauges), dev group (with a knocking feature where a member needs to agree the join-request),...
But since this feature is in beta (exits soon though, according to the team), I would wait a couple of weeks.

For the Telegram community, you could simply bridge the matrix room to Telegram: https://matrix.org/bridges/#telegram or https://t2bot.io/telegram/ . The Telegram community can keep using Telegram if they want while OrganicMaps advertises an open source chat tool instead of a proprietary one

I will comment here again when Spaces is released stable.

**Comment by biodranik** [comment]
Thanks, we will consider Matrix with Telegram bridge a bit later, when we have more time to properly set up everything and announce it. Please keep us updated.

**Comment by nep2ner** [comment]
The spaces feature is beta now and works pretty well. Let us know if you'd like assistance setting up a bridge.

**Comment by jwsp1** [comment]
It has been in beta for a couple of months and will exit beta probably next week (source). Let's wait for the stable release.
I will keep you guys updated.

**Comment by jwsp1** [comment]
Matrix Spaces has been launched last week.
My suggestion is to create an account here https://app.element.io/ while choosing the matrix.org server. Then, on the left side panel, create a new public space by clicking the plus-button. You can enter a name, picture, address under which it can be found and description. You will be asked how many rooms you want and how they should be named (you can add/delete rooms out of the space later). What comes into my mind: General Discussions (users helping users), Technical Discussions (admins/dev helping users), Discussions (Russian), Release Notes (read-only), Dev-Chatgroup (private, only accessible by invitation),...
You can also mirror the existing Telegram Chat to Matrix by following [this easy 4-step-setup](https://t2bot.io/telegram/). That way, people can also stay on Telegram, if they want to.
If you need further help, don't hesitate to ask :)

**Comment by natrius** [comment]
FYI i created a space for testing that contains already the general organic maps room on matrix. Space: #organicmapsspace:matrix.org and the room is #organicmaps:matrix.org

**Comment by jwsp1** [comment]
Are you member of organicmaps? If not, I would prefer to see the core-dev creating an official space (hence please remove yours, at least change usernames). Also, bridging to Telegram is important which can only be done if an admin of the telegram group invites the bot.

**Comment by biodranik** [comment]
Looks like @andrewshadura already created https://matrix.to/#/#organicmaps:matrix.org
We can use it (assuming admin rights) and bridge it with Telegram or can create a new one with a different name. I've joined the space.

**Comment by biodranik** [comment]
Done, the bridge is established. Welcome to the Matrix.
