### ISSUE TITLE
Login to OSM doesn't work

### ISSUE THREAD

**Issue by SoNickRND** [organicmaps/organicmaps#628]
Can't login to OSM account.
Checked my email \ pass twice.
Checked against OSM site, email\pass is valid.

**Comment by TimMagee** [comment]
OSM log in worked for me. I successfully updated the map from Organic Maps today.

**Comment by rtsisyk** [comment]
A hotfix is on review in Google Play.

**Comment by SoNickRND** [comment]
> A hotfix is on review in Google Play.

Well, mine from Gplay, should I switch somewhere else?

**Comment by SoNickRND** [comment]
> OSM log in worked for me. I successfully updated the map from Organic Maps today.

Should we check for differences? Mine android version is 10,  Lineage OS and phone is OnPlus A2003.

**Comment by TimMagee** [comment]
@SoNickRND I use Android 7.0 on a Moto G4.

**Comment by idekovets** [comment]
On Nexus 5 with AOSP 8.1, F-Droid, 
Organic Maps version — 2021.06.12-7-g75fd600f97-FDroid
I have login error.

On iOS logged in successfully.

**Comment by rtsisyk** [comment]
> Well, mine from Gplay, should I switch somewhere else?

Google Play reviews may slow to over a week due to COVID:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/1799054/122671995-fa248700-d1d1-11eb-89b1-fe2e5e117096.png">

Here is a link to the latest APK from Google Play signed by Google Inc:

https://drive.google.com/file/d/1LH39qMyviXytu2Llf7Ih3FQJkn2dgMQA/view?usp=sharing

Or please just wait until Mon or Tue until Google accepts it.

**Comment by j5k** [comment]
FYI: on new F-Droid version 2021.06.20-6 I can log in successfully. Thanks for fixing.

**Comment by idekovets** [comment]
F-Droid 2021.06.20-6 work well!

**Comment by SoNickRND** [comment]
Working now, closing this.
