### ISSUE TITLE
[ios] Distance in navigation panel is not updated between 10km and 1000m

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6478]
There is a regression when the distance in navigation mode is not properly updated and stays at 10km without an update. Two users have reported it. Looks like it reproduces in CarPlay, I wasn't able to reproduce it on the iPhone.

> ...I‘m on the road again. Seems the problem is between 10 km and 1 km. Position and speed is not affected.
When entering 1 km and lower it‘s counting down from 10 km to 900 meters
Also when it's more than 10 km to the next exit everything is okay. Just between 10 km and 1 km

> iPhone 12, iOS 17.1
I’m using CarPlay when navigating with organic maps
The phone's language is German.
AppStore says Organic Maps is up to date, Version 2023.09.22_20
I’m not sure if I described it correctly. OrganicMaps told me, 56 km to the next exit. Then 55, 54, and so on, until 10 km is reached. Then the display was not counting down, it still says 10 km until 1 km is reached and it needs to switch to meters.
Speed is still correct and the map is moving like normal.

**Comment by biodranik** [comment]
Was anyone able to reproduce this bug?

**Comment by postspectacular** [comment]
I've been having the same issue for the past few months (just kept on forgetting to report the issue). I'm on iOS 16.6.1 w/ English as system locale, but using German for Organic Maps (because I hoped it would change the voice...). I will do some more testing with English over the weekend and report back. Just wanted to confirm the issue for now! It's reliably happening if one stays on a road for longer than 10km (e.g. on motorways). The countdown goes well until 10km till the next exit/direction change, then stops updating until 1km before, then continues...

**Comment by biodranik** [comment]
@postspectacular thanks! Any additional input is valuable. Do you see this issue only in CarPlay?

**Comment by postspectacular** [comment]
Understood. We're going on a trip tomorrow, will try it on both iOS and Android. Also, I've upgraded to iOS 17.2 now, so will be interesting to see if it maybe makes a difference...
