### ISSUE TITLE
[android] Source files and line numbers are not correct in logs

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6559]
Highly likely it is caused by recently merged R8.

There is no "SourceFile.java", and numbers are not correct even if you try to add them to the function name.

```
11-14 15:52:25.546 (Thread-3) E/OMcore: core/jni_helper.cpp:206 HandleJavaException(): java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
	at app.organicmaps.util.log.Logger.log(SourceFile:52)
	at app.organicmaps.util.log.Logger.d(SourceFile:2)
	at app.organicmaps.util.HttpClient.run(SourceFile:33)
```

**Comment by rtsisyk** [comment]
It looks like that the only way to disable `SourceFile:<magic number>` behavior is to disable R8 optimizations completely via `-dontoptimize` option, which will re-adds 3MB back to the binary. Unfortunately, `-dontobfuscate` (already enabled) doesn't help.
 
R8 [provides `retrace` tool to recovery real file names](https://developer.android.com/tools/retrace):

a.txt:
```
W System.err: java.lang.Throwable
W System.err:    at app.organicmaps.util.HttpClient.run(SourceFile:38)
```

~/Library/Android/sdk//cmdline-tools/latest/bin/retrace ./android/app/build/outputs/mapping/googleBeta/mapping.txt a.txt:

```
W System.err: java.lang.Throwable
W System.err:    at app.organicmaps.util.HttpClient.run(HttpClient.java:69)
```

Basically, the missing source file is not a problem. Java stack traces still have original full Java class names, which are mapped 1:1 to the source files. However, the cryptic line number is definitely an issue. It looks like that `mapping.txt` file is required to recover the line:

```
[REDACTED]
app.organicmaps.util.HttpClient -> app.organicmaps.util.HttpClient:
# {"id":"sourceFile","fileName":"HttpClient.java"}
    3:12:java.io.InputStream getInputStream(java.net.HttpURLConnection):216:216 -> getInputStream
    13:24:java.io.InputStream getInputStream(java.net.HttpURLConnection):217:217 -> getInputStream
    25:34:java.io.InputStream getInputStream(java.net.HttpURLConnection):218:218 -> getInputStream
    35:44:java.io.InputStream getInputStream(java.net.HttpURLConnection):219:219 -> getInputStream
    45:50:java.io.InputStream getInputStream(java.net.HttpURLConnection):221:221 -> getInputStream
    51:58:java.io.InputStream getInputStream(java.net.HttpURLConnection):225:225 -> getInputStream
    59:59:java.io.InputStream getInputStream(java.net.HttpURLConnection):227:227 -> getInputStream
    3:10:app.organicmaps.util.HttpClient$Params run(app.organicmaps.util.HttpClient$Params):63:63 -> run
    11:35:app.organicmaps.util.HttpClient$Params run(app.organicmaps.util.HttpClient$Params):68:68 -> run
    36:44:app.organicmaps.util.HttpClient$Params run(app.organicmaps.util.HttpClient$Params):69:69 -> run
[REDACTED]
```

Changing `run(app.organicmaps.util.HttpClient$Params):69:69` in the last line to `run(app.organicmaps.util.HttpClient$Params):99:99` changes the output from `app.organicmaps.util.HttpClient.run(HttpClient.java:69)` to `app.organicmaps.util.HttpClient.run(HttpClient.java:99)`.

I am not familiar with R8 internal, but it looks that the mapping file is actually required to recover the original line number. This file is already uploaded to Google Play, so recovering line number for Google Play shouldn't be a big deal. However, we need to figure out how to maintain the history of mapping.txt for betas, fdroid and other builds. 

For now, I am disabling the optimization via `-dontoptimize`. This is sad because it re-adds 3MB of crap back, which is mostly `androidx.`, `com.google.android.` and `kotlinx.` outside our control. 

Let's try to re-enable after streamlining the procedure of decrypting of line numbers.
