### ISSUE TITLE
Add sac_scale

### ISSUE THREAD

**Issue by meinrad-0** [organicmaps/organicmaps#6593]
All hiking paths look the same now, despite difference in difficulty. Also when tapping it says "path" or the name. So one cannot know what to expect.

Would be great if one taps the path that it would give its difficulty. The sac_scale is great for this. Another option would be to make a sort of warning sign for the last two steps of the scale when tapping the path.
A next step would be to also visualize them differently

As an example have look at this: 49.219973, 20.025669 . Looks like a normal hiking path in OM. In reality this is a rather hard path with very steep sections (chains as well). In OSM this is marked as sac_scale=demanding_alpine_hiking, which is the second most difficult. I think it is useful and important to reflect this in OM.

I searched for a similar issue, but couldn't find it. Sorry if it is a duplicate

**Comment by patepelo** [comment]
This totally needed. Thanks for opening it.

Another way would be to represent it as text when zooming in.

For example:
Zooming in: Great Lakes path - sac:3

Zooming out: Great Lakes path

---

Or if this is just a number, to put the value in between dashed lines (like the one way arrow) of streets.

This could later apply also to MTB scale (there are two).

**Comment by pastk** [comment]
The biggest challenge is how to handle many possible combinations of `smoothness`, `surface`, `trail_visibility`, `sac_scale`, `tracktype` etc.
- https://github.com/organicmaps/organicmaps/issues/6447#issuecomment-1790522426

Its easier if its about text-only display in PP, then we can theoretically just list all possible "attributes" there.

Other related discussions:
- https://github.com/organicmaps/organicmaps/issues/1577#issuecomment-980177481
- https://github.com/organicmaps/organicmaps/issues/2185#issuecomment-1618876869
- https://github.com/organicmaps/organicmaps/issues/4898

**Comment by pastk** [comment]
> Or if this is just a number, to put the value in between dashed lines (like the one way arrow) of streets.

There was a long discussion how to better represent it textually here:
- https://github.com/organicmaps/organicmaps/pull/4242

**Comment by pastk** [comment]
Maybe it would be better to add `sac_scale=` into metadata instead of a separate feature type or a subtype.

It'll solve the "display trail's details in the PP" case efficiently. This way it'll be easier to support other (country-specific) classifications like an Italian [CAI](https://wiki.openstreetmap.org/wiki/Proposal:Cai_scale).

For rendering purposes I think we can use a type/subtype approach and should generalize difficulty in 2 or maximum 3 tiers like
1. Leisure walking
2. Hiking
3. Extreme / alpine / technical / dangerous routes

ATM its probably impossible to distinguish 1. and 2. (as many trails are just `highway=path/track/footway` w/o any additional tags), so its more practical to have just "Trails" and extreme stuff (could be rendered e.g. dotted red).

**Comment by mahdi1234** [comment]
Above sounds like perfect to mark difficulty, but should also be mixed with colors where it applies. So maybe difficulty could be solid line easy, dashed more difficult, single points very demanding. It's similar to how Osmand marks smoothness if one would like to imagine.

**Comment by pastk** [comment]
If difficulty is not set / unknown then it should default to an ordinary "trail" (not extreme) IMO.

**Comment by PathTreader** [comment]
Love this suggestion. At the OSM layer I have been championing more sac_scale tagging on OSM in mountain and popular walking areas in the UK. 

Rendering trail hiking difficulty (sac_scale) should probably off by default and be an intentional selection. Trail visibility is in interesting one. Perhaps it could use opacity? And again be an optional setting?

Regarding colour, consider using existing colour schema -

https://www.sac-cas.ch/fileadmin/Ausbildung_und_Wissen/Sicher_unterwegs/Sicher_unterwegs_Wandern/2020_Berg_Alpinwanderskala_EN.pdf

**Comment by biodranik** [comment]
> The biggest challenge is how to handle many possible combinations of smoothness, surface, trail_visibility, sac_scale, tracktype etc.

We can implement a single-tap selection of tracks to quick-check its properties. And show them in the Place Page (PP).

**Comment by alensiljak** [comment]
The way, for example, Bergfex deals with the difficulty (only!) is by adding a little tag to the path:

**Comment by alensiljak** [comment]
Just noticed that, while the difficulty was on, the SAC scale colouring wasn't. This is the way OsmAnd deals with the difficulty and visibility:

<img src="https://github.com/organicmaps/organicmaps/assets/462445/28418ec3-5739-44f5-9fc8-7736c9282f0b" width="500" />

The difficulty is marked here according to the SAC scale - blue (T1-2), red (T3), black (T4-6).
The visibility is marked by the distance between the dots on the path. I'm not yet sure what the dashed line is. Have to look it up.

**Comment by pastk** [comment]
> Another map that displays `sac_scale` nicely is [OpenAndroMap](https://wiki.openstreetmap.org/wiki/OpenAndroMaps):

do they combine it with `trail_visibility=` and `route=hiking` somehow?

**Comment by map-per** [comment]
Yes, for `trail_visibility` different dash patterns are used and hiking route relations are displayed as a separate lines next to the path (e.g. the green 446 and 445 routes in the picture) or above the path on lower zoom levels.

The Legend of the map is [here](https://www.openandromaps.org/kartenlegende/elevation-hike-theme). At the moment this is the best hiking map style I know, so if you want to download it for inspiration / espionage the steps are described in the [wiki](https://wiki.openstreetmap.org/wiki/OpenAndroMaps).

**Comment by alensiljak** [comment]
> Another map that displays `sac_scale` nicely is [OpenAndroMap](https://wiki.openstreetmap.org/wiki/OpenAndroMaps):
> 
> They use different colours for `sac_scale`
> sac_scale 	colour
> T1 	yellow
> T2 	blue
> T3 	red
> T4-T6 	black

This is really good. I managed to install it and try it out. This colouring makes it fairly easy to spot sections of different grade on the way. Also the via-ferrata, chains, and ladders are on the map, too, so you know why the route may be graded high. This finally helped me find a path through the cliffs (I have to take on the weekend), which are full of climbing and via-ferrata routes and are just a mess in OsmAnd, all being displayed more-or-less the same way.

The colours are also the standard Austrian system. And, I think most are used to this scheme from skiiing or other sports. blue = middle, red = hard, black = avoid if you can. Highly recommended.

One issue I'm not sure how to set up in an elegant way is - what happens when the colours of the route and the difficulty are mixed up. I.e. route has blue markers but is T3 level (red) or vice versa, red markers on a T2 (blue) route. Seems easy to mix up which one's which.
In the two themes that I have (Elevate and Elements), it seems that most hiking routes are just yellow, with a text saying "blau", for example. That's one way to do it.

Important to note that the length of the dashes and the distance between them indicate the path visibility, which is really useful and easily noticeable. Long, tightly lined dashes make almost a continuous line, while short, widely-distanced dashes show that a route may not be so easy to identify on the ground.

As for the colours... There should be an indication of a marked hiking path vs just a path (i.e. hunters' or a regular walking path). Green might not be such a good choice because those paths are mostly in the green areas, as well. The Elevate scheme uses yellow, which is great indoors and on a dark background. I wonder what it will look like tomorrow, outside, on a bright day. I'll try it out on a short (7-8km) hike to a via ferrata spot and later to identify some via ferrata routes.

Another cool feature is how it displays the potentially dangerous elements:

<img src="https://github.com/organicmaps/organicmaps/assets/462445/8b19327b-255e-44ff-bee4-9671eaf68625" width="300px" />

Here showing the yellow "slow" marks for "demanding terrain" and the red one for "secured section". The whole section is "demanding terrain" so I assume the mark only shows the beginning of it. The secured section is also normally indicated on the map with a ladder but here gets a warning mark. Great.

**Comment by alensiljak** [comment]
And this is how it looks without the planned-route overlay:
<img src="https://github.com/organicmaps/organicmaps/assets/462445/d4854e34-5c77-44a6-9c4a-3e05cb786995" width="300px" />

**Comment by pastk** [comment]
> This is really good. I managed to install it and try it out. This colouring makes it fairly easy to spot sections of different grade on the way. Also the via-ferrata, chains, and ladders are on the map, too, so you know why the route may be graded high. This finally helped me find a path through the cliffs (I have to take on the weekend), which are full of climbing and via-ferrata routes and are just a mess in OsmAnd, all being displayed more-or-less the same way.
> 

It'd be great to see comparison screenshots for that tricky place in OsmAnd, Mapy.cz and OpenAndroMap!

One thing I don't really like about this style is how tracks are displayed:
![image](https://github.com/organicmaps/organicmaps/assets/18434508/c2e43c98-259e-4a2b-bf05-b8297e8e7dd3)
Dashing doesn't work well for outlined thick lines..

**Comment by map-per** [comment]
@alensiljak: Can you also take a look at this PR for OrganicMaps (#7810)

**Comment by alensiljak** [comment]
I actually like how OsmAnd adds the route colour underneath and with some transparency, leaving the actual path line free for having a different style (colour, thickness, pattern).

**Comment by patepelo** [comment]
Thanks for all the examples.

> I actually like how OsmAnd adds the route colour underneath and with some transparency, leaving the actual path line free for having a different style (colour, thickness, pattern).

 I'd prefer the OpenAndroMap, marking it contiguous to the main line. It looks better IMO and is compatible when two or more relations share the same path. 
 
Like a subway map approach.


P.S. This is an example of FacilMap with Hiking layer. It's hard to read.

![image](https://github.com/organicmaps/organicmaps/assets/23003127/b27351e5-e242-4c25-abfb-9bd679127025)

**Comment by alensiljak** [comment]
> Like a subway map approach.

ok, but just be careful about cases like this: 

<img src="https://github.com/organicmaps/organicmaps/assets/462445/a2f3da45-83c0-45c3-8901-c0b01a04395b" width="300px" />

And there's more below that don't even fit on the screen. Having all possible route colours might not be as useful as it sounds. Although, I agree that it helps in reality, i.e. when a green path is better maintained and has more marks on the path than the red path you are following but OsmAnd chose to display blue. Then at least you know that, for a section of the way, you can just follow the green markers. Or something like that, which happens often in practice.

**Comment by pastk** [comment]
> Having all possible route colours might not be as useful as it sounds.

[`osmc:symbol`](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol) contains a `waycolor` which is usually used as a "main color" to use on the map. Also some routes (~15%) have a tagged `colour=` for that purpose.

**Comment by pastk** [comment]
Please keep in mind the Outdoors style is intended not solely for hiking, but also for e.g. backcountry and mtb cyclists, 4wd/offroad.

Before proceeding with any kind of `sac_scale` implementation we need to have a good understanding how it'll affect implementation of other features like highlighting of marked routes, displaying mtb grades, tracktype/smoothness for wheeled adventures, shared use sections, etc.
I.e. we need to develop a systematic comprehensive vision first (not necessary super detailed).

If we use all available expressive means (bright colors, different line patterns, "shields", etc.) just for sac_scale, then we'll struggle adding routes highlighting or track grading.

**Comment by pastk** [comment]
- advanced users want all possible sac_scale, trail visibility, etc. options rendered differently
- while most of the users will find all those colors and dash patterns overwhelming and hard to memorize

Remember that OM's way is more about well-thought-out simplicity that works for most cases, not about complexity and abundance of options.

A balanced solution would be to reduce overall number of difficulty grades rendered on the map, while providing a way to see details when needed (e.g. selecting a section or zooming in deeper). It'll also leave more options to implement routes, cycling grades etc. later.

- just 2 grades for the main style (e.g. "fine for the most" and "think twice before you go")
- 4 grades is probably enough for Outdoors
- Outdoors grades should look like an extension of the main style grades, not a completely different visual system

Note that I'm talking about "overall difficulty" grades here, i.e. without separate `trail_visibility`.
The value of the grading system is to provide a simple understandable scale of difficulty by hiding/consolidating various requirements like pathfinding skills, level of fitness, survival skills, sense of balance, gear requirements, etc.
The original SAC scale has trail visibility incorporated into the grades. OSM chose to tag it separately (see https://wiki.openstreetmap.org/wiki/Proposal:Hiking#Usage,_Tags_and_Values) - which is fine as it allows more flexibility. But the point is that it's not necessary to display all possible attributes separately :)

E.g. for vehicle tracks we should also consolidate `smoothness` and `tracktype` into just 3-4 grades.

**Comment by alensiljak** [comment]
> [`osmc:symbol`](https://wiki.openstreetmap.org/wiki/Key:osmc:symbol) contains a `waycolor` which is usually used as a "main color" to use on the map. Also some routes (~15%) have a tagged `colour=` for that purpose.

This all works when there are maximum of a few routes (relations) sharing the same section of the actual land. The problem begins, as I've shown above, when there's 20+ named routes on the same section or a path. Because each one of them has its own colour and symbol.
Maybe I'm missing something and I certainly hope that's the case. In the given example of using the metro colouring, it would be like having 20 lines going through the same station. What colour do you put on the station, if you only have to choose one?

**Comment by pastk** [comment]
> The problem begins, as I've shown above, when there's 20+ named routes on the same section or a path. Because each one of them has its own colour and symbol. Maybe I'm missing something and I certainly hope that's the case. In the given example of using the metro colouring, it would be like having 20 lines going through the same station. What colour do you put on the station, if you only have to choose one?

Ah sorry I've misunderstood your point indeed!

There was a discussion about this particular problem with multiple routes sharing a section: https://github.com/organicmaps/organicmaps/issues/2185#issuecomment-1858504007

**Comment by pastk** [comment]
> The location is [here](https://www.openstreetmap.org/#map=15/47.8130/16.0234&layers=P).
> 

Mapy.cz (web version)

![image](https://github.com/organicmaps/organicmaps/assets/18434508/884137ec-0a7e-4dbc-8e62-6c15d10aa162)

**Comment by map-per** [comment]
> Before proceeding with any kind of sac_scale implementation we need to have a good understanding how it'll affect implementation of other features like highlighting of marked routes, displaying mtb grades, tracktype/smoothness for wheeled adventures, shared use sections, etc.
I.e. we need to develop a systematic comprehensive vision first (not necessary super detailed).

I think it makes sense to split the map style for hiking and cycling at some point. Hikers are more interested in `sac_scale` and `trail_visibility`, while `smoothness` is more important for cycling. Moreover both have different marked routes.
So cycling and hiking are so distinct use cases, that it makes sense to have a separate map layer for each.

In my vision the hiking map style is similar to OpenAndroMap, showing `sac_scale`, `trail_visibility` and hiking routes. On the other hand the cycling map style is similar to [CycleOSM](https://www.openstreetmap.org/#map=14/48.1365/11.5782&layers=Y), showing `smoothness`, `mtb_scale` and cycling routes.

**Comment by pastk** [comment]
We'll have a separate cycling map style at some point for sure, but its going to be primarily oriented towards urban and leisure cycling, i.e. based off the current main map style.

Whereas backcountry and mtb cycling style needs to be based off the Outdoors style.

So its either two separate cycling map styles (more complex for users (considering there will be other styles like driving, public transport..) and higher development and maintenance efforts) or fitting backcountry cycling and driving into the current Outdoors map..

Actually I like the idea of configuring the map style via two selectors: a "mode of transport" (aka routing mode) and an "activity". So a user could choose e.g. "cycling" + "outdoors" or "cycling" + "sight-seeing" or "pedestrian" + "shopping" or "vehicle" + "outdoors", etc. see https://github.com/organicmaps/organicmaps/issues/2355#issuecomment-1092002191 for details.
But so far it looks its both hard to design/implement and high maintenance.

Routes are better done as a switchable layer (akin to user imported tracks), otherwise they draw too much attention and in many cases its unwanted (esp. where routes network is dense).
