### ISSUE TITLE
Elevation data doesn't match the OSM island contour

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#6746]
28.763817, -18.005605

![image](https://github.com/organicmaps/organicmaps/assets/170263/08d6b370-60a3-4d28-b6fb-97d780310e41)

**Comment by RedAuburn** [comment]
tracestack topo has it right:
https://www.openstreetmap.org/#map=16/28.7631/-18.0035&layers=P

CyclOSM has the same as OM:
https://www.openstreetmap.org/#map=16/28.7678/-18.0060&layers=Y

**Comment by vng** [comment]
Interesting. At first, I thought that Tracestack Topo does some intersection with coastlines, but nope - can move North and see the same issue. Probably some other dataset or still some fancy processing.

Elevation Finder makes the same interpolation as in OM:
<img width="802" alt="Screenshot 2023-12-08 at 23 11 30" src="https://github.com/organicmaps/organicmaps/assets/175612/8ae48642-7be2-428a-ab65-a4a3f93e71ee">

**Comment by muralito** [comment]
There was a volcanic eruption there in 2021. https://en.wikipedia.org/wiki/2021_Cumbre_Vieja_volcanic_eruption
Maybe this is the cause of data mismatch.

**Comment by biodranik** [comment]
@muralito can you please check if it's ok in the latest release?

**Comment by muralito** [comment]
> @muralito can you please check if it's ok in the latest release?

This large delta between datasets was corrected. In all the west coast of the island, the topo data and seems pretty ok in 2024.03.31-8 -FDroid and 26-MAR-2024 OSM data. There are Just a few small differences when the isolines are very close one to the other, but with the tools i can't say if the problem is in the coastline or in the topo data. 

By the way, the coastline seems to be adjusted in the last weeks in OSM,
The OpenTopoMap seems to have bad data in this coast.
