### ISSUE TITLE
Please remove kayak integration

### ISSUE THREAD

**Issue by Remko56** [organicmaps/organicmaps#6773]
I saw a post here https://weeklyosm.eu/archives/16873 and I came to write my opinion.

Dear developers,
We are really appreciate your affords to run such good project. But I think you should NOT add anything online in your app. Especially third-party.

As solution of this I suggest you following:
- Remove such integration and place text about how you need our donations in “About app” menu (the menu where all your official links placed)
- Ask user to support you when user launches your app first time

I really like your app, but I find kayak integration unnecessary and annoying.

Have a nice day:)

**Comment by Jean-BaptisteC** [comment]
Thanks for your calm in your sentences
Did you have check other issues? We have already issues on this topic.
It's planned to add setting in app to disable Kayak integration.

**Comment by pastk** [comment]
Thanks for your input!

Basically its the same as
- #6707

**Comment by Evilprof** [comment]
I really don’t think this is good idea to add something like kayak (even as link) to OM. It’s better create something by yourself, not using third parties.

I know this can be difficult, but third-parties can’t be trusted until they will become open source too.

**Comment by Hfhcihufgd** [comment]
The kayak crap is sticky one, as I see.

**Comment by Misalf-git** [comment]
> Thanks for your input!
> 
> Basically its the same as
> - #6707

**Comment by Kasi78** [comment]
[They got anti feature 😂😂😂😂](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14082/diffs?commit_id=cdf6baa74e0f222ebb210ae63ca4d51a4b3807a8)

https://github.com/organicmaps/organicmaps/issues/7119

**Comment by thibaultmol** [comment]
Funny how it's almost all anonymous (deleted) accounts complaining about. Classic troll behaviour. I'm pretty sure most people are fine with this. If you don't click on it, it doesn't track you ... So don't click on it if you don't care about...

**Comment by mnalis** [comment]
> Funny how it's almost all anonymous (deleted) accounts complaining about

I find that claim insulting for all the real people participating in all that dozens of threads here and on F-droid. It is easy to check with minimum of effort which ones are @ghost faked accounts, and which ones are real. 

> If you don't click on it, it doesn't track you ... So don't click on it if you don't care about...

Ummm, are you replying to the right issue here @thibaultmol? This one doesn't mention word _"track"_ in any of the comments until you've brought it up?

Also, wouldn't such argument that apply to anything? E.g. well _"Google/Facebook/Huawei/Tik-Tok/whatever wouldn't track you if you never clicked that `I Agree` button"_! And moreso, does such justification **really** belong in the app purporting to be _"user privacy friendly"_ (indeed that being one of its main selling points, compared to its MAPS.ME predecessor) ?!

P.S. the behaviour of @ghost throwaway accounts is of course childish and despicable, that goes without saying.  But it is [logical fallacy](https://en.wikipedia.org/wiki/Ad_hominem) to ignore the arguments just because of who is presenting them, instead of looking at the arguments themselves. Do not fall into that trap. Some conspiracy theorists might even argue that all the @ghost accounts are actually invented by _powers-that-be_ in order to _**discredit-by-association** all pro-privacy arguments_ (as it seems to be working quite well for that purpose)

**Comment by pastk** [comment]
Other similar issues are closed already, so let this one be. IMO the request is valid still.
