### ISSUE TITLE
Cannot search for subway, the fast-food joint

### ISSUE THREAD

**Issue by kuba-orlik** [organicmaps/organicmaps#678]
Searching for "subway" brings only results related to underground train stations, and not the fast-food joints in the city.

**Comment by dolmen** [comment]
@kuba-orlik Please edit to give more context: which country, which city

**Comment by dolmen** [comment]
Confirming. Especially when searching in France, "subway" is not ambiguous: "Subway" can only be the fast food restaurants as the underground is called "métro".
Example of search results on Nomatim:
https://nominatim.openstreetmap.org/ui/search.html?q=Subway%2C+Paris

**Comment by biodranik** [comment]
Guys, we have Organic Maps :) No fast food )

**Comment by biodranik** [comment]
It's a bug, of course, thanks for reporting it.

**Comment by pastk** [comment]
Searching for "fast food subway" or "where to eat subway" results in Subway restaurants as expected.

The issue with "subway" search is probably because its listed as an alias for subway/metro station type:
```
railway-subway_entrance|railway-station-subway|@transport
en:3Subway|3tube|3metro|3underground|U+1F687
```
And it looks like this match takes precedence over the POI name match.
Or maybe when there is a type match then full-text search is not executed at all? @vng

**Comment by TheAdventurer64** [comment]
Maybe we could have it where you have to search for "Subway station" specifically to find stations nearby.
