### ISSUE TITLE
Add display "turn on lights and fasten your seat belt" message

### ISSUE THREAD

**Issue by gtrus21** [organicmaps/organicmaps#7137]
When starting car navigation, add a pop-up window "turn on the headlights and fasten your seat belt"

**Comment by Jean-BaptisteC** [comment]
What is the point of this feature?

**Comment by gtrus21** [comment]
prevention of traffic violations

**Comment by Jean-BaptisteC** [comment]
I don't think it's a role of GPS. If we add a new screen before start routing, I'm adraid users skip screen without read it.
Keep in mind, we try do the most simple GPS for everythink.
Did you have already see this in other GPS?

**Comment by gtrus21** [comment]
I'm not asking for a new screen, but a pop-up window at the bottom (android notifications).  If the user doesn’t pay attention to it, then that’s his problem, you did everything you could.  If the user pays attention, you will prevent a violation (and maybe even save someone's life).  I haven’t seen this in other programs, you will be the first

**Comment by CaldeiraG** [comment]
I know Waze has both a headlights warning (for tunnels) and a child reminder for when you arrive at your destination. I think both can be useful in some situations. The headlights one could show up over the direction arrows area I guess

![photo1704973048](https://github.com/organicmaps/organicmaps/assets/25271504/15b469f0-66b2-4281-b678-af008f5f75e6)

As for the seatbelt it doesn't make a lot of sense to me since your car is already doing that work for you :)

**Comment by gtrus21** [comment]
I'm happy for your car, but you are not the only user of the program

**Comment by matkoniecz** [comment]
That is clear case of https://en.wikipedia.org/wiki/Alarm_fatigue and I am really dubious about benefits here.

Proper solution for both of that is car autodetecting that it is not done and for example beeping if seat belt is not engaged and someone is sitting on a seat.

That is better than showing obnoxious message that is not applicable in vast majority of cases (or will be ignored anyway).

**Comment by gtrus21** [comment]
> That is clear case of https://en.wikipedia.org/wiki/Alarm_fatigue and I am really dubious about benefits here.
> 
> Proper solution for both of that is car autodetecting that it is not done and for example beeping if seat belt is not engaged and someone is sitting on a seat.
> 
> That is better than showing obnoxious message that is not applicable in vast majority of cases (or will be ignored anyway).
> 
> In other words: please, no.

where did you see the warning light in cars of the 80s?

**Comment by matkoniecz** [comment]
Annoying million of people with pointless popup will in aggregate likely waster more human time than it will save by potentially causing people to use seat belts more (which would help only people in old cars who forgot to fasten seat belts, processed message rather than ignored it, put on seat belt, got into accident and had their injuries reduced by seat belt).

Annoying million of people with pointless popup has also its costs, including increased dismissiveness of better targeted warnings.
