### ISSUE TITLE
Freezing CarPlay

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7247]
> I use OM with a USB cable connected to my car Mazda CX-30
Since the last update it happens very often that I choose a destination of my favourites, it is showing the route, I press start navigation and then its freezing. (all done with my car buttons)
After relaunch of the app OM remembers the path and works properly even if I was already driving some hundred meters.

 > - iPhone12,1 (15.4.1)
 > - Organic Maps 2024.01.18-9

@fabwu can you please take a look?

**Comment by PaulJHaag** [comment]
Even with out routing the GPS freezes
When I switch to anoter app and switch back to OM again.
The blue arrow turns grey and will not move any further.
But the app is still responsive/working beside the GPS is not talking to the app

**Comment by PaulJHaag** [comment]
![image](https://github.com/organicmaps/organicmaps/assets/10125241/9b118787-66f0-437d-9a67-efdf926e0a51)

**Comment by biodranik** [comment]
@PaulJHaag does actual GPS position work in other apps at the same time? Could it be that GPS signal was blocked and device can't receive it for some reason?

**Comment by PaulJHaag** [comment]
Dear Alexander Borsuk,Other GPS apps work. I tried three others. After restart of the OM app it will jump to the correct position. It happens alleays when I switch to another app (any app) and switch back. The arrow changes colour from blue to grey and GPS is not working anymore. All other things work.Kind regards Paul Paul HaagKhao Nam Un329 Moo 4, Hin DatPang Sila Thong 62120Kamphaeng ***@***.***+66 6121 00 797Am 03.02.2024 um 06:23 schrieb Alexander Borsuk ***@***.***>:﻿
@PaulJHaag does actual GPS position work in other apps at the same time? Could it be that GPS signal was blocked and device can't receive it for some reason?

**Comment by biodranik** [comment]
@PaulJHaag thanks, someone else has also recently described a similar issue. Does it reproduce always? What is the easiest way to reproduce it?

Maybe recent iOS location fixes by @kirylkaveryn also fix this issue. Please let us know after the upcoming new version update of Organic Maps.

**Comment by HeldHannes** [comment]
I got a new device (Android 13 Samsung Galaxy Tab S7+) and the GPS location in other apps work fine. I even can copy the coordinates from other apps and search in OM for them and they are displayed in the correct spot on the Map. 

But OM itself can't get my location from GPS right - there is a uncertainty of nearly 1km to max 200m. 
Navigation is not possible with OM since it locates me somewhere offroad. 
Also the updating time of the location is very long: I can drive 10 minutes then it jumps somewhere near my position, but in the last two weeks never better than the 200m.

**Comment by PaulJHaag** [comment]
Dear Alexander Borsuk

after the update to OM version 2024.02.05-19 I looks fine related to my
privious GPS problem.
I can switch between apps with or without routing active. The GPS
position is not freezing anymore.
The next days I will do further test.

Thank you so much for the excellent app.

Kind regards
Paul

**Comment by Jean-BaptisteC** [comment]
@HeldHannes please check other issues with tag location or open a new issue, your commentary is out of topic here 🙂

**Comment by HeldHannes** [comment]
> @HeldHannes please check other issues with tag location or open a new issue, your commentary is out of topic here 🙂

Sorry, deleted it.

**Comment by biodranik** [comment]
> I got a new device (Android 13 Samsung Galaxy Tab S7+) and the GPS location in other apps work fine. I even can copy the coordinates from other apps and search in OM for them and they are displayed in the correct spot on the Map.

> But OM itself can't get my location from GPS right - there is a uncertainty of nearly 1km to max 200m.
> Navigation is not possible with OM since it locates me somewhere offroad.
Also the updating time of the location is very long: I can drive 10 minutes then it jumps somewhere near my position, but in the last two weeks never better than the 200m.

@HeldHannes Please check that Organic Maps is permitted to access a fine (precise) GPS location in system apps settings. Looks like you accidentally enabled only a coarse (approximate) network location when you launched Organic Maps for the first time.

Note that it's an iOS-related issue thread ;-)

**Comment by PaulJHaag** [comment]
Thank youSince the last OM update this issue disappeared Kind regards Paul Paul HaagKhao Nam Un329 Moo 4, Hin DatPang Sila Thong 62120Kamphaeng ***@***.***+66 6121 00 797Am 17.02.2024 um 07:12 schrieb Alexander Borsuk ***@***.***>:﻿

I got a new device (Android 13 Samsung Galaxy Tab S7+) and the GPS location in other apps work fine. I even can copy the coordinates from other apps and search in OM for them and they are displayed in the correct spot on the Map.


But OM itself can't get my location from GPS right - there is a uncertainty of nearly 1km to max 200m.
Navigation is not possible with OM since it locates me somewhere offroad.
Also the updating time of the location is very long: I can drive 10 minutes then it jumps somewhere near my position, but in the last two weeks never better than the 200m.

@HeldHannes Please check that Organic Maps is permitted to access a fine (precise) GPS location in system apps settings. Looks like you accidentally enabled only a coarse (approximate) network location when you launched Organic Maps for the first time.
Note that it's an iOS-related issue thread ;-)

**Comment by biodranik** [comment]
@PaulJHaag did you check what I've asked? Your symptoms are equal to other users issues, when they allowed Organic Maps to access only a coarse (approximate) network-based location, instead of precise (GPS-based) location. You can check and change it in system applications settings.

**Comment by HeldHannes** [comment]
Thanks, You were right. Permissions were only on coarse location - set them to fine. Now it works fine.
