### ISSUE TITLE
Bookmark color can be set, but the pin on the map does not change its color

### ISSUE THREAD

**Issue by JeckPeppinger** [organicmaps/organicmaps#7530]
I have a kml file made outside of organic maps, import it.
The kml uses two colors for bookmarks (red and grey) - but this does not matter for the issue.

Now select a bookmark on the map - lets say a red one.
Edit bookmark.
Change color to green.
The bookmark list shows the green, but not the pin on the map, this remains red no matter what one does.
Restarting the app did not help.

[gackeLonely Planet - India (2022) Delhi.zip](https://github.com/organicmaps/organicmaps/files/14513978/gackeLonely.Planet.-.India.2022.Delhi.zip)

kml file added.

**Comment by pastk** [comment]
All bookmarks seem to be duplicated (appear twice) in this file.
So when one changes a color its changed for the underlying bookmark only, while the top one retains the original color.

So the issue is more generic - what to do with duplicate bookmarks.
- https://github.com/organicmaps/organicmaps/issues/2220

**Comment by JeckPeppinger** [comment]
ah - yes - checked the kml and can confirm the bookmarks are doubled - funny. did not notice, and checked my original file which has no doubles. I think my case is solved now, and the topic can be forwarded for handling doubled bookmarks.
