### ISSUE TITLE
use cool eye symbols for android as well

### ISSUE THREAD

**Issue by RedAuburn** [organicmaps/organicmaps#7572]
Should use these eye symbols for bookmark visibility in android also:
https://github.com/organicmaps/organicmaps/pull/7508

**Comment by fitojb** [comment]
... redrawn in the Material style of course :)

The eyes are a much better metaphor.

**Comment by RedAuburn** [comment]
@Jean-BaptisteC you don't think so?

also, there are some already made material ones 👍️:
![image](https://github.com/organicmaps/organicmaps/assets/26939824/47f5794f-9c39-4d79-b644-00472c32d2df)

**Comment by Jean-BaptisteC** [comment]
Default checkbox is not good, because checkbox is used to select items in list not to set visibility of items.
Personnaly, I don't like eye icon to set visibility, I prefer map icon like in OSMAnd (it's a little different because he use toggle to set visibility of items)
I have found an map icon https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amap%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024 but I didn't have found version icon with bar like for eye icon.

**Comment by Jean-BaptisteC** [comment]
This icon https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Amap%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4024

**Comment by biodranik** [comment]
@euf, do you remember the reason for using a crossed-eye icon instead of a closed-eye?

**Comment by euf** [comment]
Yes, I do 🙂 This was my personal choice after trying a dozen of different designs, including Material icons. 

That's what I came up with:

![1-eye-on](https://github.com/organicmaps/organicmaps/assets/11754264/46d2f9b9-bf95-4e58-8c61-34287da32512)
![1-eye-off](https://github.com/organicmaps/organicmaps/assets/11754264/7d17a9f0-191d-4532-add7-a93b6d7bb70a)

First, I found that a closed eye is less recognizable and visually distinctive than a crossed one (simply speaking, the glyph looks too small and doesn't differ much). Crafting a good crossed one took some time, but I'm very happy with the result.

Secondly, I opted for drawing the eye icons from scratch instead of using Material ones because I was able to achieve better visual balance with other icons. In OM rounded shapes are preferred to sharper ones; icons are consistent with material by keeping 2px stroke on 24px canvas but margins are carefully chosen dependent on icon shape to make them look better next to each other; etc.

Overall, I was aiming to achieve a softer and nicer look while staying consistent and semantic. 

Maybe I could write up a github wiki page with a UI icons guideline, what do think?
