### ISSUE TITLE
A bug when building routes

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#7701]
> Additionally, I discovered an issue when utilizing the "Subway" layer:
 > 1. Turn on any option within the routing settings.
 > 2. Activate the "Subway" map layer.
 > 3. Input a "From" location.
 > 4. Change the navigation method to any mode apart from "Public 
 > Transport" and "Ruler."
 > 5. Introduce a "To" location.
 > 6. Allow the route calculation to complete before clicking on "Routing 
 > options enabled."
 > 7. Turn on any option within the routing settings.
 > 8. The new route will be calculated, overlapping the previous one.
 > You can perform steps 4-7 (apart from 5) again for another overlapping 
 > route.
 > Once you select the "Public Transport" mode and turn on any option 
 > within the routing settings, the earlier routes will no longer appear. 
 > Alternatively, removing the "From" or "To" locations will also result in 
 > the disappearance of earlier routes.

**Comment by biodranik** [comment]
@Jean-BaptisteC can you please try to reproduce and confirm it on Android?

**Comment by Jean-BaptisteC** [comment]
I have same bugs has @Altonss 
- Enable routing options in public transport routing
- Switch to car routing and enable other routing options
- Go back to routing screen -> routing is calculated with public transport

**Comment by Tmpod** [comment]
I also confirm Jean's findings on Android. Is the original report made for iOS, or? I can't seem to get overlapping routes on Android.

**Comment by biodranik** [comment]
Wasn't this issue already fixed in the recent release?

**Comment by biodranik** [comment]
Then it should be fixed.

**Comment by Tmpod** [comment]
Alright, I will try tackle this!

Would be nice to know if this (still) affects iOS as well, or if it's Android only, but I don't own an Apple device.

**Comment by biodranik** [comment]
@Tmpod on iOS, only the PT route is displayed. The issue comes from the code that automatically enables PT routing if PT layer is active.

**Comment by Tmpod** [comment]
I went looking in the code, and I believe this is because of this particular block:

https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/java/app/organicmaps/routing/RoutingController.java#L354-L358

It forcibly sets the router type to PT, disregarding any previous value. Since this function ends up being indirectly called by `MwnActivity#onActivityResult` [here](https://github.com/organicmaps/organicmaps/blob/master/android/app/src/main/java/app/organicmaps/MwmActivity.java#L1000-L1001), the app ends up always reverting to PT if you have the subway layer active.

I think a good solution would be to add `mState == State.NONE` to that condition, because we really don't want to override the routing type if we're already planning, but we do want that default if we're starting a new plan.

Thoughts?

**Comment by biodranik** [comment]
@Tmpod that sounds like a clean solution, let's try it in the PR. Also a comment for this change would be helpful.
