### ISSUE TITLE
Reduce thickness of path lines in Outdoors style

### ISSUE THREAD

**Issue by alensiljak** [organicmaps/organicmaps#7821]
**Is your feature request related to a problem? Please describe.**
I find the path line thickness in Outdoors mode a bit too much. The pedestrian paths are often wider than the highways. While this is not necessarily bad, it sometimes covers other map features and takes quite some useful space if there are many paths displayed.

**Describe the ideal solution**
Reduce the line thickness just a little bit and let us use test it in real-world scenarios.

**Describe alternatives you have considered**
Please see [this comment](https://github.com/organicmaps/organicmaps/issues/6593#issuecomment-2039409905) for comparison.

**Additional context**
Outdoors style, #2356

**Comment by alensiljak** [comment]
Actually, when compared to other apps directly, OM has the thinnest lines. They just somehow feel thick because there is no extra information (underlying or a parallel line, as in other apps). 
It may be the colouring that is making it look a bit heavier, as well. 
OK, let's leave this out for now, then.

**Comment by pastk** [comment]
> I find the path line thickness in Outdoors mode a bit too much.

Actually some people want them wider! (e.g. for bright sun light or when a screen vibrates a lot on a hanlebar..)

> The pedestrian paths are often wider than the highways.

Highways are now inherited unchanged from the main style (except the highway=service which I made thicker because it was super thin). And it'll be better to have them thicker and more visible for the outdoors style (perhaps add a contrast outline for higher zooms at least).
