### ISSUE TITLE
 HappyCow App Integration

### ISSUE THREAD

**Issue by Ralimbahere** [organicmaps/organicmaps#7993]
Hey, wouldn't it be cool if every time you find a restaurant on HappyCow, you could just tap "Open in Maps" and have Organic Maps show up as an option, just like Apple Maps, Google Maps, or Waze Maps?

It'd be awesome to be able to tap on a restaurant in HappyCow and have the location pinged automatically in Organic Maps for easy navigation.

To make this happen, we'd need to team up with the Android and Apple developers
 at HappyCow. You can reach out to them through this link: [HappyCow Contact](https://www.happycow.net/contact)

Let's make finding vegan restaurants even easier!

![IMG_C1D995AA74AA-1](https://github.com/organicmaps/organicmaps/assets/123059596/0b8dd511-5d56-4ca6-a996-ff66b9ad9b6d)

**Comment by Ralimbahere** [comment]
Also I just opened a ticket with Happycow to request the OpenStreetMap/Organic Map option to be integrated within the app.

**Comment by RedAuburn** [comment]
IMO there's no integration to be done on Organic Maps' side here, as the happycow database is closed source. OSM is the base for all other veg* place finders, so it makes sense to just use OSM instead of a separate database. 
closing this in favour of https://github.com/organicmaps/organicmaps/issues/7996 for better `diet:` handling
