### ISSUE TITLE
Evaluate use of KDE's map server

### ISSUE THREAD

**Issue by KAMiKAZOW** [organicmaps/organicmaps#80]
The [KDE project](https://kde.org/) generate and host their own map data in standard [o5m file format](https://wiki.openstreetmap.org/wiki/O5m) at http://maps.kde.org/earth/vectorosm/v1/ -- no API key or anything like that, just plain HTTP open for anyone to grab.

If I understand it correctly, one big functional difference is that those files are square tiles and not split across region borders, so an index would be required which tiles correspond to which regions (although a benefit would be that online-only use wouldn't eat so much mobile data as it wouldn't require entire regions to be downloaded).

During pre-release development you could just use that server. Before Omaps hits app stores, asking the KDE people if they're OK with the amount of extra traffic. If not, a monthly sync to an Omaps server could possibly still make more sense than generating own maps files.

**Comment by dimqua** [comment]
Looks like they aren't up-to-date currently...

**Comment by gerion0** [comment]
Afaik, this data are used for [KDE Itinerary](https://community.kde.org/KDE_PIM/KDE_Itinerary) and [Marble](https://marble.kde.org/). Especially, see [this blog entry](https://www.volkerkrause.eu/2020/07/25/updating-marble-osm-data-server.html) by @vkrause.

Of course, a featurewise connection of omaps with KDE Itinerary would be nice as well.

**Comment by vkrause** [comment]
To clarify a bit what's on that server: what you see in the listing on http://maps.kde.org/earth/vectorosm/v1/ are only the static low-resolution tiles. Those are only updated occasionally and are based on NE rather than OSM. What you don't see directly there are the high-z tiles up to zoom level 17. Those are dynamically generated based on nightly updated OSM data and at level 17 are close to raw OSM data (no filtering or geometry simplification applied, only clipping to tiles), e.g. http://maps.kde.org/earth/vectorosm/v1/17/70403/42982.o5m. That's IMHO the real value this server provides. Whether that is something helping with your use-case I don't know though :)

**Comment by biodranik** [comment]
I don’t see any value now for OMaps. We take the whole planet and generate all compressed maps. What is the use case to download raw data again from any server?
