### ISSUE TITLE
Replace HPCL text to petrol station Logo

### ISSUE THREAD

**Issue by Yashbhosale00** [organicmaps/organicmaps#8001]
**Steps to reproduce**
1. Go to map screen and find petrol station location

**Expected behaviour**
Petrol pump type should be shown

**Screenshots**
![WhatsApp Image 2024-04-27 at 1 36 40 AM](https://github.com/organicmaps/organicmaps/assets/121059725/9cd78183-ea03-49fb-9b95-901b45966ebd)
![WhatsApp Image 2024-04-27 at 1 36 40 AM(1)](https://github.com/organicmaps/organicmaps/assets/121059725/66663dc9-73bc-4e0c-b387-fa5bde966668)

**System information:**
 - Android 10
 - Samsung

**Comment by patepelo** [comment]
Hey, this is an expected behavior. 

In your first example the node doesn't have a name, so it takes the title from the category type. The next sub tag corresponds to helpful information like the operator, in this case. Maybe we should consider repeating the category name in the sub labels in cases without names.

**Comment by patepelo** [comment]
This is a map data problem and an intended handling of the situation.

**Comment by Yashbhosale00** [comment]
> This is a map data problem and an intended handling of the situation.

"Yes But I tap on any petrol pump station or hospital, it should show a more attractive logo to enhance the user interface."

**Comment by patepelo** [comment]
> more attractive logo
Maybe this?
https://github.com/orgs/organicmaps/discussions/1052
