### ISSUE TITLE
Error opening tracks (.gpx .kml) from Total Commander

### ISSUE THREAD

**Issue by snooppr** [organicmaps/organicmaps#8532]
when trying to open .gpx, .kml tracks from TC using OM an error occurs, see screenshot.
![om](https://github.com/organicmaps/organicmaps/assets/61022210/6534af71-1bc0-4e6b-9207-2a56d88b6fe9)

The tracks are fine, they open from TC in any other GPS applications (except OM).

The bug is also notable because tracks can still be opened from TC, but in a different way: TC, press and hold the track and call up the menu, select the second item "open with" and select the OM application, the track is successfully imported. But if you select the first item in the TC menu "open file with", the same error will occur.

Tracks are successfully imported from the native file manager, i.e. the problem is TC<>OM.

version:
Android 9;
TC 3.50d

**Comment by Misalf-git** [comment]
Could it be about Total Commander sending either `file://xxx.kml` or `content://xxx.kml`?

If I got it right, more recent Android versions restrict static `file://` urls across apps and Google wants apps to use `content://` urls instead, even for unproblematic file locations.

**Comment by biodranik** [comment]
The error clearly says that permission has been denied.  This should be fixed on the Total Commander side. 

More details can be found here:
https://developer.android.com/training/data-storage/shared/documents-files

**Comment by Misalf-git** [comment]
On my system (Android 12) using TC to send a .gpx/.kmz file to OM via "open with..." and having the `file://url` checkbox checked results in the same error.
But that's an optional feature (f.e. to workaround incompatibilities with older apps).
If I leave the `file://url` checkbox unchecked it works.

However, for me TC's default action when tapping a .gpx/.kmz file opens OM which then correctly imports the file.

Intercepting this intent (using "App Manager") shows that TC sends a `content://` url by default on my system.

I'm not fluent with Android intents, otherwise I'd have tryed to `am start` a `file://` url via terminal.

@biodranik , would OM with its permissions be even able to handle `file://` urls?
"Permission denied" is a typical non-descriptive error message.

@snooppr , maybe your system's current app configuration for default file handling is wonky and always uses `file://` url for .gpx/.kmz files by default? I'm just guessing - no idea if Android would do that.
Like maybe check Android's `Settings` -> `Apps` -> `Organic Maps` -> `Default open` -> and tap `Delete current "Default open" settings` (don't delete App-Data, it would delete your bookmarks etc).

Note that Total Commander also has the ability to set default "open with..." apps for choosen file extensions in TC's settings. That would be an intentional user action, though, that you would probably remember having done.

**Comment by biodranik** [comment]
@Misalf-git OM explicitly does not have read/write external storage permission (which allows other apps to read sensitive user data on Android 10 and below). So OM can't open `file://` urls.

**Comment by snooppr** [comment]
No problem TC. OM does not require permissions to access storage, hence the error on Android 9 (checked on agalogs). If this is sec. OM policy, nothing can be done. I will close this.

**Comment by Misalf-git** [comment]
@snooppr 
> Note that Total Commander also has the ability to set default "open with..." apps for choosen file extensions in TC's settings.
 
![resized_Screenshot_20240624-175058_Total Commander2024-06-24_17-51-20_1414.png](https://github.com/organicmaps/organicmaps/assets/72605561/9dd52b2f-7adb-408d-a9e1-ad0004f504db)

**Comment by snooppr** [comment]
> @snooppr
> 
> > Note that Total Commander also has the ability to set default "open with..." apps for choosen file extensions in TC's settings.
> 
> ![resized_Screenshot_20240624-175058_Total Commander2024-06-24_17-51-20_1414.png](https://private-user-images.githubusercontent.com/72605561/342407919-9dd52b2f-7adb-408d-a9e1-ad0004f504db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDY1NjcsIm5iZiI6MTcxOTI0NjI2NywicGF0aCI6Ii83MjYwNTU2MS8zNDI0MDc5MTktOWRkNTJiMmYtN2FkYi00MDhkLWE5ZTEtYWQwMDA0ZjUwNGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE2MjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NWQ3N2ExYzVjYmQ2NzZhNDYxMDA4N2YyNTczMGVhMzY5ZjAxY2QxYTkyZmI4N2NiZGRiYzQ5Nzk4ZTc2N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2QC18h7GBRQvnEYomrunAeHJY7ckf-A-HbbLmTgM8h4)

I know about it and wrote about it in my first message. This workaround is not very convenient, and newbie TC users will think that everything is simply broken.
