### ISSUE TITLE
What3Words (w3w) coordinates

### ISSUE THREAD

**Issue by nitricware** [organicmaps/organicmaps#8584]
Austrian emergency services like the ambulance use w3w coordinates. If organic maps would implement a feature to display w3w coordinates like other coordinates systems, this enhancement would benefit emergency services and people requiring help. 

**Additional context**
https://developer.what3words.com/public-api

**Comment by biodranik** [comment]
Please check https://github.com/organicmaps/organicmaps/issues/7038 and https://github.com/organicmaps/organicmaps/issues/3437

**Comment by nitricware** [comment]
> Please check https://github.com/organicmaps/organicmaps/issues/7038 and https://github.com/organicmaps/organicmaps/issues/3437

Thanks. GitHub iOS search returned 0 results when searching for w3w 🙄

**Comment by Jackalaq** [comment]
It is also used and preferred by UK emergency services.  Rather than simply close this as 'not planned', could this be reopened, discussed and considered?

Ah, having researched it a bit, perhaps I know why...
The database is proprietary and the W3W business are being litigious.  How very late-stage-capitalist.

Could I therefore suggest an option to lookup a location at W3W.co included on the 'copy location menu'?  This would simply generate then open a URL in the format:
                    w3w.co/55.003613,-2.373925
Without any proprietary software use or infringement, nor changed OS permissions, it would resolve to:
                    ///looms.mocking.skips
...providing that the user had internet access of course.  Could save some lives.

**Comment by defiling9046** [comment]
> Hi [@nitricware](https://github.com/nitricware) It is also used and preferred by UK emergency services. Rather than simply close this as 'not planned', could this be reopened, discussed and considered?
> 
> Ah, having researched it a bit, perhaps I know why... The database is proprietary and the W3W business are being litigious. How very late-stage-capitalist.
> 
> Could I therefore suggest an option to lookup a location at W3W.co included on the 'copy location menu'? This would simply generate, then open, a URL in the format: w3w.co/55.003613,-2.373925 Without any proprietary software use or infringement, nor changed OS permissions, it would resolve to: ///looms.mocking.skips ...providing that the user had internet access of course. Could save some lives.

Sounds like a good idea
