### ISSUE TITLE
All road ref numbers are displayed.

### ISSUE THREAD

**Issue by VladimirMorozov** [organicmaps/organicmaps#873]
Tallinn is littered with road ref numbers, map is hard to use.
They should be displayed only for important roads or there should be an option to turn them off.

![изображение](https://user-images.githubusercontent.com/2279813/126038509-1c857a3f-c053-4a1d-bc99-e54bdf92c20e.png)

**Comment by biodranik** [comment]
@pastk @vng why does it happen in Tallinn only?

**Comment by mikamikaWolt** [comment]
Some more info.
Most roads in the city on the map are shown with these weird numbers. But when tap on such label with the number, info panel will show correct street name.
This looks like an issue with displaying the data in particular area, rather than missed or incorrect data on the map.

**Comment by vng** [comment]
Tallinn is so well-mapped that street way's are combined into street relations (just like DMBS), that define additional params like ref.
For example https://www.openstreetmap.org/relation/8821312

My proposal here is to remove "shield" drawing rule from highway=residential.

**Comment by biodranik** [comment]
> My proposal here is to remove "shield" drawing rule from highway=residential.

That sounds easy and reasonable. Let's do it )

**Comment by VladimirMorozov** [comment]
IMHO these shields are still very distracting. Is it possible to make a region-specific change?

**Comment by vng** [comment]
Unfortunately no at this moment.

**Comment by biodranik** [comment]
It doesn't look right. We already have city borders, what about deleting shields in cities for these types of roads at the generation stage? Or maybe a simple dirty hack `if (Estonia) ...`?

**Comment by pastk** [comment]
I found that road shields have their  min vis zoom hardcoded to 10 (used for prioritization in the displacement logic), so it might make priorities of road shields of even lesser roads very high and they will displace most of other POIs.
It was added in 85f0ffaff1d39088cbd105c102df9cb4e3bad62

**Comment by biodranik** [comment]
The reason was to give local ads (that are not supported by OM anymore) a higher priority. Can we safely revert it for shields?

**Comment by pastk** [comment]
> The reason was to give local ads (that are not supported by OM anymore) a higher priority. Can we safely revert it for shields?

It turned out to be more complicated...
Removing that hardcoded minVisibleScale doesn't make any change at z14-, however at lower zooms road shields start to displace names of lakes, towns and even the "Tallinn" caption and star icon!
There are a few reasons to it.
1. `m_minVisibleScale` is always 0 for lines and areas (its not used for priority calculation there), but road shields are processed as a part of a line, hence they inherit this 0 value - which makes their overlay priority super high. Its a bug. @vng 
2. Even with above fixed, road shields will probably have too high priority still. E.g. motorways are visible from z7, hence their shields will use z7 for prioritization also, however those shields are visible from z10... I.e. the motorway shields will appear at z10 but with a priority higher than features appearing at z8- (e.g. captions for smaller towns and many other things).

**Comment by biodranik** [comment]
The priority for shields should be customizable. We may even remove them completely (or enable them only on the most detailed zooms) in hiking and city tourism styles.

**Comment by pastk** [comment]
> The priority for shields should be customizable. We may even remove them completely (or enable them only on the most detailed zooms) in hiking and city tourism styles.

https://github.com/organicmaps/organicmaps/pull/4426 will make them customizable just like other draw elements.
