### ISSUE TITLE
Add to the Accrescent.app store 

### ISSUE THREAD

**Issue by JaByteOS** [organicmaps/organicmaps#8747]
Have you considered or are you planning on putting your app on Accrescent (app store focused on security, privacy, and usability) 

Accrescent is a private and secure Android app store built with modern features in mind.

It was just endorsed by GrapheneOS (considered by many to be the most private and secure mobile operating). GrapheneOS also now has accrescent in their app store. 

Right now there is only 9 apps on it. So any new apps added get great installation opportunities from the privacy and security minded community. 

Anyway, I really like your app, and would love to see it on Accrescent because it's so easy to install and update apps compared with f-droid, plus much more secure! 

Thank you for taking the time to read this. I'm a security and privacy conscious individual, not associated with Accrescent or GrapheneOS (though I use them both).

Xoxo Olivia

**Comment by RedAuburn** [comment]
looks like developer registration is invite-only:

> Registration not permitted
> Accrescent developer registration is currently invite-only. Please come back when registration opens for everyone.

maybe ask them to invite organic maps?

**Comment by JaByteOS** [comment]
Wow, thank you for looking into this! And for your time. I will definitely ask them to invite you (not sure how that process works).

**Comment by JaByteOS** [comment]
Here's what I found:

"Sign-up is not yet available to the general public and is only permitted for allowlisted GitHub accounts. This choice was made to ensure that all developers on Accrescent are willing to tolerate the lackluster user experience, console bugs, and frequent policy changes resultant of Accrescent being in its early stages. If you are not allowlisted and are still interested in publishing on Accrescent, you may contact us at contact@accrescent.app to request being allowlisted."

So I guess just email. I contacted their matrix group and they said they were currently working on some back end coding, then would follow up with requests.

**Comment by Anvil5465** [comment]
Looks like it was just added to Accrescent

**Comment by JaByteOS** [comment]
Wow! Amazing! I see it, how cool is that! Excellent work!

**Comment by biodranik** [comment]
Why fdroid version should be added there?

**Comment by biodranik** [comment]
I'm lost here: install an apk built and signed by fdroid but not from fdroid for more security?...

**Comment by biodranik** [comment]
What are the benefits of supporting that build? The cons are that it will take more of our time.

P.S. There is always an option to build fdroid flavor locally by `cd android; ./gradlew installFdroidRelease`

**Comment by biodranik** [comment]
You can use Obtanium to auto-update from our GitHub releases directly, without waiting for approval in any stores.

**Comment by Jeffrey2307** [comment]
> What are the benefits of supporting that build? The cons are that it will take more of our time.
> 
> P.S. There is always an option to build fdroid flavor locally by `cd android; ./gradlew installFdroidRelease`

Why should it take more of your time? You could just publish the Web-APK instead of the one in Accrescent. 

> What are the benefits of supporting that build? The cons are that it will take more of our time.
> 
> P.S. There is always an option to build fdroid flavor locally by `cd android; ./gradlew installFdroidRelease`

Why should it take more time? I think what he wanted to say way to publish the Web-APK on Accrescent, instead of the one which is now in Accrescent. If I need to be honest, I would love to see that and prefer his Idea more, but I can understand why this Build was chosen, because of Android Auto and Google Location Services (which can be disabled in Settings too)

**Comment by Jeffrey2307** [comment]
> Honestly I don't really know what the difference between the Google and Web-APK are. Both contain the proprietary Google libraries.

But if you don't know the difference or in general much about the Builds, why are you spreading wrong information? Because you said both contain Google libraries and that's not true. The Web-Apk is a standalone Build, without being a Google or F-Droid Build. It is only signed by the Developers.

> There would need to be an entirely new build without the proprietary libraries that needs to be maintained as well, this build does not exist at the moment.

There is! And it is the Web-Build (Apk). It exists, but it would be better to be sure, before saying something. They put effort in it.

**Comment by Jeffrey2307** [comment]
> The Web-APK does contain proprietary Google libraries and this can be checked by any application such as LibChecker or App Manager. Since you seem to be unable to check basic information before accusing someone of spreading misinformation, I'll gladly point you to the names of the Google libraries that the Web-APK contains.

Oh then I'm sorry!  was just speaking of what I heard from the CEO of Organic Maps and they never mentioned that! Your right and I'm sorry for accusing. I did not know this way of checking, since I mostly just ask the Teams from the Apps.

> These libraries/services are present in both the Google APK and the Web-APK but are not present in the F-Droid APK: `com.google.android.gms.common.api.GoogleApiActivity` `com.google.android.gms.version`

Oh thank you for listing and searching about this topic!

> The only differences that I can tell between the Web-APK and the Google APK is that they have different signing keys and are published in different places. There are no differences in the libraries.

Yea I understand now what you mean. I think I was more saying about the Build. 

> If the Web-APK was indeed a FOSS build of Organic Maps, don't you think the developer would have simply told me that, rather than asking me what the benefits of maintaining a FOSS build would be?

True, I had these feelings too, when I asked them before.

> Next time conduct basic research about your claims before accusing anyone of spreading misinformation.

I agree and I'm sorry. I really did not know this way of checking and I think I was more saying about the Build, rather than the libraries. So there was a misunderstanding from my side! And I deleted these posts from before, because I talked past you.
