### ISSUE TITLE
Add ability to create power=substation in editor

### ISSUE THREAD

**Issue by Jean-BaptisteC** [organicmaps/organicmaps#8763]
In the OSM-FR telegram channel, a user as asked to add the ability to create power=substation in the editor it can be useful to add minor substation.

On editor, we need to add the ability to add the name of the substation and the operator.

**Comment by biodranik** [comment]
How substations are useful to the majority of users?

**Comment by Jean-BaptisteC** [comment]
The user on telegram told me he needed to switch to everydoor to add the substation.
I can ask you the same question, for the map styles, why we have added substation in the map style?
IMO, all POI visible should be addable in the editor.

**Comment by biodranik** [comment]
Why substations were added initially? How are they useful to users? I've never heard about any use-case except "I'm actively mapping into OSM, and would like to add/see substations there".

I'm asking because substations are mostly _area_ objects, while OM's editor can only add _point_ (_node_) objects.

**Comment by Jean-BaptisteC** [comment]
Yes, you're right substations are in most case mapped like the way (building or landuse) and node is used for minor substation (street_cabinet or transformer on power pole)
