### ISSUE TITLE
[ios] Recent Track doesn't work reliably

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#9145]
In a short amount of time, several track interruptions were visible on the map as gaps. Launching OM starts recording again, then it stops after some time.

It could be iOS 18 (still beta) issue where it was reproduced, or any iOS device issue. Any feedback from iOS 17 owners is welcome.

It could be related to not requesting "Always" location permission. Looks like the system pauses location updates due to this property set to YES and does not resume updates automatically: https://developer.apple.com/documentation/corelocation/cllocationmanager/pauseslocationupdatesautomatically?language=objc

CC @kirylkaveryn

**Comment by biodranik** [comment]
1. The existing feature that worked is broken and doesn't work anymore.
2. It is not clear yet if it was broken by recently merged changes to the master branch (e.g. related to track recording), or reproduces only on iOS 18.
3. After a proper investigation and testing we can either remove the blocker status or fix it.

**Comment by map-per** [comment]
I was curious to test it out on Android 10 and 14, but I got similar issues in a short 10 min test:

Sometimes the recording doesn't start, or the location is not updated any more after a while in the background leading to a straight line connection instead of the actual route.

As the track recorder is in the master: I don't think it is a good idea to release it in this state.

**Comment by biodranik** [comment]
Testing confirms that this issue has been fixed by https://github.com/organicmaps/organicmaps/pull/9171
