### ISSUE TITLE
barrier=cycle_barrier + bicycle=dismount are not respected by bicycle routing 

### ISSUE THREAD

**Issue by biodranik** [organicmaps/organicmaps#9233]
https://www.openstreetmap.org/node/7190290475

Car | Cycling | Foot
----|---------|-----
![выява](https://github.com/user-attachments/assets/dc32944b-a3a8-4451-81b8-09e710642ab3)|![выява](https://github.com/user-attachments/assets/b350b881-d7bb-4283-a30e-0ba959a51b91)|![выява](https://github.com/user-attachments/assets/8fcff1e2-4958-4fb1-b325-73cb06b4c195)

[barrier](https://wiki.openstreetmap.org/wiki/Key:barrier?uselang=en)
  	[cycle_barrier](https://wiki.openstreetmap.org/wiki/Tag:barrier=cycle%20barrier?uselang=en)

[bicycle](https://wiki.openstreetmap.org/wiki/Key:bicycle?uselang=en)
  	[dismount](https://wiki.openstreetmap.org/wiki/Tag:bicycle=dismount?uselang=en)

CC @vng

**Comment by Po11da** [comment]
I should probably comment on this since I started the discussion. Basically, Organic seems to believe cycling barriers aren't passable when they require dismounting, thus creating significantly longer and completely unnecessary paths to target. In some cases it may even lead to "no route possible" error even though the route exists, but requires dismounting the bike at least once.
