### ISSUE TITLE
multiply stop points on the route

### ISSUE THREAD

**Issue by DenisSouth** [organicmaps/organicmaps#966]
How can I add more then 3 (A,B,C) stops on a route? I need at least 30 stops to plan route for hiking.
Is there some computing issues or I can fork repository and change some number somewhere from 3 to 30?

maybe the API https://openrouteservice.org/dev/#/api-docs/v2/directions will be handy 
it allows to calculate route

**Comment by biodranik** [comment]
We can't say now about the real reasons but can assume that it was mostly related to UI. It would be great if you can play with the code and investigate what is the real blocker here.

**Comment by DenisSouth** [comment]
I think I found something 
https://github.com/organicmaps/organicmaps/blob/master/android/res/values/integer.xml
`      <integer name="pp_buttons_max">4</integer>`

https://github.com/organicmaps/organicmaps/blob/master/android/src/com/mapswithme/maps/widget/placepage/PlacePageButtons.java#L288

```
mMaxButtons = 4
if (addStop >= mMaxButtons)
{
        from = res.indexOf(Item.ROUTE_FROM);
        if (addStop > from)
          Collections.swap(res, from, addStop);
}
```
Could it be so easy to fix, by changing pp_buttons_max to something else?

**Comment by biodranik** [comment]
You can try and tell us :)

**Comment by Endem10n** [comment]
It's about buttons count in PlacePageView, not about stops count at the route, if I do not mistake.

**Comment by CasparNuel** [comment]
Any update on this? For some reason I cannot get graddle to properly build the project, so I cannot test either of the suggestions made in this thread. It would however be very helpful if it was possible to have more than 3 stop on a route.

**Comment by DenisSouth** [comment]
I tried to build this project approximately 10 times with different environment settings, on 2 PC but all tries failed.
I think for 1..20  stops routes would be easier to use  https://maps.openrouteservice.org/ or create an application around their API

**Comment by biodranik** [comment]
@Endem10n is right, it's not related to the number of stops.

**Comment by CasparNuel** [comment]
I have been looking in to this because I think it would be a big improvement to be able to have more than 3 stops.

Basically, `setButtons()` in `PlacePageView.java` checks if it is allowed to display the "add stop" button by checking `isStopPointAllowed()` function boolean value.

`isStopPointAllowed()` however, goes into native cpp code:
`frm()->GetRoutingManager().CouldAddIntermediatePoint();` in File `Framework.cpp`.

I have not enough skills to dig further into this, as my knowledge of cpp and native android code is very minimal.


The issue seems to be more complicated than just a button not showing. Maybe a limitation of the routing Algorithm right now?

Maybe a project dev can take a quick look in the cpp code to confirm what `CouldAddIntermediatePoint();` actually checks for?

**Comment by CasparNuel** [comment]
@DenisSouth I managed to compile a version that allows 50 stops.

Just like @Endem10n and @biodranik stated, the limit of 3 stops is most likely due to UI reasons: there are only 3 stop sprites (icons): A, B, C.

First, I tried to make a generic icon (without letters) and use that instead, but I had some issues understanding how the code interacts with the icons. There are some files that end in .sfd which list icons, but I don't understand how I can generate them properly with my new sprites.

So instead, I modified the code so that it just gives every stop the "A" icon. It's not the best solution but it works and allows for 50 intermediate stops to be added.

![Screenshot_20210820-032611.png](https://user-images.githubusercontent.com/73889285/130164852-f8e34797-3d25-444e-8de5-f45618688ef9.png)

I'm pretty sure I could increase it above 50 without breaking the code, but I had to set some max value in the cpp file.

**Comment by DenisSouth** [comment]
@CasparNuel Could you share the name of .cpp file and variable name related to the number of stops?

I researched resource files.
You can open "_name_.sdf" file with a text editor, it's XML with coordinates and icon name, which .cpp code crops from neighboring "_name_.png" 

I made Python code to display icons from organicmaps/data/resources-6plus_dark/ 
symbols.png + symbols.sdf
```
import cv2
import xmltodict
root_path = "organicmaps/data/resources-6plus_dark/"
filename = "symbols"

with open(root_path + filename + ".sdf", 'r') as file:
    data_raw = file.read()

xml = xmltodict.parse(data_raw)
data = xml.get('root', {}).get('file', {}).get('symbol', {})

pic = cv2.imread(root_path + filename + ".png")
print(pic.shape)
for loc in data:
    minX, maxX = int(loc.get('@minX', 0)), int(loc.get('@maxX', 0))
    minY, maxY = int(loc.get('@minY', 0)), int(loc.get('@maxY', 0))
    name = str(loc.get('@name', "--"))
    if "route-point" in name:
        crop = pic[minY:maxY, minX:maxX]
        cv2.imshow(name, crop)
        cv2.waitKey()
        cv2.destroyWindow(name)
```

Coordinates of route points sit in lines
```
  <symbol minX="1792" maxX="1863" minY="200" maxY="271" name="route-point-start"/>
  <symbol minX="282" maxX="382" minY="0" maxY="95" name="route-point-finish"/>
  <symbol minX="1863" maxX="1934" minY="200" maxY="271" name="route-point-a"/>
  <symbol minX="1350" maxX="1421" minY="200" maxY="271" name="route-point-b"/>
  <symbol minX="1621" maxX="1692" minY="200" maxY="271" name="route-point-c"/>

```
I think I will be able to generate 50 icons more and I suggest switching from letters to numbers
so route will be like that [point-start, 1,2,3,4,5,...., point-finish]

**Comment by biodranik** [comment]
@DenisSouth sdf files are auto-generated by `tools/unix/generate_styles.sh`, I don't recommend editing them. It's better to find a good icon source or draw it programmatically to avoid polluting texture and increase runtime memory requirements.

**Comment by DenisSouth** [comment]
![dots](https://user-images.githubusercontent.com/31843379/130194558-e2dc1adf-c732-4e9e-ac2c-7e7db5270e2f.png)

<img src="https://your-image-url.type" width="100" height="100">
I made generator and image, 0-99, 102x102px 

According to 
https://github.com/organicmaps/organicmaps/blob/master/tools/unix/generate_symbols.sh
I assume optipng may generate sets of images for different screen resolution
```
import cv2
import numpy as np

LIMIT = 100
COLS = 10

HEIGHT = 102
WIDTH = 102
CENTER = (51, 46)
CIRCLE_INNER_R = 34
CIRCLE_OUTER_R = 44

GREEN = (64, 179, 54, 255)
WHITE = (255, 255, 255, 255)

TEXT_FACE = cv2.FONT_HERSHEY_DUPLEX
TEXT_SCALE = 1.4
TEXT_THICKNESS = 2

TEMPLATE = np.zeros((HEIGHT, WIDTH, 4), dtype=np.uint8)
cv2.circle(TEMPLATE, CENTER, CIRCLE_OUTER_R, WHITE, -1)
cv2.circle(TEMPLATE, CENTER, CIRCLE_INNER_R, GREEN, -1)

rows = int(np.ceil(LIMIT / COLS))

REZ = np.zeros((HEIGHT * rows, WIDTH * COLS, 4), dtype=np.uint8)

y = x = 0
w, h = WIDTH, HEIGHT
cnt = 0
for i in range(0, LIMIT):
    img = TEMPLATE.copy()
    text = str(i)
    text_size, _ = cv2.getTextSize(text, TEXT_FACE, TEXT_SCALE, TEXT_THICKNESS)
    text_origin = (CENTER[0] - text_size[0] // 2, CENTER[1] + text_size[1] // 2)

    cv2.putText(img, text, text_origin, TEXT_FACE, TEXT_SCALE, WHITE, TEXT_THICKNESS, cv2.LINE_AA)
    REZ[y:y + h, x:x + w] = img

    x += WIDTH
    cnt += 1
    if cnt == COLS:
        cnt = 0
        y += HEIGHT
        x = 0

cv2.imwrite("dots.png", REZ)
```

**Comment by CasparNuel** [comment]
@DenisSouth @biodranik -- I don't fully understand just yet.

I understand that symbols.png and symbols.sdf are required to display the icons. Symbols.sdf shows the location of the icon on the bitmap.

But how would someone add an icon? Let's say I wanted to add the 1->99 icons, how would I go about doing that?

Do I need to be able to edit symbols.png, or am I overlooking some tool that does that for me?

**Comment by DenisSouth** [comment]
@CasparNuel Can you try to rename resource ?
for example 
 <symbol minX="1863" maxX="1934" minY="200" maxY="271" name="route-point-a"/>
to 
name="route-point-aaa
and change it in the code from "a" to "aaa", ​then to compile project?

maybe we may add some icons  that way

**Comment by DenisSouth** [comment]
@biodranik What is the best course of action for the stop points icons problem? May we use separate images instead of "sprite list" sdf +png?
I think it would be easier to implement, to change, and also it will require less amount of memory.

**Comment by biodranik** [comment]
1. Icons should be on the symbols.png/sdf texture to work.
2. Adding too many similar icons is a big overhead, because it consumes expensive graphics texture memory.
3. Ideally, only one icon should be added, and a letter or number inside is dynamically rendered ("merged") at the time of drawing.
4. Before doing it in the right way, it makes sense to do it in the "let's try it" way, e.g. let all icons be a C icon. It would be great to take a look at the PR, test how it works on all platforms, and then decide what to do with icons.

**Comment by DenisSouth** [comment]
How can we proceed the test? Should it be commit into some 'beta testing' brunch of project?
I can try to use apk on several android devices

**Comment by CasparNuel** [comment]
@biodranik So we should manually add the icon to the png and sdf files? Or is there some utility to add `some_image.png` to the icons bitmap and sdf files automatically?

**Comment by biodranik** [comment]
Let's start with a PR into the master branch, you or we can attach apk for testing.

**Comment by biodranik** [comment]
> @biodranik So we should manually add the icon to the png and sdf files? Or is there some utility to add `some_image.png` to the icons bitmap and sdf files automatically?

Do not edit files manually. They are autogenerated and will be overwritten. The logic should be in the script I referenced above, I assume it scans all pngs or has their list hardcoded somewhere. Sorry I can't check the code right now.

**Comment by DenisSouth** [comment]
<img src="https://user-images.githubusercontent.com/73889285/130164852-f8e34797-3d25-444e-8de5-f45618688ef9.png" height="300">

@CasparNuel May you please describe changes what you made to get this result, or pull request them to master branch?

**Comment by CasparNuel** [comment]
@DenisSouth I'm having some trouble with git and GitHub.

In order to compile this app I had to use a diffrent linux installation than I usually use, so my SSH keys aren't correct anymore. I'll launch a PR somewhere this weekend when I have git and GitHub configured correctly on this machine.

As for the icons: programmatically drawing the index may be more difficult than it seems. When defening the order of the dots (A-B-C or 1-2-3) the code does some checks wether or not some intermediate stops should be swapped (A-C-B -> A-B-C). I'm afraid this code could complicate the drawing of the index in the circle.

Instead, I tought to maybe use some sort of "+' icon, or a thumbtack icon.

The advantage is that you can use a single sprite for stops that is easily recognized.

The disadvantage is that you cannot quickly see how many stops you have, and for more complex routes it may be hard to figure out their exact order.

**Comment by DenisSouth** [comment]
@CasparNuel What Linux do you use ?) I Tried to compile it on latest Mint but it failed few times, each try was about 40min

**Comment by CasparNuel** [comment]
@DenisSouth I usually use mint, but compilation kept running to a halt, my computer would become very slow and after an hour the build process would fail due to Ninja not having access to enough RAM.

So to make this build compile, I loaded Ubuntu onto my workstation. It's a lot faster but it's pretty much a clean install of Ubuntu so none of my git configurations are correct.

I'll fix that and make a PR as soon as I can. I'll also try to implement the "+" sign.

**Comment by biodranik** [comment]
+ sign is a bad idea if it breaks the current experience. Using a "C" icon for every point after the C looks less intrusive because most users do not use more than 3 stops.

**Comment by CasparNuel** [comment]
@biodranik @DenisSouth A repeating "C" after 3 stops is possible, or even a repeating "+" after 3 stops is possible.

I only need to figure out how to generate the resources properly, do I manually add the "+" resource to all the folders?

`organicmaps/data/styles/clear/style-clear/..........` or is there some script that can do this for me when I give an image?


I'd prefer a repeating "+" (after 3 stops) over a repeating "C", but that's personal preference. 

What do you guys think? And how are the resources handled?

**Comment by biodranik** [comment]
Please start with reusing one of the already existing icons in the texture. "+" after A, B, C should look better. It would be way easier to fix just the icon later after testing the code.

**Comment by CasparNuel** [comment]
@DenisSouth @biodranik I was able to set up GitHub on my machine and share my changes.

I've cleaned up a lot of my testing, the changes in the PR are very minimal. During testing I changed a lot more, but that was unnecessary. 

The only thing that's left to be done, after testing of course, is to add the "+" icon to the bitmaps, and change the according line of code with the correct name (`name = route_point_plus` or something similar) to actually show the "+" icon instead of a repeating "C" icon.

I have also not tested how much the routing algorithm can handle. I've set the upper limit for stops at 100 right now. Maybe it could handle more, or maybe it could handle less. Someone should test this and adapt the max value accordingly.

https://github.com/organicmaps/organicmaps/pull/1141

**Comment by CasparNuel** [comment]
I'm also getting the DCO sign-off alert. I'm not familiar with this, should I follow those steps or is this not important?

**Comment by DenisSouth** [comment]
@biodranik  Could you please compile some apk with changes to test it?
https://github.com/organicmaps/organicmaps/pull/1141/commits/8adcfc4035247b4c59e04a76974453280cb8388e

**Comment by CasparNuel** [comment]
@DenisSouth It appears that I cannot share the apk in a github message, or I can't figure out how to do it (drag and drop only seems to work for images on my linux FireFox).

I've uploaded it to wetransfer, so it'll only be available for two weeks or so...

Here you go:
https://we.tl/t-UuTsaPXWzE

Currently, the stops are using A-B-C-C-C..., the "+" asset has to be added and then it can be easily changed in the code, I added a comment where it should be done.

I've noticed one issue with the stops if you add more than four in a weird shape: when you make the route, the app will re-order your stops so that they will always be in the correct order. However, when you close and open the app, this order is not preserved and you get a messy route.

First time making route:
![Screenshot_20210821-171906](https://user-images.githubusercontent.com/73889285/130326530-c58dab1e-3e8d-4bc3-bcd6-21f767663779.png)

Loading route after closing app: (map was not fully loaded yet, but you can see the route has been changed to some weird order)

![Screenshot_20210821-171930](https://user-images.githubusercontent.com/73889285/130326560-3aaa021c-b53b-4d2c-a625-2b7c6833db86.png)

**Comment by biodranik** [comment]
Interesting, looks like there is an issue with points serialization somewhere in the core code.

**Comment by DenisSouth** [comment]
@CasparNuel  android 10 says "app not installed" while this Apk installation.

What  if you will copy icon A instead of C, will whole route be messed up?

```
      case 0: name = "route-point-a"; break;
      case 1: name = "route-point-b"; break;
      case 2: name = "route-point-c"; break;
      default: name = "route-point-c"; break;

change to 
      case 0: name = "route-point-a"; break;
      default: name = "route-point-a"; break;


```

**Comment by CasparNuel** [comment]
@DenisSouth this apk is for armeabi-v7a, you most likely have a v8.

Or, it could be you have to uninstall the organic maps app first, and after that try to install my apk. My apk is not signed so the signatures will mismatch if you still have the original app installed.

If you put the route-point-a in the default case, the app will not break. Everything would just have the "a" icon.

**Comment by pastk** [comment]
Done in #1141
