### ISSUE TITLE
Routing across several unloaded areas (BC -> Alberta).

### ISSUE THREAD

**Issue by vng** [organicmaps/organicmaps#980]
1. Download Victoria (BC) and Edmonton (Alberta). Route Victoria -> Edmonton says "No route found" without any additional options [BUG]
2. Download Vancouver (BC). Route Victoria -> Vancouver is ok through the Swartz bay [OK]
3. Building Vancouver -> Edmonton route says that need to download Ontario North which is far east from needed route ?! [BUG]

**Comment by biodranik** [comment]
The issue actually occurs for every route that leaves the "Kelowna" map that the app initially downloaded.  It invariably wants to download "Ontario - North" regardless of destination (whether it be in BC or AB), when this map is literally 1000s of km away from the route.

A specific problem is routing from Kelowna, BC, to Jasper, AB.  With only the Kelowna map loaded, it wants to download "Edmonton" and "Ontario - North" maps. Once the maps are finally done, the routing fails because it did not download the map it actually needed (which I figured out was "BC - Centre").  Even if routing starts with all BC and Alberta maps loaded, it still asks to download the Ontario map, but at least routing works properly.  However, "BC - Centre" is removed, it will route around the missing map without any warning, and offer a needlessly long route.
